<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('government-ngos','per-diem-compliance-calculator');
ob_start();
?>
<h2>Check travel expenses against per-diem limits</h2><p class="lead">Enter the policy rates that apply to your trip and compare them with actual lodging and meal expenses.</p>
<div class="form-grid"><div class="field"><label for="nights">Lodging nights</label><input id="nights" type="number" min="0" step="1" value="3"></div><div class="field"><label for="lodgingLimit">Lodging limit per night</label><input id="lodgingLimit" type="number" min="0" step="any" value="180"></div><div class="field"><label for="actualLodging">Actual lodging total</label><input id="actualLodging" type="number" min="0" step="any" value="570"></div><div class="field"><label for="fullDays">Full M&IE days</label><input id="fullDays" type="number" min="0" step="1" value="2"></div><div class="field"><label for="partialDays">Partial travel days</label><input id="partialDays" type="number" min="0" step="1" value="2"></div><div class="field"><label for="mealLimit">Full-day meal/incidental limit</label><input id="mealLimit" type="number" min="0" step="any" value="80"></div><div class="field"><label for="partialFactor">Partial-day factor (%)</label><input id="partialFactor" type="number" min="0" max="100" step="any" value="75"></div><div class="field"><label for="actualMeals">Actual/reimbursable meal total</label><input id="actualMeals" type="number" min="0" step="any" value="250"></div><div class="field"><label for="currency">Currency symbol</label><input id="currency" type="text" maxlength="6" value="$"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Check limits</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Lodging allowance</span><strong id="lodgingAllow">—</strong></div><div class="metric"><span>M&IE allowance</span><strong id="mealAllow">—</strong></div><div class="metric"><span>Total allowance</span><strong id="totalAllow">—</strong></div><div class="metric"><span>Amount above limits</span><strong id="excess">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value);function go(){const vals=['nights','lodgingLimit','actualLodging','fullDays','partialDays','mealLimit','partialFactor','actualMeals'].map(n);if(vals.some(x=>!Number.isFinite(x)||x<0)||vals[6]>100){$('note').textContent='Enter non-negative values; the partial-day factor must be 0–100%.';$('note').className='helper danger';return;}const [ni,ll,al,fd,pd,ml,pf,am]=vals,s=$('currency').value||'',la=ni*ll,ma=fd*ml+pd*ml*pf/100,total=la+ma,actual=al+am,ex=Math.max(0,actual-total);$('lodgingAllow').textContent=s+la.toFixed(2);$('mealAllow').textContent=s+ma.toFixed(2);$('totalAllow').textContent=s+total.toFixed(2);$('excess').textContent=s+ex.toFixed(2);$('note').textContent='This is a comparison tool. Enter the official rate, partial-day rule, tax treatment and eligible expense basis from the policy that actually governs the trip.';$('note').className='helper'+(ex>0?' danger':'');}
['nights','lodgingLimit','actualLodging','fullDays','partialDays','mealLimit','partialFactor','actualMeals','currency'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('nights').value=3;$('lodgingLimit').value=180;$('actualLodging').value=570;$('fullDays').value=2;$('partialDays').value=2;$('mealLimit').value=80;$('partialFactor').value=75;$('actualMeals').value=250;$('currency').value='$';go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the per-diem compliance calculator works</h2><p>Lodging allowance equals eligible nights multiplied by the lodging limit. Meal and incidental allowance equals full days at the full rate plus partial travel days at the percentage you enter.</p>
<h2>Why the rates are editable</h2><p>Per-diem rates and travel rules vary by government, donor, employer, destination and date. A fixed global table would quickly become inaccurate. Enter the rate and partial-day rule from the policy or award that governs your trip.</p>
<h2>Actual cost versus reimbursable cost</h2><p>Some policies reimburse actual cost up to a ceiling; others pay a fixed allowance. Taxes, conference lodging exceptions, provided meals and incidentals can also be treated differently. Use the “actual” fields only on the basis relevant to your policy.</p>
<h2>Compliance limitation</h2><p>This tool compares arithmetic totals and does not decide legal or grant allowability. Keep receipts, approvals and travel documentation required by the applicable rules.</p>
<h2>Separate arithmetic from travel-policy compliance</h2><p>Per diem rules can vary by funding source, destination, travel day, meal provision, lodging documentation and employee/contractor status. The calculator compares claimed amounts with the limits and partial-day factor you enter, but it does not determine which official rate applies. Keep the rate table or policy version with the expense record, note any provided meals or exceptions, and use the governing organization's rounding and currency rules for reimbursement approval.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does this tool contain official government per-diem rates?','No. Rates vary by jurisdiction, destination and date, so you enter the rate that applies to your trip.'],['What is the partial-day factor?','It is the percentage of the full meal/incidental allowance permitted for a partial travel day under the policy you are following.'],['Does being under the limit guarantee an expense is allowable?','No. Eligibility can also depend on purpose, approvals, receipts, taxes, provided meals and other policy conditions.'],['Can I use this for a donor-funded project?','Yes for arithmetic comparison, provided you enter the donor-approved rates and rules. The tool itself does not determine grant compliance.']];
require __DIR__.'/../includes/tool-template.php';
