<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('government-ngos','program-budget-burn-rate-calculator');
ob_start();
?>
<h2>Calculate program budget burn rate</h2><p class="lead">Compare financial burn with schedule progress and estimate end-of-period spend if the current pace continues.</p>
<div class="form-grid"><div class="field"><label for="budget">Approved budget</label><input id="budget" type="number" min="0" step="any" value="500000"></div><div class="field"><label for="spent">Spent to date</label><input id="spent" type="number" min="0" step="any" value="220000"></div><div class="field"><label for="start">Program start date</label><input id="start" type="date" value="2026-01-01"></div><div class="field"><label for="end">Program end date</label><input id="end" type="date" value="2026-12-31"></div><div class="field"><label for="asof">As-of date</label><input id="asof" type="date" value="2026-06-30"></div><div class="field"><label for="currency">Currency symbol</label><input id="currency" type="text" maxlength="6" value="$"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate burn rate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Budget burned</span><strong id="burn">—</strong></div><div class="metric"><span>Time elapsed</span><strong id="time">—</strong></div><div class="metric"><span>Burn vs time variance</span><strong id="variance">—</strong></div><div class="metric"><span>Projected period spend</span><strong id="forecast">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value),day=86400000;function d(id){const x=new Date($(id).value+'T00:00:00Z');return x.getTime()}function go(){const b=n('budget'),s=n('spent'),st=d('start'),en=d('end'),as=d('asof'),c=$('currency').value||'';if(!Number.isFinite(b)||b<=0||!Number.isFinite(s)||s<0||![st,en,as].every(Number.isFinite)||en<=st||as<st||as>en){$('note').textContent='Enter a positive budget and valid dates with the as-of date inside the program period.';$('note').className='helper danger';return;}const burn=s/b*100,elapsed=(as-st)/(en-st)*100,variance=burn-elapsed,forecast=elapsed>0?s/(elapsed/100):0;$('burn').textContent=burn.toFixed(1)+'%';$('time').textContent=elapsed.toFixed(1)+'%';$('variance').textContent=(variance>=0?'+':'')+variance.toFixed(1)+' pts';$('forecast').textContent=c+forecast.toFixed(2);$('note').textContent='Straight-line forecasting assumes the current average spending pace continues. Real programs often have front-loaded procurement, seasonal activity or milestone-based payments.';$('note').className='helper'+(forecast>b?' danger':'');}
['budget','spent','start','end','asof','currency'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('budget').value=500000;$('spent').value=220000;$('start').value='2026-01-01';$('end').value='2026-12-31';$('asof').value='2026-06-30';$('currency').value='$';go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>What budget burn rate measures</h2><p>Budget burn is cumulative spend divided by the approved budget. Comparing that percentage with the percentage of program time elapsed is a quick way to identify whether spending is running ahead of or behind a simple linear schedule.</p>
<h2>Burn-rate variance</h2><p>The variance shown is budget-burn percentage minus time-elapsed percentage. A positive value means spending has progressed faster than calendar time; a negative value means it has progressed more slowly.</p>
<h2>How the spend forecast works</h2><p>The forecast extrapolates average spend to date across the full project period. It is intentionally simple and should be replaced with a detailed monthly forecast when procurement, payroll, subawards or milestone payments are uneven.</p>
<h2>Budget status is not performance status</h2><p>Underspending can indicate efficiency, delayed implementation or under-delivery. Overspending can reflect accelerated activity or a cost problem. Interpret finance alongside workplan progress and commitments.</p>
<h2>Interpret burn rate alongside delivery progress</h2><p>Spending 50% of the budget halfway through a grant is not automatically healthy or unhealthy. Some programs front-load equipment and startup costs; others spend later when field activities accelerate. Compare financial burn with milestone completion, commitments already placed, restricted budget lines and the remaining implementation calendar. A forecast that includes committed-but-not-yet-paid costs is usually more decision-useful than a simple historical spend percentage.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is program budget burn rate?','Cumulative spend divided by the approved program budget, expressed as a percentage.'],['What does positive burn-rate variance mean?','It means the percentage of budget spent is higher than the percentage of program time elapsed.'],['How is projected period spend calculated?','The tool divides spend-to-date by the fraction of program time elapsed, assuming the same average pace continues.'],['Is straight-line burn appropriate for every program?','No. Programs with seasonal work, procurement or milestone payments should use a more detailed cash-flow forecast.']];
require __DIR__.'/../includes/tool-template.php';
