<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('government-ngos','public-meeting-notice-date-calculator');
ob_start();
?>
<h2>Estimate a public meeting notice deadline</h2><p class="lead">Work backward from the meeting time using the notice period and counting method required by your rule or policy.</p>
<div class="form-grid"><div class="field"><label for="meeting">Meeting date and time</label><input id="meeting" type="datetime-local" value="2026-10-15T18:00"></div><div class="field"><label for="lead">Required notice period</label><input id="lead" type="number" min="0" step="1" value="3"></div><div class="field"><label for="unit">Counting method</label><select id="unit"><option value="calendar">Calendar days</option><option value="business" selected>Business days</option><option value="hours">Hours</option></select></div><div class="field full"><label for="holidays">Excluded holidays for business-day mode</label><textarea id="holidays" placeholder="YYYY-MM-DD, one per line"></textarea></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate latest notice time</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated latest posting</span><strong id="deadline">—</strong></div><div class="metric"><span>Counting method</span><strong id="method">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);function iso(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),da=String(d.getDate()).padStart(2,'0'),h=String(d.getHours()).padStart(2,'0'),mi=String(d.getMinutes()).padStart(2,'0');return `${y}-${m}-${da} ${h}:${mi}`}function ymd(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function go(){const mt=new Date($('meeting').value),lead=parseInt($('lead').value,10),unit=$('unit').value;if(!Number.isFinite(mt.getTime())||!Number.isInteger(lead)||lead<0){$('note').textContent='Enter a valid meeting time and non-negative whole notice period.';$('note').className='helper danger';return;}let d=new Date(mt),hol=new Set($('holidays').value.split(/\s+/).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)));if(unit==='hours')d=new Date(d.getTime()-lead*3600000);else if(unit==='calendar')d.setDate(d.getDate()-lead);else{let c=0;while(c<lead){d.setDate(d.getDate()-1);const wd=d.getDay();if(wd!==0&&wd!==6&&!hol.has(ymd(d)))c++;}}$('deadline').textContent=iso(d);$('method').textContent=unit==='hours'?'hours':unit+' days';$('note').textContent='Public-notice laws differ on whether the meeting day counts, how weekends/holidays are treated, posting location, emergency exceptions and exact-hour rules. Verify the governing statute, regulation or local policy before relying on this date.';$('note').className='helper';}
['meeting','lead','unit','holidays'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('meeting').value='2026-10-15T18:00';$('lead').value=3;$('unit').value='business';$('holidays').value='';go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>What the public meeting notice calculator does</h2><p>The tool performs date arithmetic based entirely on the notice period and counting method you enter. It can subtract hours, calendar days, or Monday-through-Friday business days with a custom holiday list.</p>
<h2>Why the legal rule is not hard-coded</h2><p>Open-meeting and public-notice requirements vary widely by jurisdiction and meeting type. Some rules count full calendar days; others specify hours, business days, posting locations, websites or special emergency procedures.</p>
<h2>Verify the counting convention</h2><p>Whether the meeting day or posting day is included can change a legal deadline. This calculator uses a simple “work backward by the entered interval” convention and therefore should be checked against the exact wording that governs your organization.</p>
<h2>Keep evidence of posting</h2><p>Where required, retain the notice, timestamp, posting location and any publication or website record. Calculating a deadline is only one part of compliance.</p>
<h2>Verify the legal counting convention before publishing</h2><p>Public-notice laws can define “days,” “hours,” weekends, holidays, emergency meetings and posting locations differently by jurisdiction. Some rules count backward from the meeting time; others impose a minimum continuous posting period. Use the calculator only after entering the governing interval and calendar assumptions, then verify the result against the current statute, regulation, policy or counsel guidance that applies to the specific public body.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does this calculator know my local open-meeting law?','No. You enter the required notice period and counting method. Local statutes and policies must be verified separately.'],['Can it exclude weekends and holidays?','Yes. Business-day mode skips Saturday, Sunday and the holiday dates you enter.'],['Can I calculate a 48-hour notice rule?','Yes. Choose hours and enter 48.'],['Is the calculated date legal advice?','No. It is date arithmetic only. Exact counting, posting and exception rules depend on the governing law or policy.']];
require __DIR__.'/../includes/tool-template.php';
