<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('hospitality','cloud-kitchen-delivery-commission-calculator');ob_start(); ?>
<h2>Model delivery-platform order economics</h2>
<p class="lead">Enter order value, food and packaging cost, plus the platform commission and any fixed fee.</p>
<div class="form-grid"><div class="field"><label for="order">Average order value</label><input id="order" type="number" value="600" step="0.01" min="0"></div><div class="field"><label for="food">Food cost per order</label><input id="food" type="number" value="180" step="0.01" min="0"></div><div class="field"><label for="pack">Packaging cost per order</label><input id="pack" type="number" value="35" step="0.01" min="0"></div><div class="field"><label for="commission">Platform commission (%)</label><input id="commission" type="number" value="25" step="0.01" min="0" max="100"></div><div class="field"><label for="fixed">Other platform fee per order</label><input id="fixed" type="number" value="10" step="0.01" min="0"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Platform fees</span><strong id="platform">—</strong></div><div class="metric"><span>Revenue after platform fees</span><strong id="netRevenue">—</strong></div><div class="metric"><span>Contribution per order</span><strong id="contribution">—</strong></div><div class="metric"><span>Contribution margin</span><strong id="margin">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const o=num('order'),f=num('food'),p=num('pack'),r=num('commission')/100,x=num('fixed');if([o,f,p,x].some(v=>v<0)||r<0||r>1){note('Use non-negative amounts and a commission between 0% and 100%.',true);return;}const fee=o*r+x,net=o-fee,con=o-fee-f-p;$('platform').textContent=money(fee,'');$('netRevenue').textContent=money(net,'');$('contribution').textContent=money(con,'');$('margin').textContent=o>0?pct(con/o*100):'—';note(con<0?'The modeled order has negative contribution before other overhead.':'Compare contribution across platforms, menu items or promotional prices.',con<0);}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Platform fees = order value × commission rate + fixed per-order fee. Contribution per order = order value − platform fees − food cost − packaging cost. Contribution margin divides that contribution by order value.</p><h2>How to use the result</h2><p>Use this to test delivery-only menu pricing, channel mix or promotional discounts. A strong menu gross margin can shrink materially after aggregator commissions and packaging costs.</p><h2>Assumptions and limitations</h2><p>Real settlements may include GST on commissions, payment charges, ads, discounts funded by the restaurant, delivery subsidies, refunds and other adjustments. Add relevant per-order costs where possible or reconcile against actual settlement statements.</p><h2>Example</h2><p>Modeling several order values can show whether minimum-order thresholds or bundles improve contribution by spreading fixed fees and packaging cost.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Does this include delivery-platform taxes and ad spend?','Not automatically. Add fixed per-order costs when appropriate and separately account for percentage charges not represented by commission.'],['What is contribution per order?','It is the order revenue remaining after the entered platform fee, food cost and packaging cost.'],['Should I use menu price before or after customer discount?','Use the revenue amount the kitchen economically receives for the order before subtracting the fees modeled here.'],['Can I compare two aggregators?','Yes. Run the same order economics with each platform\'s actual commission and fees.']];require __DIR__.'/../includes/tool-template.php';
