<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('hospitality','room-rate-breakeven-calculator');ob_start(); ?>
<h2>Estimate a break-even room rate</h2>
<p class="lead">Enter available inventory, occupancy, fixed cost and variable cost per occupied room for the period.</p>
<div class="form-grid"><div class="field"><label for="rooms">Rooms available per day</label><input id="rooms" type="number" value="100" step="1" min="1"></div><div class="field"><label for="days">Days in period</label><input id="days" type="number" value="30" step="1" min="1"></div><div class="field"><label for="occupancy">Expected occupancy (%)</label><input id="occupancy" type="number" value="70" step="0.01" min="0.01" max="100"></div><div class="field"><label for="fixed">Fixed costs for period</label><input id="fixed" type="number" value="1200000" step="0.01" min="0"></div><div class="field"><label for="variable">Variable cost per occupied room</label><input id="variable" type="number" value="500" step="0.01" min="0"></div><div class="field"><label for="profit">Target operating surplus</label><input id="profit" type="number" value="0" step="0.01"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Expected occupied room nights</span><strong id="occupied">—</strong></div><div class="metric"><span>Fixed cost per occupied room</span><strong id="fixedPer">—</strong></div><div class="metric"><span>Required average room revenue</span><strong id="rate">—</strong></div><div class="metric"><span>Required room revenue</span><strong id="periodRevenue">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const r=num('rooms'),d=num('days'),o=num('occupancy')/100,f=num('fixed'),v=num('variable'),p=num('profit');if(r<=0||d<=0||o<=0||o>1||f<0||v<0){note('Check rooms, days, occupancy and cost inputs.',true);return;}const occ=r*d*o,fp=(f+p)/occ,rate=v+fp;$('occupied').textContent=dec(occ,1);$('fixedPer').textContent=money(fp,'');$('rate').textContent=money(rate,'');$('periodRevenue').textContent=money(rate*occ,'');note('This is a simplified room-revenue break-even model and excludes non-room revenue unless you offset costs accordingly.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Expected occupied room nights = rooms × days × occupancy. Required average room revenue per occupied night = variable cost per occupied room + (fixed cost + target surplus) ÷ expected occupied room nights.</p><h2>How to use the result</h2><p>Use the result to understand how occupancy assumptions affect the rate needed to recover costs. Lower occupancy spreads the same fixed cost across fewer sold nights, increasing the required average rate.</p><h2>Assumptions and limitations</h2><p>This simplified model attributes all entered fixed cost to room revenue and does not net off food, events, spa or other departmental contribution. It also ignores taxes and channel acquisition costs unless included in variable or fixed costs.</p><h2>Example</h2><p>Scenario testing at 50%, 70% and 90% occupancy can show how strongly fixed-cost recovery depends on volume.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Is this the same as ADR?','No. It estimates the average room revenue needed under your assumptions; actual ADR is the achieved rate on rooms sold.'],['Should OTA commission be in variable cost?','If commission varies with occupied/booked rooms, include an appropriate expected amount or model it separately.'],['Can I add a target profit?','Yes. The target operating surplus is added to fixed costs before calculating the required rate.'],['Does other hotel revenue reduce the required room rate?','It can economically, but this simplified model does not include non-room contribution unless you adjust the cost target yourself.']];require __DIR__.'/../includes/tool-template.php';
