<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('manufacturing','oee-calculator');
ob_start();
?>
<h2>Calculate Overall Equipment Effectiveness (OEE)</h2><p class="lead">Break OEE into availability, performance and quality so the loss category is visible.</p>
<div class="form-grid"><div class="field"><label for="planned">Planned production time (minutes)</label><input id="planned" type="number" min="0.0001" step="any" value="480"></div><div class="field"><label for="down">Stop/downtime within planned time (minutes)</label><input id="down" type="number" min="0" step="any" value="60"></div><div class="field"><label for="ideal">Ideal cycle time (seconds/unit)</label><input id="ideal" type="number" min="0.0001" step="any" value="30"></div><div class="field"><label for="total">Total units</label><input id="total" type="number" min="0" step="any" value="720"></div><div class="field"><label for="good">Good units</label><input id="good" type="number" min="0" step="any" value="690"></div></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Availability</span><strong id="a">—</strong></div><div class="metric"><span>Performance</span><strong id="p">—</strong></div><div class="metric"><span>Quality</span><strong id="q">—</strong></div><div class="metric"><span>OEE</span><strong id="oee">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);function go(){const pt=+$('planned').value,d=+$('down').value,i=+$('ideal').value,t=+$('total').value,g=+$('good').value;if(!(pt>0&&d>=0&&d<=pt&&i>0&&t>=0&&g>=0&&g<=t)){['a','p','q','oee'].forEach(id=>$(id).textContent='—');$('note').textContent='Check that downtime ≤ planned time and good units ≤ total units.';$('note').className='helper danger';return}const run=pt-d,A=run/pt,P=run>0?(i*t)/(run*60):0,Q=t>0?g/t:0,O=A*P*Q;$('a').textContent=(A*100).toFixed(2)+'%';$('p').textContent=(P*100).toFixed(2)+'%';$('q').textContent=(Q*100).toFixed(2)+'%';$('oee').textContent=(O*100).toFixed(2)+'%';$('note').textContent=P>1?'Performance exceeds 100%. Verify ideal cycle time, units and runtime; an ideal cycle that is too slow commonly causes this.':'OEE = Availability × Performance × Quality. Use consistent Planned Production Time and ideal-cycle definitions.';$('note').className='helper'+(P>1?' danger':'')}['planned','down','ideal','total','good'].forEach(id=>$(id).addEventListener('input',go));go()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>OEE formula</h2><p>Overall Equipment Effectiveness is commonly calculated as <strong>Availability × Performance × Quality</strong>. Availability is runtime divided by planned production time. Performance compares ideal-cycle output with runtime. Quality is good count divided by total count.</p>
<h2>Loss categories behind OEE</h2><p>The three factors help separate time lost to stops, speed/small-stop losses and quality losses. OEE can also simplify algebraically to good count × ideal cycle time ÷ planned production time when definitions are consistent, but retaining the three components makes diagnosis easier.</p>
<h2>Why performance can exceed 100%</h2><p>Performance above 100% usually means the “ideal” cycle time is not truly the fastest sustainable design/reference cycle for that product, the unit count is inconsistent, or runtime boundaries differ. Do not simply cap the value and hide the data-quality issue.</p>
<h2>Avoid universal OEE targets</h2><p>Benchmarks such as 85% are widely cited for some discrete-manufacturing contexts, but there is no universal ideal number for every process. Product mix, asset type and business constraints differ. Use consistent internal loss definitions and improve the loss categories that matter.</p>
<h2>Make OEE loss data actionable</h2><p>OEE becomes more useful when every stop, speed loss and quality loss is coded consistently enough to build a Pareto of causes. Report the three factors with OEE so a plant can see whether a change came from availability, rate or quality. Comparing lines with different products is meaningful only when ideal-cycle standards and planned-time rules are equally rigorous; otherwise the benchmark can reward looser standards.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How is OEE calculated?','OEE is Availability × Performance × Quality, with all three factors expressed as decimal ratios before multiplication.'],['What is Planned Production Time?','It is the time your OEE system considers the equipment intended to produce, after whatever planned exclusions your organization formally applies.'],['Can OEE be over 100%?','A correctly defined OEE should not exceed 100%. Performance over 100% is a signal to verify ideal cycle time and data boundaries.'],['Is 85% OEE always world class?','It is a commonly cited reference in some contexts, not a universal standard or target for every process.']];
require __DIR__.'/../includes/tool-template.php';
