<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('manufacturing','production-capacity-calculator');
ob_start();
?>
<h2>Calculate production capacity</h2><p class="lead">Estimate gross theoretical output and expected good output over a selected operating period.</p>
<div class="form-grid"><div class="field"><label for="machines">Machines / parallel resources</label><input id="machines" type="number" min="1" step="1" value="4"></div><div class="field"><label for="hours">Hours per shift</label><input id="hours" type="number" min="0" step="any" value="8"></div><div class="field"><label for="shifts">Shifts per day</label><input id="shifts" type="number" min="0" step="any" value="2"></div><div class="field"><label for="days">Operating days in period</label><input id="days" type="number" min="0" step="any" value="22"></div><div class="field"><label for="rate">Rated output per machine-hour</label><input id="rate" type="number" min="0" step="any" value="50"></div><div class="field"><label for="eff">Expected run/efficiency factor (%)</label><input id="eff" type="number" min="0" max="100" step="any" value="85"></div><div class="field"><label for="yield">Good yield (%)</label><input id="yield" type="number" min="0" max="100" step="any" value="97"></div></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Scheduled resource-hours</span><strong id="rh">—</strong></div><div class="metric"><span>Rated gross capacity</span><strong id="gross">—</strong></div><div class="metric"><span>Adjusted gross output</span><strong id="adjusted">—</strong></div><div class="metric"><span>Expected good output</span><strong id="good">—</strong></div></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);function go(){const m=+$('machines').value,h=+$('hours').value,s=+$('shifts').value,d=+$('days').value,r=+$('rate').value,e=+$('eff').value/100,y=+$('yield').value/100;if(!(m>0&&h>=0&&s>=0&&d>=0&&r>=0&&e>=0&&e<=1&&y>=0&&y<=1)){['rh','gross','adjusted','good'].forEach(id=>$(id).textContent='—');return}const rh=m*h*s*d,g=rh*r,a=g*e,good=a*y;$('rh').textContent=rh.toLocaleString(undefined,{maximumFractionDigits:2})+' h';$('gross').textContent=g.toLocaleString(undefined,{maximumFractionDigits:0});$('adjusted').textContent=a.toLocaleString(undefined,{maximumFractionDigits:0});$('good').textContent=good.toLocaleString(undefined,{maximumFractionDigits:0})}['machines','hours','shifts','days','rate','eff','yield'].forEach(id=>$(id).addEventListener('input',go));go()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>Production capacity formula</h2><p>Rated gross capacity is <strong>parallel resources × hours/shift × shifts/day × operating days × rated units/hour</strong>. The calculator then applies an explicit run/efficiency factor and a good-yield percentage to show a planning estimate for good output.</p>
<h2>Rated capacity versus demonstrated capacity</h2><p>Nameplate or ideal rate may be higher than what a mixed product schedule can sustain. For planning, use a demonstrated rate or a realistic efficiency factor based on comparable production. If the resource is labor rather than a machine, verify staffing and skill constraints separately.</p>
<h2>Do not hide every loss in one factor</h2><p>A single efficiency percentage is convenient but can obscure downtime, speed loss, changeovers and scheduling loss. For improvement work, separate those causes using OEE, changeover tracking, quality yield and bottleneck analysis. For long-range rough-cut capacity, an empirically grounded aggregate factor may be appropriate.</p>
<h2>Capacity is constrained by the bottleneck</h2><p>Multiplying every machine's nominal rate is valid only when those machines truly operate in parallel producing the same output. In a serial process, end-to-end capacity is controlled by the constrained step and flow interactions, not the sum of every workstation's rate.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is production capacity?','It is the output a process or resource system can produce over a defined time under stated operating assumptions.'],['Should I use rated or actual units per hour?','Use the rate that matches your planning purpose. Demonstrated sustainable rates are generally more realistic for operational commitments.'],['Why is yield applied after the efficiency factor?','Efficiency adjusts gross production opportunity while yield converts produced units into expected good units. Keeping them separate makes assumptions visible.'],['Can I add capacities of serial machines?','Usually no. Serial-line throughput is limited by the bottleneck and flow constraints; this calculator is most direct for true parallel resources.']];
require __DIR__.'/../includes/tool-template.php';
