<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('manufacturing','throughput-calculator');
ob_start();
?>
<h2>Calculate production throughput</h2><p class="lead">Measure finished output per unit of productive time and compare it with a target rate.</p><div class="notice">Use completed good units and the actual productive time window. Do not mix scheduled hours with runtime unless that is the definition you intend to track.</div><div class="form-grid"><div class="field"><label for="units">Good units completed</label><input id="units" type="number" value="1200" min="0" step="any"></div><div class="field"><label for="time">Productive time</label><input id="time" type="number" value="8" min="0.0001" step="any"></div><div class="field"><label for="unit">Time unit</label><select id="unit"><option value="hour" selected>hours</option><option value="minute">minutes</option><option value="day">days</option></select></div><div class="field"><label for="target">Target throughput per same time unit</label><input id="target" type="number" value="140" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Throughput rate</span><strong id="rate">—</strong></div><div class="metric"><span>Equivalent per hour</span><strong id="perhour">—</strong></div><div class="metric"><span>Gap to target</span><strong id="gap">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('rate').textContent='—';$('perhour').textContent='—';$('gap').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const u=num('units'),t=num('time'),target=num('target'),unit=$('unit').value;if(!(u>=0&&t>0&&target>=0))throw 0;const rate=u/t;const factor=unit==='minute'?60:unit==='day'?1/24:1;const ph=rate*factor;const gap=rate-target;$('rate').textContent=fmt(rate,2)+' units/'+unit;$('perhour').textContent=fmt(ph,2)+' units/hour';$('gap').textContent=(gap>=0?'+':'')+fmt(gap,2)+' units/'+unit;$('note').textContent='Throughput uses good completed output divided by the productive time window. Keep the time boundary consistent when comparing shifts or lines.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Throughput Calculator works</h2><p>Throughput is the rate at which a process produces completed good output over a defined time window. This calculator uses throughput = good units completed ÷ productive time. It also normalizes the result to an hourly rate so teams can compare windows expressed in minutes, hours or days without changing the underlying production count.</p><h2>How to use this throughput calculator</h2><p>Enter the number of good units completed, the productive time represented by that count and the matching time unit. Add a target rate if you want a positive or negative gap. Use the same inclusion rules each time: for example, decide whether breaks, planned changeovers and blocked time belong inside or outside the productive-time denominator.</p><h2>How to interpret the result</h2><p>A higher rate means more good output is flowing through the measured process in the same amount of productive time. The target gap is useful for daily management because it shows the rate difference directly, but it does not explain the cause. Pair the result with downtime, quality, changeover and bottleneck data before deciding what to improve.</p><h2>Assumptions and limitations</h2><p>Throughput is definition-sensitive. Counting started units, total units including scrap, or shipments instead of completed good units produces different metrics. A short observation window can also exaggerate the effect of batch releases or temporary stoppages. This tool does not infer cycle time, WIP, OEE or capacity from throughput alone.</p><h2>Practical example and workflow</h2><p>If a line completes 1,200 good units in 8 productive hours, throughput is 150 units/hour. Against a 140-unit/hour target, the line is 10 units/hour above target. A supervisor can then check whether that improvement came from less downtime, a faster constraint operation or an unusual product mix.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the formula for manufacturing throughput?','Throughput is good completed output divided by the productive time used for the measurement.'],['Should scrap be included in throughput?','For a good-output throughput metric, exclude scrap. If your plant tracks gross throughput, label that definition separately and use it consistently.'],['Is throughput the same as cycle time?','No. Throughput is output per time period; cycle time is time per unit or operation. They are related only under specific stable-flow assumptions.'],['Why can throughput differ from production capacity?','Capacity is a potential or planned ceiling under stated assumptions, while throughput is an observed output rate for a real time window.']];
require __DIR__.'/../includes/tool-template.php';
