<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','brokerage-commission-calculator');
ob_start();
?>
<h2>Calculate property brokerage or commission</h2><p class="lead">Estimate total brokerage/commission, tax on the fee if applicable, and net proceeds before other closing costs.</p><div class="notice">This calculator does not assume a legally mandated or market-standard commission. Use the written brokerage agreement and applicable tax treatment.</div><div class="form-grid"><div class="field"><label for="price">Property transaction value</label><input id="price" type="number" value="5000000" min="0" step="any"></div><div class="field"><label for="rate">Commission rate (%)</label><input id="rate" type="number" value="2" min="0" step="any"></div><div class="field"><label for="tax">Tax on commission (%)</label><input id="tax" type="number" value="0" min="0" step="any"></div><div class="field"><label for="split">Your share of commission (%)</label><input id="split" type="number" value="100" min="0" max="100" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Gross commission</span><strong id="gross">—</strong></div><div class="metric"><span>Tax on commission</span><strong id="taxamt">—</strong></div><div class="metric"><span>Commission incl. tax</span><strong id="total">—</strong></div><div class="metric"><span>Your commission share</span><strong id="share">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('gross').textContent='—';$('taxamt').textContent='—';$('total').textContent='—';$('share').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const p=num('price'),r=num('rate'),tx=num('tax'),sp=num('split');if(!(p>=0&&r>=0&&tx>=0&&sp>=0&&sp<=100))throw 0;const g=p*r/100,t=g*tx/100,tot=g+t,share=g*sp/100;$('gross').textContent=fmt(g,2);$('taxamt').textContent=fmt(t,2);$('total').textContent=fmt(tot,2);$('share').textContent=fmt(share,2);$('note').textContent='Commission structures, taxes, minimum fees and who pays them are contractual and jurisdiction-specific. Enter the actual agreed rates.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Brokerage / Commission Calculator works</h2><p>The basic calculation is transaction value × commission rate. If a tax applies specifically to the brokerage fee, the calculator adds that amount separately. A broker/agent share can then be applied to the gross commission to estimate the portion retained before office splits, expenses or withholding.</p><h2>How to use this brokerage / commission calculator</h2><p>Enter the property sale/lease transaction value relevant to your agreement, the commission percentage, any tax rate charged on the commission itself and the share retained by the person or office you are modelling. Leave tax at zero when it does not apply or when you want to view only the pre-tax fee.</p><h2>How to interpret the result</h2><p>The output separates gross commission from tax so you can avoid treating tax collected from the client as brokerage revenue. The share field is useful when a listing side, cooperating broker, franchise or internal split applies, but it is only a mathematical split—not a determination of legal entitlement.</p><h2>Assumptions and limitations</h2><p>Real-estate commission is contractual and can be structured as flat fees, tiered rates, separate buyer/seller charges or lease-specific formulas. Taxes and invoicing rules vary by jurisdiction. This tool does not calculate stamp duty, transfer taxes, capital gains, closing charges, escrow, legal fees or financing costs.</p><h2>Practical example and workflow</h2><p>For a transaction value of 5,000,000 at 2%, gross commission is 100,000. If the broker retains 60% after a co-broker split, the share is 60,000 before internal expenses. Enter any commission tax separately so revenue and tax collected are not mixed.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Is real estate commission always a fixed percentage?','No. It is commonly negotiated and may be flat, tiered, split between parties or calculated differently for leases and sales.'],['Should tax be included in commission revenue?','Usually tax collected on the fee should be shown separately from brokerage revenue. Follow your invoicing and accounting rules.'],['What does commission share mean?','It is the percentage of gross commission allocated to the broker/agent or office you are modelling, before any other deductions.'],['Does this include closing costs or transfer taxes?','No. It estimates brokerage/commission only unless you separately model other transaction costs.']];
require __DIR__.'/../includes/tool-template.php';
