<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','cap-rate-calculator');
ob_start();
?>
<h2>Calculate real estate cap rate</h2><p class="lead">Calculate capitalization rate from annual NOI and property value, or estimate value from a target cap rate.</p><div class="notice">Cap rate is an unlevered income-to-value ratio. It is not the same as mortgage rate, cash-on-cash return or total investment return.</div><div class="form-grid"><div class="field"><label for="noi">Annual net operating income (NOI)</label><input id="noi" type="number" value="600000" min="0" step="any"></div><div class="field"><label for="value">Property value / price</label><input id="value" type="number" value="7500000" min="0.01" step="any"></div><div class="field"><label for="target">Target cap rate (%)</label><input id="target" type="number" value="8" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Cap rate</span><strong id="cap">—</strong></div><div class="metric"><span>Value at target cap rate</span><strong id="implied">—</strong></div><div class="metric"><span>NOI per month</span><strong id="monthly">—</strong></div><div class="metric"><span>Value / NOI multiple</span><strong id="multiple">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('cap').textContent='—';$('implied').textContent='—';$('monthly').textContent='—';$('multiple').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const noi=num('noi'),v=num('value'),t=num('target');if(!(noi>=0&&v>0&&t>0))throw 0;const cap=noi/v*100,iv=noi/(t/100);$('cap').textContent=fmt(cap,2)+'%';$('implied').textContent=fmt(iv,2);$('monthly').textContent=fmt(noi/12,2);$('multiple').textContent=noi>0?fmt(v/noi,2)+'×':'—';$('note').textContent='Cap rate uses NOI before financing. Ensure your NOI definition is consistent and excludes debt service, income tax and capital expenditures unless your analysis intentionally differs.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Cap Rate Calculator works</h2><p>Capitalization rate is commonly calculated as annual net operating income ÷ property value. NOI is property operating income after normal operating expenses but before financing costs such as mortgage principal and interest. The reverse relationship—NOI ÷ target cap rate—provides an implied value under that selected income yield.</p><h2>How to use this cap rate calculator</h2><p>Enter a stabilized annual NOI and the property value or purchase price you want to evaluate. If you also enter a target cap rate, the calculator shows the corresponding implied value. Keep rent, vacancy, other income and operating expenses on the same annual basis before calculating NOI.</p><h2>How to interpret the result</h2><p>Cap rate is an unlevered operating-income yield, useful for comparing properties or pricing assumptions. A lower cap rate corresponds to a higher value for the same NOI, while a higher cap rate corresponds to a lower value. It does not tell you the return on the investor’s cash after debt or tax.</p><h2>Assumptions and limitations</h2><p>NOI definitions must be consistent. Debt service, depreciation, income tax and investor-specific financing are normally outside NOI; capital reserves and management assumptions vary by analysis. Cap rates also reflect property type, location, lease risk, growth expectations and market conditions, so this calculator does not determine a “correct” market cap rate.</p><h2>Practical example and workflow</h2><p>If annual NOI is 600,000 and price is 7.5 million, the cap rate is 8%. At the same 600,000 NOI, a 7.5% target cap rate implies a value of 8 million. That sensitivity makes it easy to see how pricing moves when required income yield changes.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the cap rate formula?','Cap rate = annual net operating income divided by property value, multiplied by 100 for a percentage.'],['Does NOI include mortgage payments?','Normally no. Cap rate is intended to be unlevered, so debt service is excluded from NOI.'],['Is a higher cap rate always better?','No. A higher cap rate may reflect higher income yield but can also reflect greater risk, weaker growth expectations or a lower-quality asset/market.'],['Can cap rate be used to value a property?','You can estimate implied value as NOI divided by a selected market/target cap rate, but selecting the appropriate cap rate requires market evidence and judgment.']];
require __DIR__.'/../includes/tool-template.php';
