<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','cash-on-cash-return-calculator');
ob_start();
?>
<h2>Calculate cash-on-cash return</h2><p class="lead">Compare annual pre-tax property cash flow with the total cash invested in the deal.</p><div class="notice">Include all material cash contributed at acquisition, not only the down payment, when you want a realistic denominator.</div><div class="form-grid"><div class="field"><label for="cashflow">Annual pre-tax cash flow</label><input id="cashflow" type="number" value="240000" step="any"></div><div class="field"><label for="down">Down payment / equity invested</label><input id="down" type="number" value="1500000" min="0" step="any"></div><div class="field"><label for="closing">Cash closing costs</label><input id="closing" type="number" value="150000" min="0" step="any"></div><div class="field"><label for="rehab">Upfront rehab / setup cash</label><input id="rehab" type="number" value="100000" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Cash-on-cash return</span><strong id="coc">—</strong></div><div class="metric"><span>Total cash invested</span><strong id="invested">—</strong></div><div class="metric"><span>Average monthly cash flow</span><strong id="monthly">—</strong></div><div class="metric"><span>Simple cash payback</span><strong id="payback">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('coc').textContent='—';$('invested').textContent='—';$('monthly').textContent='—';$('payback').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const cf=num('cashflow'),d=num('down'),c=num('closing'),r=num('rehab');const inv=d+c+r;if(!(Number.isFinite(cf)&&d>=0&&c>=0&&r>=0&&inv>0))throw 0;const ret=cf/inv*100;$('coc').textContent=fmt(ret,2)+'%';$('invested').textContent=fmt(inv,2);$('monthly').textContent=fmt(cf/12,2);$('payback').textContent=cf>0?fmt(inv/cf,2)+' years':'Not positive';$('note').textContent='Cash-on-cash return is a simple pre-tax cash yield. It ignores appreciation, principal paydown, income tax and the time value of money.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Cash-on-Cash Return Calculator works</h2><p>Cash-on-cash return measures annual pre-tax cash flow relative to the actual cash invested by the investor. The calculator sums down payment, closing costs and upfront rehab/setup cash, then divides annual cash flow by that total. This makes it different from cap rate, which ignores the financing structure.</p><h2>How to use this cash-on-cash return calculator</h2><p>Enter the annual cash flow remaining after property operating expenses and debt service but before income tax, using the convention appropriate to your underwriting. Then enter all significant cash contributed at acquisition. If a lender finances renovation or closing costs, include only the cash portion paid by the investor.</p><h2>How to interpret the result</h2><p>A positive cash-on-cash percentage shows current-period cash yield on invested equity. The simple payback figure indicates how many years of identical cash flow would recover the initial cash contribution, but it should not be mistaken for an IRR or discounted payback because it ignores timing and future sale proceeds.</p><h2>Assumptions and limitations</h2><p>The metric excludes appreciation, loan principal reduction, refinance proceeds, depreciation tax effects and the changing value of money. It is highly sensitive to what is included in “cash flow” and “cash invested.” Compare deals only when those definitions are consistent and verify financing/expense assumptions independently.</p><h2>Practical example and workflow</h2><p>If annual pre-tax cash flow is 240,000 and total cash invested is 1.75 million after down payment, closing and rehab, cash-on-cash return is about 13.7%. An investor can compare that current cash yield with alternative financing structures while separately modelling long-term equity growth.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the cash-on-cash return formula?','Annual pre-tax cash flow divided by total cash invested, multiplied by 100.'],['Should closing costs be included in cash invested?','Yes when they are paid from the investor’s cash and are part of the upfront capital required for the deal.'],['Is cash-on-cash return the same as cap rate?','No. Cap rate uses NOI and property value before financing; cash-on-cash return uses post-debt-service cash flow and investor cash invested.'],['Does cash-on-cash return include appreciation?','No. It is a current cash-yield metric and does not include appreciation, sale proceeds or principal paydown.']];
require __DIR__.'/../includes/tool-template.php';
