<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','property-flip-profit-calculator');
ob_start();
?>
<h2>Estimate property flip profit</h2><p class="lead">Model sale proceeds, total project cost, profit, ROI and break-even sale price for a property flip.</p><div class="notice">Add contingency to rehab/holding costs if appropriate. Taxes, financing structure and transaction fees vary by jurisdiction and deal.</div><div class="form-grid"><div class="field"><label for="buy">Purchase price</label><input id="buy" type="number" value="3000000" min="0" step="any"></div><div class="field"><label for="rehab">Renovation / rehab</label><input id="rehab" type="number" value="500000" min="0" step="any"></div><div class="field"><label for="hold">Holding + financing costs</label><input id="hold" type="number" value="200000" min="0" step="any"></div><div class="field"><label for="buyclose">Purchase closing costs</label><input id="buyclose" type="number" value="120000" min="0" step="any"></div><div class="field"><label for="sale">Expected sale price</label><input id="sale" type="number" value="4300000" min="0" step="any"></div><div class="field"><label for="sellpct">Selling costs (% of sale)</label><input id="sellpct" type="number" value="5" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated profit</span><strong id="profit">—</strong></div><div class="metric"><span>ROI on project cost</span><strong id="roi">—</strong></div><div class="metric"><span>Total project cost</span><strong id="cost">—</strong></div><div class="metric"><span>Break-even sale price</span><strong id="breakeven">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('profit').textContent='—';$('roi').textContent='—';$('cost').textContent='—';$('breakeven').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const b=num('buy'),r=num('rehab'),h=num('hold'),bc=num('buyclose'),s=num('sale'),sp=num('sellpct');if(!(b>=0&&r>=0&&h>=0&&bc>=0&&s>=0&&sp>=0&&sp<100))throw 0;const base=b+r+h+bc,sell=s*sp/100,cost=base+sell,profit=s-cost,roi=base>0?profit/base*100:NaN,be=base/(1-sp/100);$('profit').textContent=fmt(profit,2);$('roi').textContent=Number.isFinite(roi)?fmt(roi,2)+'%':'—';$('cost').textContent=fmt(cost,2);$('breakeven').textContent=fmt(be,2);$('note').textContent='This is a project estimate before income/capital-gains tax and unexpected costs. Selling cost is modelled as a percentage of sale price.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Property Flip Profit Calculator works</h2><p>The flip model adds purchase price, rehab, holding/financing and purchase closing costs to form the project cost before sale. Selling costs are calculated as a percentage of sale price. Profit equals sale price minus all entered project and selling costs. Break-even sale price solves for the sale price that covers the fixed project costs plus percentage selling cost.</p><h2>How to use this property flip profit calculator</h2><p>Enter realistic acquisition and renovation budgets, carrying costs for the expected project duration, purchase closing costs, projected resale price and percentage selling cost. Keep the same tax basis/currency throughout. If a cost is uncertain, use conservative values or run multiple scenarios instead of entering a single optimistic number.</p><h2>How to interpret the result</h2><p>Profit shows estimated dollars remaining before investor tax. ROI compares profit with the fixed project cost before percentage selling expense, providing a simple project-yield view. Break-even sale price is useful because it tells you how much downside exists between your expected exit price and the price at which the project stops making a pre-tax profit.</p><h2>Assumptions and limitations</h2><p>The calculation does not estimate capital gains/income tax, lender points, construction delays, financing draws, opportunity cost, market-price uncertainty or detailed cash timing. Percentage selling cost is a simplification. A full underwriting model should schedule cash flows by date and stress resale price, timeline and rehab overruns.</p><h2>Practical example and workflow</h2><p>If acquisition plus rehab, carrying and purchase closing costs total 3.82 million and selling costs are 5%, the break-even sale price is about 4.02 million. An expected 4.3 million exit therefore has limited price cushion, which may be more decision-useful than looking only at headline gross profit.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What costs should I include in a house flip?','Include purchase, renovation, financing/holding, purchase closing and expected selling costs, plus contingency where appropriate.'],['How is break-even sale price calculated?','The calculator solves sale price × (1 − selling-cost rate) = fixed project costs.'],['Does the profit include tax?','No. Income/capital-gains tax and jurisdiction-specific charges are not estimated.'],['Why is ROI different from profit margin on sale price?','ROI compares profit with capital/project cost, while profit margin would compare profit with sale revenue. They answer different questions.']];
require __DIR__.'/../includes/tool-template.php';
