<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','property-dscr-calculator');
ob_start();
?>
<h2>Calculate property DSCR</h2><p class="lead">Calculate debt service coverage ratio from net operating income and annual debt service.</p><div class="notice">Use the lender’s NOI and debt-service definitions for underwriting. This calculator does not determine loan eligibility.</div><div class="form-grid"><div class="field"><label for="noi">Annual net operating income (NOI)</label><input id="noi" type="number" value="900000" min="0" step="any"></div><div class="field"><label for="debt">Annual debt service</label><input id="debt" type="number" value="650000" min="0.01" step="any"></div><div class="field"><label for="target">Target DSCR</label><input id="target" type="number" value="1.25" min="0.01" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>DSCR</span><strong id="dscr">—</strong></div><div class="metric"><span>NOI after debt service</span><strong id="surplus">—</strong></div><div class="metric"><span>NOI required at target</span><strong id="required">—</strong></div><div class="metric"><span>NOI headroom vs target</span><strong id="headroom">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('dscr').textContent='—';$('surplus').textContent='—';$('required').textContent='—';$('headroom').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const n=num('noi'),d=num('debt'),t=num('target');if(!(n>=0&&d>0&&t>0))throw 0;const ratio=n/d,req=d*t,head=n-req;$('dscr').textContent=fmt(ratio,3)+'×';$('surplus').textContent=fmt(n-d,2);$('required').textContent=fmt(req,2);$('headroom').textContent=(head>=0?'+':'')+fmt(head,2);$('note').textContent='Freddie Mac defines debt coverage as NOI divided by annual debt service. Lenders can apply their own NOI adjustments, reserves and minimum DSCR requirements.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Property DSCR Calculator works</h2><p>Debt Service Coverage Ratio compares property net operating income with annual debt service. Freddie Mac defines debt coverage as NOI divided by annual debt service for multifamily property. A ratio of 1.00 means NOI equals scheduled debt service; above 1.00 indicates an income cushion before other non-NOI items.</p><h2>How to use this property dscr calculator</h2><p>Enter the annual NOI using the lender or underwriting definition relevant to the property, then enter total annual principal and interest or other debt-service amount included by that definition. Add a target DSCR to see the NOI required to meet it and the current dollar headroom above or below that target.</p><h2>How to interpret the result</h2><p>DSCR is a coverage metric, not a profitability measure. For example, 1.25× means NOI is 125% of annual debt service under the entered assumptions. The dollar headroom result is often more intuitive for sensitivity analysis because it shows how much NOI could fall before the selected target is missed.</p><h2>Assumptions and limitations</h2><p>Lenders may normalize rents, vacancy, management fees, reserves, replacement costs or other NOI components differently. They may also include debt obligations beyond the simple mortgage payment. Minimum DSCR varies by program and risk. Therefore, do not use this tool as a loan-approval predictor or substitute for a lender term sheet.</p><h2>Practical example and workflow</h2><p>With 900,000 of annual NOI and 650,000 of debt service, DSCR is about 1.385×. Against a 1.25× target, required NOI is 812,500, leaving 87,500 of headroom. An underwriter can then stress rent or expense assumptions to see how quickly that cushion disappears.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the property DSCR formula?','DSCR = annual net operating income divided by annual debt service.'],['What does a DSCR of 1.25 mean?','It means NOI is 1.25 times annual debt service under the definitions used.'],['Does every lender calculate NOI the same way?','No. Lenders can make different vacancy, reserve, management and expense adjustments, so use the lender’s underwriting definition.'],['Is a higher DSCR always better?','Higher coverage generally means a larger income cushion relative to debt service, but it does not by itself measure asset quality, return or risk.']];
require __DIR__.'/../includes/tool-template.php';
