<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','prorated-rent-calculator');
ob_start();
?>
<h2>Calculate prorated rent</h2><p class="lead">Prorate monthly rent using actual calendar days or a 30-day convention.</p><div class="notice">Actual-days and 30-day conventions can produce different amounts. This tool makes the denominator explicit rather than assuming one method is legally correct.</div><div class="form-grid"><div class="field"><label for="rent">Monthly rent</label><input id="rent" type="number" value="30000" min="0" step="any"></div><div class="field"><label for="days">Chargeable occupancy days</label><input id="days" type="number" value="12" min="0" step="1"></div><div class="field"><label for="monthdays">Days in calendar month</label><input id="monthdays" type="number" value="30" min="28" max="31" step="1"></div><div class="field"><label for="method">Proration convention</label><select id="method"><option value="actual" selected>Actual days in month</option><option value="30">30-day month</option></select></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Daily rent rate</span><strong id="daily">—</strong></div><div class="metric"><span>Prorated rent</span><strong id="prorated">—</strong></div><div class="metric"><span>Share of month charged</span><strong id="pct">—</strong></div><div class="metric"><span>Uncharged monthly rent</span><strong id="remaining">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('daily').textContent='—';$('prorated').textContent='—';$('pct').textContent='—';$('remaining').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const r=num('rent'),d=num('days'),md=num('monthdays'),m=$('method').value;const den=m==='30'?30:md;if(!(r>=0&&d>=0&&den>0&&d<=den))throw 0;const daily=r/den,amt=daily*d;$('daily').textContent=fmt(daily,2);$('prorated').textContent=fmt(amt,2);$('pct').textContent=fmt(d/den*100,2)+'%';$('remaining').textContent=fmt(r-amt,2);$('note').textContent='Lease language and local law determine the permitted proration method. Use the convention stated in the agreement or required in your jurisdiction.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Prorated Rent Calculator works</h2><p>Prorated rent is monthly rent multiplied by the fraction of the rental period being charged. Under an actual-days convention, daily rent is monthly rent ÷ the number of calendar days in that month. Under a 30-day convention, the monthly amount is divided by 30 regardless of the month’s length.</p><h2>How to use this prorated rent calculator</h2><p>Enter the monthly rent, number of chargeable occupancy days, the calendar month length and the convention you need. Count days according to the lease—for example, whether move-in day is included and move-out day excluded—because the day-count rule can change the result even when the mathematical formula is the same.</p><h2>How to interpret the result</h2><p>The daily rate and percentage-of-month outputs make the proration auditable for tenants, landlords and property managers. If the chargeable days equal the denominator, prorated rent equals the full monthly rent. The remaining amount simply shows the portion of monthly rent not charged under the entered day count.</p><h2>Assumptions and limitations</h2><p>Proration practices are contractual and jurisdiction-specific. Some leases use daily annual rent, banker’s months or other methods. Local housing rules may limit how partial periods are billed. This calculator does not determine the legally correct method and does not add utilities, late fees, deposits or other charges.</p><h2>Practical example and workflow</h2><p>For 30,000 monthly rent and 12 chargeable days, an actual 31-day month produces a different charge than a 30-day convention. By showing the denominator and daily rate, the property manager can document exactly how the partial-month amount was obtained.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Should prorated rent use 30 days or actual days?','Use the method specified by the lease and applicable local rules. Both conventions exist and can produce different amounts.'],['Do I count the move-in day?','That depends on the lease/day-count convention. Decide which days are chargeable before entering the occupancy-day count.'],['Does this include security deposit or utilities?','No. It calculates base rent proration only.'],['Can the prorated amount exceed monthly rent?','Not with a valid day count that is no greater than the selected month denominator.']];
require __DIR__.'/../includes/tool-template.php';
