<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','rent-escalation-calculator');
ob_start();
?>
<h2>Project rent escalation</h2><p class="lead">Project future rent and cumulative rent from a starting monthly rent and annual escalation rate.</p><div class="notice">Escalation clauses may be fixed, stepped, indexed, capped or subject to law. Enter the contractual assumption you want to model.</div><div class="form-grid"><div class="field"><label for="rent">Starting monthly rent</label><input id="rent" type="number" value="30000" min="0" step="any"></div><div class="field"><label for="rate">Annual escalation (%)</label><input id="rate" type="number" value="5" step="any"></div><div class="field"><label for="years">Projection years</label><input id="years" type="number" value="5" min="1" max="50" step="1"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Monthly rent in final year</span><strong id="future">—</strong></div><div class="metric"><span>Annual rent in final year</span><strong id="annual">—</strong></div><div class="metric"><span>Cumulative rent over term</span><strong id="cumulative">—</strong></div><div class="metric"><span>Increase vs starting rent</span><strong id="increase">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('future').textContent='—';$('annual').textContent='—';$('cumulative').textContent='—';$('increase').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const r=num('rent'),g=num('rate')/100,y=Math.floor(num('years'));if(!(r>=0&&Number.isFinite(g)&&y>=1&&y<=50&&g>-1))throw 0;let cum=0,last=r;for(let i=0;i<y;i++){last=r*Math.pow(1+g,i);cum+=last*12}const final=r*Math.pow(1+g,y-1);$('future').textContent=fmt(final,2);$('annual').textContent=fmt(final*12,2);$('cumulative').textContent=fmt(cum,2);$('increase').textContent=r>0?fmt((final/r-1)*100,2)+'%':'—';$('note').textContent='This assumes one compounding rent increase at the start of each new rental year and no step changes, caps, incentives or index-linked clauses.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Rent Escalation Calculator works</h2><p>With a fixed annual percentage escalation, rent for year n is starting rent × (1 + escalation rate)^(n−1). The calculator sums twelve months of each projected annual rent to estimate cumulative rent over the selected term and shows the final-year monthly and annual amounts.</p><h2>How to use this rent escalation calculator</h2><p>Enter the current monthly rent, annual percentage increase and number of years. The tool assumes each increase occurs once at the start of a new rental year. Use a negative rate only when intentionally modelling a contractual reduction. For complex leases, model each step separately instead of forcing a single average rate.</p><h2>How to interpret the result</h2><p>The final-year increase shows how compounding changes rent over time. A 5% annual escalation is not a 25% increase after five annual steps in all contexts because each increase applies to the already increased amount. Cumulative rent is useful for lease budgeting and comparing fixed escalation with alternative proposals.</p><h2>Assumptions and limitations</h2><p>Real leases may use fixed dollar steps, CPI/index adjustments, caps/floors, rent-free periods, turnover rent or different review dates. Regulation can limit increases in some jurisdictions. This calculator does not determine enforceability or future inflation; it simply applies the entered fixed-rate scenario.</p><h2>Practical example and workflow</h2><p>Starting at 30,000 per month with 5% annual escalation, later years compound on earlier increases. A tenant can use cumulative rent to budget the lease term, while a landlord can compare the same cash-flow pattern with a stepped-rent proposal without confusing headline annual percentages with total cash paid.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does annual rent escalation compound?','Yes in this calculator. Each year’s percentage is applied to the prior year’s rent.'],['Does the first year increase immediately?','No. The starting rent applies to year one; the first escalation is applied for year two.'],['Can I use this for CPI-linked rent?','Only as a scenario if you enter an assumed fixed rate. Actual index-linked rent requires the contract’s specific index and adjustment rules.'],['Does this check local rent-control laws?','No. Legal limits and lease enforceability must be verified separately.']];
require __DIR__.'/../includes/tool-template.php';
