<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','rent-vs-buy-calculator');
ob_start();
?>
<h2>Compare estimated cost of renting vs buying</h2><p class="lead">Model a simplified multi-year housing cost comparison including financing, ownership costs, appreciation and rent growth.</p><div class="notice">Rent-vs-buy decisions depend heavily on assumptions. Change the horizon, appreciation, rent growth and ownership costs rather than treating one scenario as a forecast.</div><div class="form-grid"><div class="field"><label for="price">Home purchase price</label><input id="price" type="number" value="6000000" min="0.01" step="any"></div><div class="field"><label for="down">Down payment (%)</label><input id="down" type="number" value="20" min="0" max="100" step="any"></div><div class="field"><label for="rate">Mortgage annual rate (%)</label><input id="rate" type="number" value="8" min="0" step="any"></div><div class="field"><label for="term">Mortgage term (years)</label><input id="term" type="number" value="20" min="1" step="1"></div><div class="field"><label for="years">Comparison horizon (years)</label><input id="years" type="number" value="7" min="1" step="1"></div><div class="field"><label for="taxmaint">Annual property tax + maintenance (% of price)</label><input id="taxmaint" type="number" value="2" min="0" step="any"></div><div class="field"><label for="app">Annual home appreciation assumption (%)</label><input id="app" type="number" value="4" step="any"></div><div class="field"><label for="rent">Starting monthly rent</label><input id="rent" type="number" value="30000" min="0" step="any"></div><div class="field"><label for="rentg">Annual rent growth (%)</label><input id="rentg" type="number" value="5" step="any"></div><div class="field"><label for="sell">Selling cost at exit (% of value)</label><input id="sell" type="number" value="4" min="0" max="30" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated net ownership cost</span><strong id="buycost">—</strong></div><div class="metric"><span>Estimated rent paid</span><strong id="rentcost">—</strong></div><div class="metric"><span>Estimated equity at horizon</span><strong id="equity">—</strong></div><div class="metric"><span>Rent cost minus buy cost</span><strong id="difference">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('buycost').textContent='—';$('rentcost').textContent='—';$('equity').textContent='—';$('difference').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const P=num('price'),dp=num('down')/100,ar=num('rate')/100,term=Math.floor(num('term')),yrs=Math.floor(num('years')),om=num('taxmaint')/100,app=num('app')/100,r0=num('rent'),rg=num('rentg')/100,sc=num('sell')/100;if(!(P>0&&dp>=0&&dp<=1&&ar>=0&&term>0&&yrs>0&&om>=0&&app>-1&&r0>=0&&rg>-1&&sc>=0&&sc<1))throw 0;const loan=P*(1-dp),n=term*12,mr=ar/12,emi=loan===0?0:(mr===0?loan/n:loan*mr*Math.pow(1+mr,n)/(Math.pow(1+mr,n)-1));let bal=loan,interest=0,principal=0;const months=Math.min(yrs*12,n);for(let i=0;i<months;i++){const intr=bal*mr;const pr=Math.min(bal,emi-intr);interest+=intr;principal+=pr;bal-=pr}let own=P*dp+interest+P*om*yrs;const future=P*Math.pow(1+app,yrs),saleCost=future*sc,equity=future-saleCost-bal;const buyNet=own-equity;let rentTotal=0;for(let y=0;y<yrs;y++)rentTotal+=r0*Math.pow(1+rg,y)*12;$('buycost').textContent=fmt(buyNet,2);$('rentcost').textContent=fmt(rentTotal,2);$('equity').textContent=fmt(equity,2);$('difference').textContent=fmt(rentTotal-buyNet,2);$('note').textContent='Simplified scenario: down payment is treated as cash cost and exit equity as an offset. It excludes opportunity cost, purchase closing costs, tax benefits, insurance and transaction-specific fees.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Rent vs Buy Calculator works</h2><p>This scenario model estimates mortgage payment and amortization, adds a percentage allowance for annual property tax plus maintenance, projects home value using the entered appreciation rate and subtracts remaining loan balance plus selling cost to estimate exit equity. Renting is modelled as annual rent with the selected growth rate.</p><h2>How to use this rent vs buy calculator</h2><p>Enter the purchase price, down payment, loan rate/term, comparison horizon and ownership-cost allowance, then set the appreciation, rent and rent-growth assumptions. The output is intentionally labelled an estimate because small changes in appreciation, financing or holding period can materially change the comparison.</p><h2>How to interpret the result</h2><p>Estimated net ownership cost treats the down payment and mortgage interest/ownership costs as cash outflows and offsets them with projected equity at the end of the horizon. The rent side totals rent paid. The difference is useful for scenario exploration, but it is not an instruction to rent or buy because preferences, liquidity and risk are not captured.</p><h2>Assumptions and limitations</h2><p>The model excludes the investment return/opportunity cost on down payment, purchase closing costs, insurance unless included in your ownership percentage, property-tax changes, tax deductions, HOA fees, renovation, rent deposits, transaction taxes and market volatility. Appreciation and rent growth are assumptions, not forecasts. Local financing rules can also differ.</p><h2>Practical example and workflow</h2><p>A buyer can run the same home through a 3-year, 7-year and 12-year horizon, then stress appreciation from 0% to 5%. Seeing where the result changes is more informative than relying on one “break-even” answer, because the decision is often dominated by holding period and transaction costs.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does this calculator tell me whether I should buy or rent?','No. It compares an entered financial scenario and does not account for personal preferences, liquidity, risk tolerance or all local costs.'],['Does it include the opportunity cost of the down payment?','No. That is a major omission for some analyses; model it separately if relevant.'],['Is home appreciation guaranteed?','No. The appreciation rate is only a scenario assumption and can be negative or differ widely by market and period.'],['Why can the result change so much with holding period?','Buying has upfront/exit costs and mortgage amortization, while rent grows differently over time. A longer or shorter horizon changes how those effects accumulate.']];
require __DIR__.'/../includes/tool-template.php';
