<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','rental-yield-calculator');
ob_start();
?>
<h2>Calculate gross and net rental yield</h2><p class="lead">Compare annual rent with property value and operating costs to estimate gross and net rental yield.</p><div class="notice">Gross yield ignores vacancy and operating expenses. Net yield is more informative but still depends on what expenses are included and whether value means purchase price or current market value.</div><div class="form-grid"><div class="field"><label for="value">Property value / total acquisition cost</label><input id="value" type="number" value="6000000" min="0.01" step="any"></div><div class="field"><label for="rent">Monthly gross rent</label><input id="rent" type="number" value="45000" min="0" step="any"></div><div class="field"><label for="vac">Vacancy / credit loss (%)</label><input id="vac" type="number" value="5" min="0" max="100" step="any"></div><div class="field"><label for="expenses">Annual operating expenses</label><input id="expenses" type="number" value="120000" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Gross rental yield</span><strong id="gross">—</strong></div><div class="metric"><span>Net rental yield</span><strong id="net">—</strong></div><div class="metric"><span>Estimated annual NOI</span><strong id="noi">—</strong></div><div class="metric"><span>Effective annual rent</span><strong id="effective">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('gross').textContent='—';$('net').textContent='—';$('noi').textContent='—';$('effective').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const v=num('value'),r=num('rent'),vac=num('vac')/100,e=num('expenses');if(!(v>0&&r>=0&&vac>=0&&vac<=1&&e>=0))throw 0;const gross=r*12,eff=gross*(1-vac),noi=eff-e;$('gross').textContent=fmt(gross/v*100,2)+'%';$('net').textContent=fmt(noi/v*100,2)+'%';$('noi').textContent=fmt(noi,2);$('effective').textContent=fmt(eff,2);$('note').textContent='Net yield here uses entered vacancy and operating expenses before financing and investor tax. Define expenses consistently when comparing properties.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Rental Yield Calculator works</h2><p>Gross rental yield is annual scheduled rent ÷ property value. This tool also estimates effective rent after vacancy/credit loss, subtracts annual operating expenses to create a simplified NOI, and divides that NOI by property value for a net yield. Financing is intentionally excluded so the result describes the property rather than the investor’s loan.</p><h2>How to use this rental yield calculator</h2><p>Enter either acquisition cost or current property value—but use the same basis when comparing assets—then monthly gross rent, expected vacancy/credit loss and annual operating expenses. Expenses can include items such as management, maintenance, insurance and property tax if those belong in your chosen NOI definition.</p><h2>How to interpret the result</h2><p>Gross yield is easy to compare but can make a high-expense or high-vacancy asset look better than it is. Net yield makes operating drag visible. A negative NOI produces a negative net yield, which is a signal to inspect rent, vacancy and cost assumptions rather than forcing a positive percentage.</p><h2>Assumptions and limitations</h2><p>This is not cash-on-cash return because it does not include debt service or investor equity. It also does not include appreciation, sale proceeds, income tax or principal paydown. Expense definitions and current-vs-purchase value choices can materially change the ratio, so document them alongside the result.</p><h2>Practical example and workflow</h2><p>At 45,000 monthly rent, scheduled annual rent is 540,000. With 5% vacancy and 120,000 of operating expenses, estimated NOI is 393,000. Against a 6 million property value, net rental yield is about 6.55%, compared with a 9% gross yield.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is gross rental yield?','Annual gross rent divided by property value, expressed as a percentage.'],['How is net rental yield different?','Net yield reduces rent for vacancy/credit loss and subtracts operating expenses before dividing by property value.'],['Does rental yield include mortgage payments?','Not in this calculator. Financing is excluded; use cash-on-cash return or DSCR for financing-related analysis.'],['Should I use purchase price or current value?','Either can be useful, but use a consistent basis for the question you are answering and when comparing properties.']];
require __DIR__.'/../includes/tool-template.php';
