<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('real-estate','vacancy-impact-calculator');
ob_start();
?>
<h2>Estimate rental vacancy impact</h2><p class="lead">Calculate lost rent, effective rent and occupancy needed to reach a revenue target.</p><div class="notice">Keep physical occupancy and economic vacancy conceptually separate. A property can be physically occupied yet still lose revenue through concessions, delinquency or below-market rent.</div><div class="form-grid"><div class="field"><label for="units">Rental units</label><input id="units" type="number" value="20" min="1" step="1"></div><div class="field"><label for="rent">Average monthly rent per unit</label><input id="rent" type="number" value="25000" min="0" step="any"></div><div class="field"><label for="vac">Economic vacancy / credit loss (%)</label><input id="vac" type="number" value="8" min="0" max="100" step="any"></div><div class="field"><label for="target">Target annual rent revenue</label><input id="target" type="number" value="5520000" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Gross potential rent</span><strong id="potential">—</strong></div><div class="metric"><span>Revenue lost to vacancy</span><strong id="lost">—</strong></div><div class="metric"><span>Effective rent revenue</span><strong id="effective">—</strong></div><div class="metric"><span>Occupancy needed for target</span><strong id="needed">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('potential').textContent='—';$('lost').textContent='—';$('effective').textContent='—';$('needed').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const u=num('units'),r=num('rent'),v=num('vac')/100,t=num('target');if(!(u>0&&r>=0&&v>=0&&v<=1&&t>=0))throw 0;const g=u*r*12,l=g*v,e=g-l,occ=g>0?t/g*100:NaN;$('potential').textContent=fmt(g,2);$('lost').textContent=fmt(l,2);$('effective').textContent=fmt(e,2);$('needed').textContent=Number.isFinite(occ)?fmt(occ,2)+'%':'—';$('note').textContent=occ>100?'Target exceeds gross potential rent at the entered unit count and rent.':'Economic vacancy can include physical vacancy plus concessions or credit loss when that is your reporting definition.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Vacancy Impact Calculator works</h2><p>Gross potential rent assumes every unit is billed at the entered average rent for twelve months. The calculator applies an economic vacancy/credit-loss percentage to estimate lost revenue and effective rent. It also divides a target annual revenue by gross potential rent to show the occupancy-equivalent percentage needed to reach that target.</p><h2>How to use this vacancy impact calculator</h2><p>Enter total rentable units, average monthly rent, the vacancy/credit-loss assumption and an optional revenue target. Use an economic loss rate when you want to include more than empty units; if your organization separates physical vacancy, concessions and bad debt, combine only the components appropriate to the metric you are modelling.</p><h2>How to interpret the result</h2><p>The lost-rent output translates a vacancy percentage into a cash amount, which is often more actionable for leasing teams. The target occupancy result also catches impossible goals: if the target exceeds gross potential rent at the current rent and unit count, required occupancy will exceed 100%, indicating rent or inventory assumptions must change.</p><h2>Assumptions and limitations</h2><p>Average rent hides unit mix, seasonality, lease-up timing and renewal changes. The model does not distinguish vacant-days by unit, concessions, collection timing or market-rent loss. For detailed property management, calculate scheduled rent and losses at the unit/lease level and reconcile to accounting reports.</p><h2>Practical example and workflow</h2><p>With 20 units at 25,000 per month, gross potential rent is 6 million per year. An 8% economic loss reduces effective rent by 480,000. A leasing manager can compare that dollar loss with the cost of promotions or staffing intended to improve occupancy and collections.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is gross potential rent?','It is the rent that would be billed if all entered units earned the entered average rent for the full period with no loss.'],['Is vacancy rate the same as occupancy rate?','Physical vacancy and occupancy are complements, but economic vacancy can also include concessions or credit loss and therefore may not equal physical vacancy.'],['Why can required occupancy exceed 100%?','The revenue target is higher than the gross potential rent implied by the entered units and average rent.'],['Does this include operating expenses?','No. It models rental revenue loss only, not NOI or property profit.']];
require __DIR__.'/../includes/tool-template.php';
