<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('hr-payroll','ctc-to-take-home-salary-calculator-india');ob_start(); ?>
<h2>Estimate take-home from CTC</h2>
<p class="lead">Break annual CTC into employer-side costs and employee deductions instead of relying on a hidden salary formula.</p>
<div class="form-grid"><div class="field"><label for="ctc">Annual CTC</label><input id="ctc" type="number" value="1200000" step="0.01" min="0"></div><div class="field"><label for="employer">Annual employer contributions / benefits inside CTC</label><input id="employer" type="number" value="60000" step="0.01" min="0"></div><div class="field"><label for="bonus">Annual variable pay / bonus inside CTC</label><input id="bonus" type="number" value="100000" step="0.01" min="0"></div><div class="field"><label for="deductions">Monthly employee deductions excluding income tax</label><input id="deductions" type="number" value="5000" step="0.01" min="0"></div><div class="field"><label for="tax">Monthly income-tax / TDS estimate</label><input id="tax" type="number" value="8000" step="0.01" min="0"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated annual fixed gross cash</span><strong id="fixedAnnual">—</strong></div><div class="metric"><span>Average monthly gross cash</span><strong id="monthlyGross">—</strong></div><div class="metric"><span>Estimated monthly take-home</span><strong id="takeHome">—</strong></div><div class="metric"><span>Estimated annual take-home</span><strong id="annualTake">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='₹')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const c=num('ctc'),er=num('employer'),b=num('bonus'),d=num('deductions'),t=num('tax');if([c,er,b,d,t].some(v=>v<0)||er+b>c){note('Amounts cannot be negative, and employer/variable components should not exceed CTC.',true);return;}const fixed=c-er-b,mg=fixed/12,th=mg-d-t;$('fixedAnnual').textContent=money(fixed,'₹');$('monthlyGross').textContent=money(mg,'₹');$('takeHome').textContent=money(th,'₹');$('annualTake').textContent=money(th*12+b,'₹');note('Annual take-home shown adds the full variable-pay amount; actual payout and tax timing may differ.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>The calculator treats annual CTC as the total employer package. It subtracts employer-side benefits/contributions and variable pay to estimate fixed annual gross cash, divides that by 12, then subtracts the employee deductions and income-tax estimate you enter.</p><h2>How to use the result</h2><p>Use it to understand offer structure rather than relying on a single CTC headline. Enter the actual values from the compensation breakup when available, especially employer PF, insurance, gratuity provision, bonus and employee deductions.</p><h2>Assumptions and limitations</h2><p>CTC structures vary widely. This tool does not calculate current income-tax slabs, PF ceilings, professional tax, ESI eligibility or company-specific payroll rules automatically. Variable pay may not be guaranteed or paid monthly.</p><h2>Example</h2><p>A ₹12 lakh CTC can produce very different take-home amounts depending on employer contributions, bonus structure and employee-side deductions.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Why doesn\'t the calculator automatically apply income-tax slabs?','Tax depends on current law, tax regime, deductions and individual circumstances, so the tool asks you to enter a monthly tax estimate instead of silently assuming one.'],['Is bonus included in monthly take-home?','The regular monthly estimate excludes the annual variable-pay amount. The annual estimate adds it back as if fully paid.'],['Should employer PF inside CTC be entered separately?','Yes, if it is part of CTC but not paid as monthly gross cash, include it in employer contributions/benefits.'],['Is this an official payroll calculation?','No. It is a compensation-structure estimate; actual payslips and payroll rules control.']];require __DIR__.'/../includes/tool-template.php';
