<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('hr-payroll','gratuity-calculator-india');ob_start(); ?>
<h2>Estimate gratuity</h2>
<p class="lead">Use the 15/26 planning formula with your verified eligible salary and completed years of service.</p>
<div class="form-grid"><div class="field"><label for="salary">Last drawn eligible monthly salary</label><input id="salary" type="number" value="50000" step="0.01" min="0"></div><div class="field"><label for="years">Completed years of service</label><input id="years" type="number" value="8" step="1" min="0"></div><div class="field"><label for="extraMonths">Additional completed months</label><input id="extraMonths" type="number" value="7" step="1" min="0" max="11"><small>Optional rounding helper: 6 or more extra months can be counted as an additional year when that rule applies.</small></div><div class="field"><label for="rounding">Round 6+ months to next year?</label><select id="rounding"><option value="yes" selected>Yes</option><option value="no">No</option></select></div><div class="field"><label for="cap">Optional payout cap</label><input id="cap" type="number" value="2000000" step="0.01" min="0"><small>Set to 0 for no cap. Verify any statutory cap that applies.</small></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Service years used</span><strong id="service">—</strong></div><div class="metric"><span>Formula estimate</span><strong id="raw">—</strong></div><div class="metric"><span>Estimate after entered cap</span><strong id="payable">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='₹')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const s=num('salary'),y=num('years'),m=num('extraMonths'),cap=num('cap'),round=$('rounding').value==='yes';if(s<0||y<0||m<0||m>11||cap<0){note('Check salary, service months and cap values.',true);return;}const sy=y+(round&&m>=6?1:0),raw=s*15/26*sy,pay=cap>0?Math.min(raw,cap):raw;$('service').textContent=dec(sy,0);$('raw').textContent=money(raw,'₹');$('payable').textContent=money(pay,'₹');note('Eligibility, salary definition, service rounding and statutory caps must be verified for the employee.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>The planning formula used is gratuity = eligible monthly salary × 15 ÷ 26 × service years used. The optional rounding control can add one year when extra completed months are six or more, and an optional user-entered cap can limit the estimate.</p><h2>How to use the result</h2><p>Use the calculator only after confirming that gratuity rules apply to the employment situation and that the salary base is correct. The controls are explicit so the tool does not silently decide eligibility or current statutory limits.</p><h2>Assumptions and limitations</h2><p>Indian gratuity eligibility, covered establishments, continuous service, salary components, forfeiture rules, death/disability cases and statutory caps are legal matters that can change or require case-specific interpretation. This is an arithmetic estimate, not legal advice.</p><h2>Example</h2><p>With ₹50,000 eligible monthly salary and eight service years, the uncapped 15/26 formula estimate is about ₹230,769.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Does the calculator decide whether an employee is eligible for gratuity?','No. Eligibility must be verified separately; the tool only calculates from the inputs you provide.'],['Why is the cap editable?','Statutory or policy caps can change or differ by context, so you should enter the verified cap rather than rely on a hard-coded legal limit.'],['What salary should I enter?','Enter the salary component that your applicable gratuity rule treats as eligible; the tool does not determine that definition.'],['How are partial service years handled?','You can choose whether six or more extra completed months are rounded to an additional year for the estimate.']];require __DIR__.'/../includes/tool-template.php';
