<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('hr-payroll','notice-period-fnf-settlement-calculator');ob_start(); ?>
<h2>Estimate a simplified FnF settlement</h2>
<p class="lead">Combine earned salary and additions, then subtract notice recovery and other deductions.</p>
<div class="form-grid"><div class="field"><label for="monthly">Eligible monthly salary for proration</label><input id="monthly" type="number" value="60000" step="0.01" min="0"></div><div class="field"><label for="worked">Payable days in final month</label><input id="worked" type="number" value="15" step="0.01" min="0"></div><div class="field"><label for="divisor">Salary-day divisor</label><input id="divisor" type="number" value="30" step="0.01" min="0.0001"></div><div class="field"><label for="leave">Leave encashment amount</label><input id="leave" type="number" value="10000" step="0.01" min="0"></div><div class="field"><label for="additions">Other payable additions</label><input id="additions" type="number" value="5000" step="0.01" min="0"></div><div class="field"><label for="notice">Notice-period recovery</label><input id="notice" type="number" value="0" step="0.01" min="0"></div><div class="field"><label for="deductions">Other deductions</label><input id="deductions" type="number" value="3000" step="0.01" min="0"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Prorated earned salary</span><strong id="earned">—</strong></div><div class="metric"><span>Gross settlement additions</span><strong id="gross">—</strong></div><div class="metric"><span>Total recoveries / deductions</span><strong id="recoveries">—</strong></div><div class="metric"><span>Estimated net FnF</span><strong id="net">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const m=num('monthly'),w=num('worked'),d=num('divisor'),l=num('leave'),a=num('additions'),n=num('notice'),x=num('deductions');if([m,w,l,a,n,x].some(v=>v<0)||d<=0){note('Amounts/days cannot be negative and divisor must be positive.',true);return;}const earned=m/d*w,gross=earned+l+a,rec=n+x;$('earned').textContent=money(earned,'');$('gross').textContent=money(gross,'');$('recoveries').textContent=money(rec,'');$('net').textContent=money(gross-rec,'');note('This is a simplified arithmetic worksheet, not a determination of lawful notice recovery or final-pay obligations.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Prorated earned salary = eligible monthly salary ÷ salary-day divisor × payable days. Gross settlement adds leave encashment and other payable additions. Net estimate subtracts notice-period recovery and other entered deductions.</p><h2>How to use the result</h2><p>Use the calculator as a reconciliation worksheet after HR/payroll has identified the actual payable and recoverable components. Keeping notice recovery as a separate input makes the settlement logic visible.</p><h2>Assumptions and limitations</h2><p>Final settlement can also include bonus, incentives, gratuity, reimbursements, asset recovery, loans, statutory deductions and tax. Notice-pay rights and salary proration rules depend on contracts, policies and law. The tool does not determine what may legally be deducted.</p><h2>Example</h2><p>Review each input against the employee's final payslip calculation rather than treating the result as an automatic payroll instruction.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Does this calculate whether notice recovery is legally allowed?','No. Enter a notice-recovery amount only after it has been determined under the relevant contract, policy and law.'],['Is gratuity included?','Not automatically. Add any separately calculated payable amount through other additions if appropriate.'],['Why is the day divisor editable?','Salary proration methods vary, so the tool lets you use the divisor actually applied by your payroll process.'],['Does the result include income tax?','Only if you include applicable tax within other deductions or handle it separately.']];require __DIR__.'/../includes/tool-template.php';
