<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('hr-payroll','pf-esi-calculator-india');ob_start(); ?>
<h2>Estimate PF and ESI contributions</h2>
<p class="lead">Enter the wage bases and rates verified for the employee and payroll period.</p>
<div class="form-grid"><div class="field"><label for="pfWage">PF wage base</label><input id="pfWage" type="number" value="15000" step="0.01" min="0"></div><div class="field"><label for="pfEmployee">Employee PF rate (%)</label><input id="pfEmployee" type="number" value="12" step="0.01" min="0" max="100"></div><div class="field"><label for="pfEmployer">Employer PF rate (%)</label><input id="pfEmployer" type="number" value="12" step="0.01" min="0" max="100"></div><div class="field"><label for="esiWage">ESI wage base</label><input id="esiWage" type="number" value="18000" step="0.01" min="0"></div><div class="field"><label for="esiEmployee">Employee ESI rate (%)</label><input id="esiEmployee" type="number" value="0.75" step="0.01" min="0" max="100"></div><div class="field"><label for="esiEmployer">Employer ESI rate (%)</label><input id="esiEmployer" type="number" value="3.25" step="0.01" min="0" max="100"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Employee PF</span><strong id="empPF">—</strong></div><div class="metric"><span>Employer PF</span><strong id="erPF">—</strong></div><div class="metric"><span>Employee ESI</span><strong id="empESI">—</strong></div><div class="metric"><span>Employer ESI</span><strong id="erESI">—</strong></div><div class="metric"><span>Employee contribution total</span><strong id="employeeTotal">—</strong></div><div class="metric"><span>Employer contribution total</span><strong id="employerTotal">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='₹')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const pw=num('pfWage'),pe=num('pfEmployee')/100,pr=num('pfEmployer')/100,ew=num('esiWage'),ee=num('esiEmployee')/100,er=num('esiEmployer')/100;if([pw,ew,pe,pr,ee,er].some(v=>v<0)){note('Wage bases and rates cannot be negative.',true);return;}const epf=pw*pe,rpf=pw*pr,eesi=ew*ee,resi=ew*er;$('empPF').textContent=money(epf,'₹');$('erPF').textContent=money(rpf,'₹');$('empESI').textContent=money(eesi,'₹');$('erESI').textContent=money(resi,'₹');$('employeeTotal').textContent=money(epf+eesi,'₹');$('employerTotal').textContent=money(rpf+resi,'₹');note('Defaults are editable examples. Verify coverage, wage ceilings/bases and current statutory rates before payroll use.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Each contribution is calculated as the entered wage base × the entered contribution rate. Employee PF and ESI are summed separately from employer PF and ESI so payroll deductions and employer cost are visible.</p><h2>How to use the result</h2><p>Use the actual contribution wage base and rates produced by your payroll or statutory eligibility process. The calculator deliberately does not infer whether an employee is covered or automatically impose wage ceilings.</p><h2>Assumptions and limitations</h2><p>PF and ESI coverage, wage definitions, ceilings, exclusions and contribution rates are statutory matters that can change. Employer PF may also be allocated across statutory components in ways this simple calculator does not break down.</p><h2>Example</h2><p>Because all rates and wage bases are editable, the tool can be used as an arithmetic checker without claiming that the displayed defaults are universally current.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Do the default PF and ESI rates guarantee current statutory treatment?','No. They are editable examples. Verify current rates, coverage and wage definitions before payroll use.'],['Does the tool apply PF or ESI wage ceilings automatically?','No. Enter the wage base that your verified payroll treatment uses.'],['Does employer PF equal the amount deposited into one account?','Not necessarily. Employer contributions can be allocated across statutory components; this tool shows only the entered total-rate calculation.'],['Can I set a rate to zero?','Yes, when you intentionally want to model no contribution for that component after verifying applicability.']];require __DIR__.'/../includes/tool-template.php';
