<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('hr-payroll','recruitment-funnel-conversion-calculator');ob_start(); ?>
<h2>Measure recruiting funnel conversion</h2>
<p class="lead">Enter candidate counts at each stage from applicants through hires.</p>
<div class="form-grid"><div class="field"><label for="applicants">Applicants</label><input id="applicants" type="number" value="500" step="1" min="0"></div><div class="field"><label for="screened">Screened / shortlisted</label><input id="screened" type="number" value="150" step="1" min="0"></div><div class="field"><label for="interviews">Interviewed</label><input id="interviews" type="number" value="60" step="1" min="0"></div><div class="field"><label for="offers">Offers made</label><input id="offers" type="number" value="20" step="1" min="0"></div><div class="field"><label for="hires">Hires</label><input id="hires" type="number" value="15" step="1" min="0"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Applicant → screen</span><strong id="screenRate">—</strong></div><div class="metric"><span>Screen → interview</span><strong id="interviewRate">—</strong></div><div class="metric"><span>Interview → offer</span><strong id="offerRate">—</strong></div><div class="metric"><span>Offer → hire</span><strong id="hireRate">—</strong></div><div class="metric"><span>Applicant → hire</span><strong id="overall">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function cv(a,b){return a>0?b/a*100:NaN;}function go(){const a=num('applicants'),s=num('screened'),i=num('interviews'),o=num('offers'),h=num('hires');if([a,s,i,o,h].some(v=>v<0)){note('Stage counts cannot be negative.',true);return;}$('screenRate').textContent=pct(cv(a,s));$('interviewRate').textContent=pct(cv(s,i));$('offerRate').textContent=pct(cv(i,o));$('hireRate').textContent=pct(cv(o,h));$('overall').textContent=pct(cv(a,h));const nonMono=(s>a)||(i>s)||(o>i)||(h>o);note(nonMono?'A later stage count exceeds an earlier stage. This can happen with mixed cohorts, but check that the funnel period is comparable.':'Stage counts are non-increasing, consistent with a single-cohort funnel.',nonMono);}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Each stage conversion rate divides the later-stage count by the immediately preceding stage. Overall applicant-to-hire conversion divides hires by applicants.</p><h2>How to use the result</h2><p>Use the funnel to locate where candidate volume narrows most. A low stage conversion may reflect sourcing quality, screening criteria, interview capacity, compensation, candidate experience or market conditions depending on the stage.</p><h2>Assumptions and limitations</h2><p>Period-based funnels can mix cohorts: candidates who applied before the period may be interviewed during it, causing a later-stage count to exceed an earlier stage. Cohort-based reporting gives cleaner conversion analysis when available.</p><h2>Example</h2><p>With 500 applicants and 15 hires, overall applicant-to-hire conversion is 3%, but stage rates show where most of the narrowing occurred.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Why can a later stage count be higher than an earlier one?','Period reports can mix candidate cohorts. People entering a later stage this month may have applied in a previous month.'],['Should I use unique candidates or activities?','Use consistent unique-candidate counts for a true funnel unless your reporting definition explicitly uses activities.'],['What does a low screen-to-interview rate mean?','It shows a narrow transition, but the reason requires context such as qualification quality, role requirements or interview capacity.'],['Can I compare roles?','Yes, but compare similar role types and periods because funnel behavior can vary substantially by market and seniority.']];require __DIR__.'/../includes/tool-template.php';
