<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('printing-packaging','bleed-trim-calculator');
ob_start();
?>
<h2>Calculate trim, bleed and safe area</h2><p class="lead">Turn a finished print size into a document/artwork size with bleed and an optional inner safe margin.</p><div class="notice">Bleed extends artwork outside the trim edge to tolerate cutting variation. Always use the printer’s production specification when it differs from the defaults here.</div><div class="form-grid"><div class="field"><label for="w">Finished trim width (mm)</label><input id="w" type="number" value="210" min="0.1" step="any"></div><div class="field"><label for="h">Finished trim height (mm)</label><input id="h" type="number" value="297" min="0.1" step="any"></div><div class="field"><label for="bleed">Bleed on each edge (mm)</label><input id="bleed" type="number" value="3" min="0" step="any"></div><div class="field"><label for="safe">Safe margin inside trim (mm)</label><input id="safe" type="number" value="5" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Artwork size with bleed</span><strong id="doc">—</strong></div><div class="metric"><span>Inner safe area</span><strong id="safearea">—</strong></div><div class="metric"><span>Added bleed area</span><strong id="bleedarea">—</strong></div><div class="metric"><span>Trim size</span><strong id="trim">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('doc').textContent='—';$('safearea').textContent='—';$('bleedarea').textContent='—';$('trim').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const w=num('w'),h=num('h'),b=num('bleed'),s=num('safe');if(!(w>0&&h>0&&b>=0&&s>=0&&2*s<w&&2*s<h))throw 0;const dw=w+2*b,dh=h+2*b;const sa=(w-2*s)*(h-2*s),ba=dw*dh-w*h;$('doc').textContent=fmt(dw,2)+' × '+fmt(dh,2)+' mm';$('safearea').textContent=fmt(w-2*s,2)+' × '+fmt(h-2*s,2)+' mm';$('bleedarea').textContent=fmt(ba,0)+' mm²';$('trim').textContent=fmt(w,2)+' × '+fmt(h,2)+' mm';$('note').textContent='Adobe notes that 3 mm / 0.125 in is common, but the print provider’s specification is the authority for the actual bleed and safe margins.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Bleed &amp; Trim Calculator works</h2><p>Bleed is artwork that extends beyond the final trim edge so small cutting variation does not reveal an unintended white line. Document size with equal bleed is trim width + 2×bleed by trim height + 2×bleed. A safe margin works in the opposite direction, keeping critical text and logos inside the trim edge.</p><h2>How to use this bleed &amp; trim calculator</h2><p>Enter the finished size supplied by the job specification, then the bleed required on each edge and a chosen inner safe margin. Adobe’s current InDesign guidance notes that 0.125 inch / 3 mm is commonly used, but also says to verify the print provider’s requirement. This calculator therefore keeps both values editable.</p><h2>How to interpret the result</h2><p>The artwork-size result is the canvas/export extent needed if your file includes the bleed area. The safe-area dimensions are a planning aid for critical content; they are not a substitute for dielines or printer templates. The added bleed-area figure can help explain why the export size is larger than the finished product.</p><h2>Assumptions and limitations</h2><p>Different products and finishing methods use different bleed and safe-zone requirements. Large-format, packaging, folded pieces and bound work can need asymmetric or much larger allowances. Crop/trim marks also sit outside or around the trim and may require additional media space; use the printer’s PDF preset or template for production files.</p><h2>Practical example and workflow</h2><p>An A4 trim size of 210 × 297 mm with 3 mm bleed becomes 216 × 303 mm artwork. With a 5 mm safe margin, critical content should stay within a 200 × 287 mm inner area. The designer can use those three boxes—bleed, trim and safe—as separate layout guides.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Is 3 mm bleed always correct?','No. 3 mm or 0.125 inch is common, but your print provider’s specification should override any default.'],['What is the difference between bleed and trim?','Trim is the final cut size. Bleed extends artwork beyond that cut so edge-to-edge color survives small trimming variation.'],['What is a safe area?','It is an inner margin used to keep important text and graphics away from the trim edge. The required amount depends on the product and finisher.'],['Does this calculator add crop marks?','No. It calculates dimensions only. Crop/trim marks should be added according to your print provider’s PDF/export requirements.']];
require __DIR__.'/../includes/tool-template.php';
