<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('printing-packaging','imposition-sheet-yield-calculator');
ob_start();
?>
<h2>Estimate sheet imposition yield</h2><p class="lead">Compare normal and rotated layouts to estimate how many finished pieces fit on a parent sheet.</p><div class="notice">Use piece dimensions that already include required bleed or spacing. Press gripper, color bars and finishing constraints should be included in the unusable edge margin or handled in the production imposition system.</div><div class="form-grid"><div class="field"><label for="sw">Parent sheet width (mm)</label><input id="sw" type="number" value="700" min="0.1" step="any"></div><div class="field"><label for="sh">Parent sheet height (mm)</label><input id="sh" type="number" value="1000" min="0.1" step="any"></div><div class="field"><label for="iw">Piece width incl. bleed (mm)</label><input id="iw" type="number" value="216" min="0.1" step="any"></div><div class="field"><label for="ih">Piece height incl. bleed (mm)</label><input id="ih" type="number" value="303" min="0.1" step="any"></div><div class="field"><label for="gap">Gutter between pieces (mm)</label><input id="gap" type="number" value="5" min="0" step="any"></div><div class="field"><label for="margin">Unusable edge margin each side (mm)</label><input id="margin" type="number" value="10" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Best pieces per sheet</span><strong id="best">—</strong></div><div class="metric"><span>Normal orientation</span><strong id="normal">—</strong></div><div class="metric"><span>Rotated orientation</span><strong id="rotated">—</strong></div><div class="metric"><span>Approx. unused area</span><strong id="waste">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('best').textContent='—';$('normal').textContent='—';$('rotated').textContent='—';$('waste').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const sw=num('sw'),sh=num('sh'),iw=num('iw'),ih=num('ih'),g=num('gap'),m=num('margin');if(!(sw>0&&sh>0&&iw>0&&ih>0&&g>=0&&m>=0&&sw>2*m&&sh>2*m))throw 0;const aw=sw-2*m,ah=sh-2*m;const fit=(w,h)=>{const cols=Math.max(0,Math.floor((aw+g)/(w+g))),rows=Math.max(0,Math.floor((ah+g)/(h+g)));return {n:cols*rows,cols,rows}};const a=fit(iw,ih),b=fit(ih,iw),best=a.n>=b.n?a:b;const used=best.n*iw*ih,avail=aw*ah;const waste=avail>0?(1-used/avail)*100:100;$('best').textContent=best.n+' pieces';$('normal').textContent=a.n+' ('+a.cols+'×'+a.rows+')';$('rotated').textContent=b.n+' ('+b.cols+'×'+b.rows+')';$('waste').textContent=fmt(waste,1)+'%';$('note').textContent='This is a rectangular grid estimate. It does not optimize mixed rotation, gang jobs, gripper/side-lay requirements or complex dielines.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Imposition Sheet Yield Calculator works</h2><p>This calculator tests two simple rectangular impositions: all pieces in their normal orientation and all pieces rotated 90 degrees. Available sheet size is reduced by the entered edge margin, then the tool uses floor((available dimension + gutter) ÷ (piece dimension + gutter)) to count columns and rows. The higher-yield orientation is reported.</p><h2>How to use this imposition sheet yield calculator</h2><p>Enter the usable parent-sheet size, the imposed piece size including any bleed you want reserved, the gutter between pieces and an edge margin for areas that cannot be occupied. The result shows both orientation counts so a prepress operator can see whether rotation alone improves yield before opening dedicated imposition software.</p><h2>How to interpret the result</h2><p>Pieces per sheet is only the first production question. The approximate unused-area percentage helps reveal whether a layout that technically fits leaves significant waste. However, material waste and press economics also depend on makeready, grain direction, finishing, color bars, gripper edge and whether offcuts can be reused.</p><h2>Assumptions and limitations</h2><p>The tool does not solve mixed-orientation nesting, irregular shapes, folding signatures, work-and-turn/work-and-tumble layouts, packaging dielines or gang runs. It assumes a simple axis-aligned grid. For press-ready imposition, use the printer’s workflow and constraints; this utility is for fast estimating and feasibility checking.</p><h2>Practical example and workflow</h2><p>On a 700 × 1000 mm sheet with 10 mm edge margins, a 216 × 303 mm piece and 5 mm gutters, the calculator compares the two grid orientations. An estimator can use the best count to estimate required sheets, then hand the job to prepress for final imposition and press-specific marks.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does this tool include bleed?','Only if you include bleed in the piece width and height you enter. That is the safest approach for estimating.'],['What should I put in the edge margin?','Reserve any area unavailable to artwork, such as gripper/side-lay, press marks or trimming constraints. Use your press or vendor specification.'],['Can it mix rotated and unrotated pieces on one sheet?','No. It compares two uniform rectangular grids. Mixed-orientation nesting can sometimes yield more and needs a more advanced imposition optimizer.'],['Is unused area the same as paper waste?','Not exactly. It is geometric unused area inside the entered usable sheet; real waste also includes makeready, spoilage, offcuts and finishing losses.']];
require __DIR__.'/../includes/tool-template.php';
