<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('printing-packaging','packaging-box-volume-calculator');
ob_start();
?>
<h2>Calculate packaging box volume</h2><p class="lead">Calculate rectangular box volume, capacity and optional material-volume difference between outside and inside dimensions.</p><div class="notice">Use actual internal dimensions when capacity must be precise. Outside dimensions are often the relevant dimensions for storage and freight planning.</div><div class="form-grid"><div class="field"><label for="l">Length (cm)</label><input id="l" type="number" value="40" min="0.001" step="any"></div><div class="field"><label for="w">Width (cm)</label><input id="w" type="number" value="30" min="0.001" step="any"></div><div class="field"><label for="h">Height (cm)</label><input id="h" type="number" value="20" min="0.001" step="any"></div><div class="field"><label for="th">Wall thickness per side (mm, optional)</label><input id="th" type="number" value="3" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Outer volume</span><strong id="outer">—</strong></div><div class="metric"><span>Outer capacity</span><strong id="litres">—</strong></div><div class="metric"><span>Approx. inner volume</span><strong id="inner">—</strong></div><div class="metric"><span>Volume difference</span><strong id="material">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('outer').textContent='—';$('litres').textContent='—';$('inner').textContent='—';$('material').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const l=num('l'),w=num('w'),h=num('h'),t=num('th')/10;if(!(l>0&&w>0&&h>0&&t>=0&&2*t<Math.min(l,w,h)))throw 0;const ov=l*w*h,il=l-2*t,iw=w-2*t,ih=h-2*t,iv=il*iw*ih;$('outer').textContent=fmt(ov,0)+' cm³';$('litres').textContent=fmt(ov/1000,3)+' L';$('inner').textContent=fmt(iv/1000,3)+' L';$('material').textContent=fmt((ov-iv)/1000,3)+' L';$('note').textContent='Wall-thickness subtraction is a simple rectangular approximation. Corrugated board folds, flaps, compression and internal fittings change usable volume.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Packaging Box Volume Calculator works</h2><p>A rectangular box volume is length × width × height. This calculator reports the outside volume and converts cubic centimetres to litres. If a wall thickness is entered, it subtracts twice that thickness from each dimension to estimate a simple internal rectangular volume, making the difference between outside and usable capacity visible.</p><h2>How to use this packaging box volume calculator</h2><p>Enter dimensions consistently in centimetres. Use external dimensions when planning pallet, shelf, carton or courier space. Use known internal dimensions when checking product fit. The wall-thickness field is only a convenience when you have external dimensions and a roughly uniform wall; for corrugated packaging, supplier internal dimensions are preferable.</p><h2>How to interpret the result</h2><p>Outer volume is useful for cube utilization and storage planning, while internal volume is more relevant to contents. The difference is not literally the volume of board in a folded box because flaps overlap and corners are constructed differently; it is simply the difference between two rectangular envelopes.</p><h2>Assumptions and limitations</h2><p>This model assumes a rectangular prism. It does not account for tapered cartons, rounded corners, inserts, dividers, void fill, compression, board caliper changes at folds or manufacturing tolerances. Freight carriers may use dimensional weight rather than physical box volume alone, so use the appropriate shipping calculator for chargeable weight.</p><h2>Practical example and workflow</h2><p>A 40 × 30 × 20 cm carton has a 24-litre outside envelope. If the wall is approximated at 3 mm per side, the internal dimensions shrink slightly and usable rectangular capacity falls below 24 litres. A packaging engineer can compare that with the product’s actual bounding dimensions and protective-fill requirement.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Should I use inside or outside box dimensions?','Use outside dimensions for storage/freight cube and inside dimensions for product capacity. If only outside dimensions are known, wall-thickness subtraction is an approximation.'],['How many cubic centimetres are in one litre?','One litre equals 1,000 cubic centimetres.'],['Does the wall-thickness result equal the amount of cardboard used?','No. It is the volume difference between outer and inner rectangular envelopes, not the physical board volume after flaps and folds.'],['Can I use this for shipping dimensional weight?','Box volume is an input to some dimensional-weight methods, but carriers apply their own divisors and rules. Use a carrier-specific dimensional-weight calculation for charges.']];
require __DIR__.'/../includes/tool-template.php';
