<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('printing-packaging','paper-weight-gsm-converter');
ob_start();
?>
<h2>Convert paper basis weight and GSM</h2><p class="lead">Convert U.S. basis weight in pounds per ream to grammage only when the basic sheet size and ream count are known.</p><div class="notice">TAPPI defines grammage as mass per unit area and basis weight as pounds for a stated ream/basic size. Common basic sizes include 17×22 bond, 25×38 text/book and 20×26 cover, but verify your grade.</div><div class="form-grid"><div class="field"><label for="mode">Conversion direction</label><select id="mode"><option value="lb2gsm" selected>Basis weight (lb) → GSM</option><option value="gsm2lb">GSM → basis weight (lb)</option></select></div><div class="field"><label for="value">Weight value</label><input id="value" type="number" value="80" min="0.001" step="any"></div><div class="field"><label for="bw">Basic sheet width (inches)</label><input id="bw" type="number" value="25" min="0.001" step="any"></div><div class="field"><label for="bh">Basic sheet height (inches)</label><input id="bh" type="number" value="38" min="0.001" step="any"></div><div class="field"><label for="ream">Sheets per ream</label><input id="ream" type="number" value="500" min="1" step="1"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Grammage</span><strong id="gsm">—</strong></div><div class="metric"><span>Basis weight</span><strong id="lb">—</strong></div><div class="metric"><span>Basic sheet area</span><strong id="area">—</strong></div><div class="metric"><span>Mass of one basic sheet</span><strong id="mass">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('gsm').textContent='—';$('lb').textContent='—';$('area').textContent='—';$('mass').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const mode=$('mode').value,v=num('value'),w=num('bw'),h=num('bh'),r=num('ream');if(!(v>0&&w>0&&h>0&&r>0))throw 0;const areaIn=w*h,areaM=areaIn*0.00064516;let gsm,lb;if(mode==='lb2gsm'){lb=v;gsm=(lb*453.59237)/(r*areaM)}else{gsm=v;lb=gsm*r*areaM/453.59237}$('gsm').textContent=fmt(gsm,2)+' g/m²';$('lb').textContent=fmt(lb,2)+' lb/ream';$('area').textContent=fmt(areaIn,2)+' in²';$('mass').textContent=fmt(gsm*areaM,2)+' g';$('note').textContent='Basis weight is grade-specific because the basic sheet size differs. There is no universal “80 lb = one GSM” conversion without the basis size and ream count.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Paper Weight GSM Converter works</h2><p>GSM, or grammage, is mass in grams per square metre. U.S. basis weight is different: it is the mass in pounds of a ream at a paper-grade-specific basic size. The calculator converts the ream mass to grams and divides by the total area of all basic sheets. Reverse conversion applies the same relationship in the other direction.</p><h2>How to use this paper weight gsm converter</h2><p>Choose a conversion direction, enter the weight value, then enter the paper grade’s basic sheet width, height and ream sheet count. TAPPI notes that 500 sheets is common but not universal. For example, bond/writing is commonly based on 17 × 22 inches, text/book on 25 × 38, cover on 20 × 26 and index on 25.5 × 30.5.</p><h2>How to interpret the result</h2><p>The same “80 lb” label can represent very different GSM values because the basic sheet area changes by grade. That is why a paper converter that asks only for pounds and returns one fixed GSM number can be wrong. The basic-sheet area shown in the result makes the conversion basis auditable.</p><h2>Assumptions and limitations</h2><p>This is a mass-per-area conversion, not a thickness calculator. Paper caliper varies with furnish, coating, density and manufacturing. Confirm the grade’s basic size and ream convention from the mill, merchant or applicable standard before using converted values in purchasing specifications or press settings.</p><h2>Practical example and workflow</h2><p>An 80 lb text/book stock using a 25 × 38 inch, 500-sheet basis converts to roughly 118 GSM, while 80 lb cover uses a 20 × 26 basic size and is much heavier per square metre. The calculator exposes that difference instead of treating both 80 lb labels as equivalent.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Why can’t 80 lb paper be converted to one universal GSM value?','Because basis weight depends on the paper grade’s basic sheet size. 80 lb text and 80 lb cover are based on different areas and therefore have different grammage.'],['What is GSM?','GSM is grams per square metre, a direct mass-per-area measurement also called grammage.'],['What ream count should I use?','Use the convention for the specific grade/product. 500 sheets is common, but standards and products can use other counts.'],['Does GSM tell me paper thickness?','No. Two papers with the same GSM can have different caliper because density, fibre, coating and finish differ.']];
require __DIR__.'/../includes/tool-template.php';
