<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('printing-packaging','print-dpi-resolution-calculator');
ob_start();
?>
<h2>Check print artwork resolution</h2><p class="lead">Calculate required pixel dimensions for trim plus bleed and compare them with an existing artwork file.</p><div class="notice">This checks raster pixel density across the full document including bleed. Vector text/art is resolution-independent until rasterized, while linked images still need adequate effective PPI.</div><div class="form-grid"><div class="field"><label for="w">Trim width (inches)</label><input id="w" type="number" value="8.5" min="0.01" step="any"></div><div class="field"><label for="h">Trim height (inches)</label><input id="h" type="number" value="11" min="0.01" step="any"></div><div class="field"><label for="bleed">Bleed each edge (inches)</label><input id="bleed" type="number" value="0.125" min="0" step="any"></div><div class="field"><label for="ppi">Required image PPI</label><input id="ppi" type="number" value="300" min="1" step="any"></div><div class="field"><label for="pxw">Artwork width (pixels)</label><input id="pxw" type="number" value="2625" min="1" step="1"></div><div class="field"><label for="pxh">Artwork height (pixels)</label><input id="pxh" type="number" value="3375" min="1" step="1"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Required pixels incl. bleed</span><strong id="required">—</strong></div><div class="metric"><span>Effective artwork PPI</span><strong id="effective">—</strong></div><div class="metric"><span>Resolution check</span><strong id="status">—</strong></div><div class="metric"><span>Document size incl. bleed</span><strong id="doc">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('required').textContent='—';$('effective').textContent='—';$('status').textContent='—';$('doc').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const w=num('w'),h=num('h'),b=num('bleed'),p=num('ppi'),pw=num('pxw'),ph=num('pxh');if(!(w>0&&h>0&&b>=0&&p>0&&pw>0&&ph>0))throw 0;const dw=w+2*b,dh=h+2*b,rw=Math.ceil(dw*p),rh=Math.ceil(dh*p),ep=Math.min(pw/dw,ph/dh),ok=pw>=rw&&ph>=rh;$('required').textContent=rw+' × '+rh+' px';$('effective').textContent=fmt(ep,0)+' PPI';$('status').textContent=ok?'Meets entered PPI':'Below entered PPI';$('doc').textContent=fmt(dw,3)+' × '+fmt(dh,3)+' in';$('note').textContent='Image PPI and printer DPI are not the same specification. Use the print provider’s required artwork resolution and bleed.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Print DPI / Resolution Calculator works</h2><p>For raster artwork, required pixels equal physical document inches × required pixels per inch. The tool adds bleed to both sides of the trim dimensions, calculates the pixel dimensions needed at the entered PPI, and compares them with the current artwork. Effective PPI is based on the limiting width or height.</p><h2>How to use this print dpi / resolution calculator</h2><p>Enter final trim size, bleed per edge and the image-resolution requirement supplied by the printer. Then enter the raster artwork’s pixel dimensions. A 300 PPI target is common in many commercial-print workflows, but Adobe notes that required image resolution depends on the output process, printer resolution and screen frequency, so the provider’s specification should be used.</p><h2>How to interpret the result</h2><p>A “meets target” result means the pixel dimensions are at least as large as the calculated requirement for the full bleed document. It does not mean the file is otherwise press-ready. Color space, embedded profiles, transparency, overprint, fonts, black generation and PDF standard are separate production checks.</p><h2>Assumptions and limitations</h2><p>Image PPI is often incorrectly called DPI. Printer DPI describes output-device dots; image resolution is pixels per inch. Vector artwork does not need a fixed pixel count until rasterized, although embedded raster images do. Cropping or scaling an image in layout software changes its effective PPI.</p><h2>Practical example and workflow</h2><p>An 8.5 × 11 inch piece with 0.125 inch bleed becomes 8.75 × 11.25 inches. At 300 PPI, a full-page raster image needs at least 2625 × 3375 pixels. This calculator lets prepress check that requirement before creating the final PDF.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Is 300 DPI the same as 300 PPI?','No. For artwork, 300 usually refers to image pixels per inch. Printer DPI is an output-device dot specification.'],['Should bleed be included when calculating required pixels?','Yes, if the raster image must extend through the bleed. Calculate pixels for the full bleed document, not only the trimmed size.'],['Do vector logos need 300 PPI?','Vector shapes are resolution-independent until rasterized. Any raster images inside the design still have effective PPI.'],['What resolution should I use for print?','Use the printer’s requirement. 300 PPI is common for many close-viewed jobs, but output method and screen frequency can justify different values.']];
require __DIR__.'/../includes/tool-template.php';
