<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('printing-packaging','roll-material-length-calculator');
ob_start();
?>
<h2>Estimate material length on a roll</h2><p class="lead">Calculate roll length from outside diameter, core diameter and material thickness.</p><div class="notice">Measure outside diameter and core diameter at the same location and use actual material caliper including adhesive/liner layers where relevant.</div><div class="form-grid"><div class="field"><label for="od">Outside roll diameter (mm)</label><input id="od" type="number" value="300" min="0.1" step="any"></div><div class="field"><label for="idiam">Core outside diameter (mm)</label><input id="idiam" type="number" value="76" min="0" step="any"></div><div class="field"><label for="th">Material thickness (microns)</label><input id="th" type="number" value="100" min="0.01" step="any"></div><div class="field"><label for="width">Web width (mm)</label><input id="width" type="number" value="1000" min="0.1" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated roll length</span><strong id="length">—</strong></div><div class="metric"><span>Material area</span><strong id="area">—</strong></div><div class="metric"><span>Approx. radial layers</span><strong id="turns">—</strong></div><div class="metric"><span>OD / core ratio</span><strong id="ratio">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('length').textContent='—';$('area').textContent='—';$('turns').textContent='—';$('ratio').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const D=num('od'),d=num('idiam'),um=num('th'),w=num('width');const t=um/1000;if(!(D>0&&d>=0&&D>d&&t>0&&w>0))throw 0;const L=Math.PI*(D*D-d*d)/(4*t),area=(L/1000)*(w/1000),layers=(D-d)/(2*t);$('length').textContent=fmt(L/1000,2)+' m';$('area').textContent=fmt(area,2)+' m²';$('turns').textContent=fmt(layers,0);$('ratio').textContent=fmt(D/Math.max(d,0.0001),2)+'×';$('note').textContent='The geometric formula assumes uniform thickness and tight, gap-free winding. Real roll length varies with compression, air, tension and thickness tolerance.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Roll Material Length Calculator works</h2><p>The geometric roll-length relationship is L = π × (OD² − core²) ÷ (4 × thickness), provided all dimensions use the same unit. This comes from equating the cross-sectional area of wound material with thickness × length. The calculator converts microns to millimetres and also reports material area from web width.</p><h2>How to use this roll material length calculator</h2><p>Measure the roll outside diameter, core outside diameter and material caliper. Include liner, adhesive or laminate thickness if those layers are wound with the product. Enter web width if you also want square metres. For a partially used roll, measure OD carefully without compressing the material or including flanges.</p><h2>How to interpret the result</h2><p>The result is most useful for inventory estimates and production planning when a roll does not have a trustworthy length label. Small errors in outside diameter or thickness can create large length errors because diameter is squared. The approximate radial-layer count helps spot obviously inconsistent inputs.</p><h2>Assumptions and limitations</h2><p>The formula assumes a perfectly cylindrical, tightly wound roll with uniform thickness and no air gaps. Real paper, foam, textiles, labelstock and flexible films compress differently with winding tension. Cores may also deform. For commercial custody or billing, use a calibrated counter or manufacturer measurement rather than geometry alone.</p><h2>Practical example and workflow</h2><p>A 300 mm OD roll on a 76 mm core with 100-micron total thickness contains roughly hundreds of metres of material. If the web is 1 m wide, the calculated square metres are numerically close to metres of length, making it easy to estimate how many signs or labels the remaining roll can produce.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What thickness should I use for labels or tape?','Use total wound caliper, including liner and adhesive layers if they remain on the roll.'],['Why does a small thickness error change length so much?','Length is inversely proportional to thickness, so a 10% caliper error can create roughly a 10% length error even before diameter measurement error.'],['Can I use the formula for foam or fabric?','Only as a rough estimate. Compressible materials and loose winding violate the uniform gap-free geometry assumption.'],['Is the result accurate enough for billing?','Usually not by itself. Use a calibrated length counter or supplier-certified quantity when contractual accuracy is required.']];
require __DIR__.'/../includes/tool-template.php';
