<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('printing-packaging','signage-area-vinyl-quantity-calculator');
ob_start();
?>
<h2>Estimate signage area and vinyl quantity</h2><p class="lead">Calculate finished sign area and approximate roll length including a waste allowance.</p><div class="notice">This is a material-area estimator, not a nesting optimizer. Add realistic allowances for margins, overlaps, test cuts, defects, color matching and panel seams.</div><div class="form-grid"><div class="field"><label for="w">Sign width (m)</label><input id="w" type="number" value="1.2" min="0.001" step="any"></div><div class="field"><label for="h">Sign height (m)</label><input id="h" type="number" value="0.8" min="0.001" step="any"></div><div class="field"><label for="qty">Quantity</label><input id="qty" type="number" value="10" min="1" step="1"></div><div class="field"><label for="waste">Waste allowance (%)</label><input id="waste" type="number" value="12" min="0" step="any"></div><div class="field"><label for="roll">Vinyl roll width (m)</label><input id="roll" type="number" value="1.37" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Finished sign area</span><strong id="area">—</strong></div><div class="metric"><span>Area incl. waste</span><strong id="buy">—</strong></div><div class="metric"><span>Approx. roll length</span><strong id="length">—</strong></div><div class="metric"><span>Area utilization</span><strong id="util">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('area').textContent='—';$('buy').textContent='—';$('length').textContent='—';$('util').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const w=num('w'),h=num('h'),q=num('qty'),wa=num('waste'),rw=num('roll');if(!(w>0&&h>0&&q>0&&wa>=0&&rw>0))throw 0;const a=w*h*q,b=a*(1+wa/100),len=b/rw,util=a/b*100;$('area').textContent=fmt(a,2)+' m²';$('buy').textContent=fmt(b,2)+' m²';$('length').textContent=fmt(len,2)+' m';$('util').textContent=fmt(util,1)+'%';$('note').textContent=w>rw?'Sign width exceeds the entered roll width. The area-based length does not account for panel seams or nesting; plan panels separately.':'Roll length is area ÷ roll width and does not optimize nesting, margins or panel orientation.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Signage Area &amp; Vinyl Quantity Calculator works</h2><p>The calculator multiplies sign width × height × quantity to get finished face area, then applies the entered waste allowance. Approximate roll length is purchase area ÷ roll width. This gives a fast material budget for rectangular signs, window graphics, wall panels or flat vinyl applications before detailed nesting.</p><h2>How to use this signage area &amp; vinyl quantity calculator</h2><p>Enter the finished width and height of one sign, quantity, expected waste percentage and usable vinyl roll width. The waste allowance should reflect your shop’s process, not a universal benchmark. Complex contour cutting, registration, laminating, color matching and tiled installations generally need more allowance than simple rectangular panels.</p><h2>How to interpret the result</h2><p>The finished area tells you what ends up on the job; purchase area adds the planning allowance; roll length translates area into an inventory quantity. If sign width exceeds roll width, the tool warns that panel seams or rotation must be planned separately because simple area division cannot determine the actual cut layout.</p><h2>Assumptions and limitations</h2><p>This does not perform two-dimensional nesting and assumes full roll width can be utilized. Edge margins, printer/cutter pinch rollers, media leader/trailer, laminate, reprints and defects add consumption. Printed jobs may also require bleed beyond the nominal sign size. Use the cutting/RIP software for final media length.</p><h2>Practical example and workflow</h2><p>Ten signs at 1.2 × 0.8 m require 9.6 m² of finished face material. With 12% waste, planned vinyl rises to about 10.75 m². On a 1.37 m roll the area-based estimate is about 7.85 linear metres, before nesting and machine margins are considered.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How much waste should I add for vinyl signage?','Use your own production history. Simple rectangles may need less; contour cuts, tiled panels, registration and reprints can need more.'],['Why is roll length only approximate?','Area divided by roll width assumes perfect use of the full width. Real nesting, margins, orientation and seams can increase linear consumption.'],['What if my sign is wider than the vinyl roll?','Plan multiple panels or rotate the artwork where practical. The calculator flags the issue but does not design seam placement.'],['Does this include laminate?','No. Calculate laminate separately if it has a different roll width, waste rate or coverage requirement.']];
require __DIR__.'/../includes/tool-template.php';
