<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('seo','canonical-tag-checker');ob_start(); ?>
<h2>Check a page's canonical tag from pasted HTML</h2>
<p class="lead">Paste the page URL and HTML source. The tool finds canonical links without fetching or uploading the page.</p>
<div class="form-grid"><div class="field full"><label for="pageUrl">Page URL</label><input id="pageUrl" type="url" value="https://example.com/products/widget"></div><div class="field full"><label for="html">HTML source</label><textarea id="html"><html><head><link rel="canonical" href="https://example.com/products/widget"></head><body></body></html></textarea></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Check Canonical</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Canonical tags found</span><strong id="count">—</strong></div><div class="metric"><span>First canonical URL</span><strong id="canonical">—</strong></div><div class="metric"><span>Matches page URL</span><strong id="match">—</strong></div><div class="metric"><span>Absolute URL</span><strong id="absolute">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function norm(u,base){try{const x=new URL(u,base);x.hash='';let s=x.href;if(x.pathname!=='/'&&s.endsWith('/'))s=s.slice(0,-1);return s;}catch(e){return null;}}function go(){const page=$('pageUrl').value.trim(),html=$('html').value;const doc=new DOMParser().parseFromString(html,'text/html'),links=[...doc.querySelectorAll('link[rel]')].filter(x=>x.rel.toLowerCase().split(/\s+/).includes('canonical'));const href=links[0]?.getAttribute('href')?.trim()||'';const can=href?norm(href,page):null,p=norm(page,page);$('count').textContent=links.length;$('canonical').textContent=href||'None';$('absolute').textContent=can?'Yes':'No / invalid';$('match').textContent=(can&&p)?(can===p?'Yes':'No'):'—';if(links.length===0)note('No canonical link tag was found in the pasted HTML.',true);else if(links.length>1)note('Multiple canonical tags were found. Review the HTML because search engines may ignore conflicting signals.',true);else if(!can)note('A canonical tag exists, but its href could not be resolved as a valid URL.',true);else note(can===p?'The canonical resolves to the same normalized URL as the entered page URL.':'The canonical points to a different normalized URL.');} $('html').addEventListener('input',go);
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>The checker parses the HTML in your browser, finds <code>&lt;link rel="canonical" href="..."&gt;</code> elements, resolves relative URLs against the page URL, and compares the first canonical with the normalized page URL.</p><h2>How to use the result</h2><p>Use it when reviewing rendered or source HTML from templates, migrations or indexation troubleshooting. A self-referencing canonical can clarify the preferred URL, while a cross-canonical intentionally points to another URL.</p><h2>Assumptions and limitations</h2><p>This tool analyzes only the HTML you paste. It does not fetch the live page, inspect HTTP Link headers, determine whether search engines selected the same canonical, or verify indexability. Multiple canonical signals should be investigated in context.</p><h2>Example</h2><p>Paste the exact HTML version you want to test because client-side rendering can change what a browser DOM contains compared with server source.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Does the checker fetch my website?','No. It analyzes only the page URL and HTML you paste into the browser.'],['Are relative canonical URLs supported?','Yes. Relative href values are resolved against the entered page URL.'],['What if there are multiple canonical tags?','The tool counts them and flags the situation for review because conflicting canonical signals can be problematic.'],['Does a matching canonical guarantee Google uses it?','No. Canonical tags are signals; search engines can select a different canonical based on other evidence.']];require __DIR__.'/../includes/tool-template.php';
