<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('seo','core-web-vitals-budget-checker');ob_start(); ?>
<h2>Check Core Web Vitals against your budgets</h2>
<p class="lead">Enter measured field or lab values and the thresholds your team wants to enforce.</p>
<div class="form-grid"><div class="field"><label for="lcp">LCP (seconds)</label><input id="lcp" type="number" value="2.3" step="0.01" min="0"></div><div class="field"><label for="lcpBudget">LCP budget (seconds)</label><input id="lcpBudget" type="number" value="2.5" step="0.01" min="0"></div><div class="field"><label for="inp">INP (milliseconds)</label><input id="inp" type="number" value="180" step="0.01" min="0"></div><div class="field"><label for="inpBudget">INP budget (ms)</label><input id="inpBudget" type="number" value="200" step="0.01" min="0"></div><div class="field"><label for="cls">CLS</label><input id="cls" type="number" value="0.08" step="0.001" min="0"></div><div class="field"><label for="clsBudget">CLS budget</label><input id="clsBudget" type="number" value="0.1" step="0.001" min="0"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Check Budgets</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>LCP status</span><strong id="lcpStatus">—</strong></div><div class="metric"><span>INP status</span><strong id="inpStatus">—</strong></div><div class="metric"><span>CLS status</span><strong id="clsStatus">—</strong></div><div class="metric"><span>Budgets passed</span><strong id="passed">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function status(v,b){return v<=b?'Pass':'Over budget';}function go(){const l=num('lcp'),lb=num('lcpBudget'),i=num('inp'),ib=num('inpBudget'),c=num('cls'),cb=num('clsBudget');if([l,lb,i,ib,c,cb].some(v=>v<0)){note('Metric values and budgets cannot be negative.',true);return;}const a=status(l,lb),d=status(i,ib),e=status(c,cb),pass=[a,d,e].filter(x=>x==='Pass').length;$('lcpStatus').textContent=a;$('inpStatus').textContent=d;$('clsStatus').textContent=e;$('passed').textContent=pass+'/3';note(pass===3?'All entered metrics are within the configured budgets.':'One or more metrics exceed the configured budgets.',pass<3);}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Each entered metric is compared directly with its corresponding budget. A metric passes when the measured value is less than or equal to the budget you set. The tool does not convert between lab and field data or calculate percentiles.</p><h2>How to use the result</h2><p>Use budgets in performance QA to catch regressions before release. Teams can set stricter internal budgets than public guidance, and can maintain different budgets for templates or device classes when appropriate.</p><h2>Assumptions and limitations</h2><p>Core Web Vitals assessment in search and reporting can depend on field data, percentile aggregation, device type and evolving definitions. The defaults are editable reference values, not a promise of current search ranking treatment. Verify official guidance for production policy decisions.</p><h2>Example</h2><p>Treat a budget failure as a prompt to investigate the affected page or template rather than as a complete diagnosis of user experience.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Are the default budgets fixed Google requirements?','No. They are editable reference values. Verify current official guidance and set budgets appropriate to your team.'],['Can I enter PageSpeed Insights field data?','Yes. Enter the metric values you want to compare, but remember that field and lab data are different measurement sources.'],['Does the tool measure my website?','No. It compares values you enter; it does not run a performance test.'],['Can I set stricter budgets?','Yes. Internal performance budgets can be tighter than external thresholds if that supports your product goals.']];require __DIR__.'/../includes/tool-template.php';
