<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('seo','redirect-map-checker');ob_start(); ?>
<h2>Audit a redirect mapping before launch</h2>
<p class="lead">Enter one redirect per line as source URL and destination URL separated by a tab, comma or ->.</p>
<div class="form-grid"><div class="field full"><label for="map">Redirect map</label><textarea id="map">https://example.com/old-a -> https://example.com/new-a
https://example.com/old-b -> https://example.com/old-a</textarea></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Analyze Map</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Valid map rows</span><strong id="rows">—</strong></div><div class="metric"><span>Duplicate sources</span><strong id="duplicates">—</strong></div><div class="metric"><span>Chain links</span><strong id="chains">—</strong></div><div class="metric"><span>Self-redirects</span><strong id="self">—</strong></div><div class="metric"><span>Loops found</span><strong id="loops">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><div class="result-box"><strong>Issues</strong><pre id="issues" class="code-output">—</pre></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function parse(line){let p;if(line.includes('->'))p=line.split('->');else if(line.includes('\t'))p=line.split('\t');else p=line.split(',');if(p.length<2)return null;const a=p[0].trim(),b=p.slice(1).join(',').trim();try{return [new URL(a).href,new URL(b).href];}catch(e){return null;}}function go(){const lines=$('map').value.split(/\r?\n/).filter(x=>x.trim()),pairs=lines.map(parse).filter(Boolean),m=new Map(),dups=[],self=[];for(const [a,b] of pairs){if(m.has(a))dups.push(a);else m.set(a,b);if(a===b)self.push(a);}const chains=[];for(const [a,b] of m)if(m.has(b)&&b!==a)chains.push(a+' -> '+b+' -> '+m.get(b));const loops=new Set();for(const start of m.keys()){let cur=start,seen=[];while(m.has(cur)){if(seen.includes(cur)){const cyc=seen.slice(seen.indexOf(cur)).concat(cur);loops.add(cyc.join(' -> '));break;}seen.push(cur);cur=m.get(cur);if(seen.length>m.size+1)break;}}$('rows').textContent=pairs.length;$('duplicates').textContent=dups.length;$('chains').textContent=chains.length;$('self').textContent=self.length;$('loops').textContent=loops.size;const out=[];if(lines.length!==pairs.length)out.push(`${lines.length-pairs.length} line(s) could not be parsed as absolute source/destination URLs.`);if(dups.length)out.push('Duplicate sources:\n'+[...new Set(dups)].join('\n'));if(self.length)out.push('Self-redirects:\n'+self.join('\n'));if(chains.length)out.push('Redirect chains:\n'+chains.join('\n'));if(loops.size)out.push('Redirect loops:\n'+[...loops].join('\n'));$('issues').textContent=out.length?out.join('\n\n'):'No duplicate sources, self-redirects, chains or loops detected in the parsed map.';note(out.length?'Review the listed redirect-map issues before deployment.':'The parsed redirect map passed these structural checks.',out.length>0);} $('map').addEventListener('input',go);
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>The checker builds a source-to-destination map from the pasted rows. It flags a duplicate when the same source is assigned more than once, a self-redirect when source equals destination, a chain when a destination is also another mapped source, and a loop when traversal returns to an earlier URL.</p><h2>How to use the result</h2><p>Use it before migrations or URL cleanup to reduce avoidable redirect hops and contradictory mappings. Fix loops and duplicate source rules first, then simplify chains so old URLs point as directly as practical to the final destination.</p><h2>Assumptions and limitations</h2><p>This is a static map analysis. It does not request URLs, verify HTTP status codes, detect server-side rules not in the pasted map, or decide whether each destination is the correct SEO replacement. Only absolute URLs are accepted for clear comparison.</p><h2>Example</h2><p>A line such as old-b → old-a becomes a chain when old-a is itself mapped to new-a.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Does this crawl the source and destination URLs?','No. It analyzes the redirect relationships you paste and makes no network requests.'],['What separators are supported?','Use a tab, comma, or -> between the source and destination URL on each line.'],['What is a redirect chain?','It occurs when one mapped destination is also a source that redirects again, creating more than one hop.'],['Why are duplicate sources risky?','Two destinations for the same source can make the intended rule ambiguous or dependent on server rule order.']];require __DIR__.'/../includes/tool-template.php';
