<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('seo','search-console-regex-generator');ob_start(); ?>
<h2>Build Google Search Console regex filters</h2><p class="lead">Turn a list of queries or URLs into a cleaner RE2-compatible regex for Custom (regex) filters.</p>
<div class="form-grid"><div class="field full"><label for="terms">Queries or URLs — one per line</label><textarea id="terms" style="min-height:190px" placeholder="seo tools\nseo tool\nfree seo tools"></textarea></div><div class="field"><label for="matchMode">Filter mode</label><select id="matchMode"><option value="match">Matches regex</option><option value="not">Doesn't match regex</option></select></div><div class="field"><label for="caseMode">Case sensitivity</label><select id="caseMode"><option value="insensitive">Not case-sensitive (default)</option><option value="sensitive">Case-sensitive</option></select></div><div class="field"><label for="anchorMode">Match scope</label><select id="anchorMode"><option value="partial">Partial match</option><option value="full">Full string</option><option value="start">Starts with</option><option value="end">Ends with</option></select></div><div class="field"><label for="dedupe">Normalize input</label><select id="dedupe"><option value="yes">Trim, remove blanks and duplicates</option><option value="no">Keep entered lines</option></select></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="generate" type="button">Generate regex</button><button class="btn btn-secondary" id="copy" type="button">Copy regex</button></div><div class="result-box"><div class="field"><label for="regexOut">Google Search Console regex</label><textarea id="regexOut" readonly style="min-height:115px"></textarea></div><div class="result-grid"><div class="metric"><span>Items</span><strong id="count">0</strong></div><div class="metric"><span>Regex length</span><strong id="length">0</strong></div><div class="metric"><span>Syntax target</span><strong>RE2</strong></div></div></div><div class="notice"><strong>GSC behavior:</strong> Search Console uses RE2 syntax. Its default regex matching is partial and not case-sensitive; use anchors when you need start/end or full-string behavior. citeturn112108search0turn112108search2</div>
<script>(()=>{const $=i=>document.getElementById(i);const esc=s=>String(s).replace(/[\\^$.*+?()[\]{}|]/g,'\\$&');function items(){let a=$('terms').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if($('dedupe').value==='yes')a=[...new Set(a)];return a}function go(){const a=items();if(!a.length){$('regexOut').value='';$('count').textContent='0';$('length').textContent='0';return}let body=a.map(esc).join('|');if(a.length>1)body='(?:'+body+')';const s=$('anchorMode').value;if(s==='full')body='^'+body+'$';else if(s==='start')body='^'+body;else if(s==='end')body=body+'$';if($('caseMode').value==='sensitive')body='(?-i)'+body;$('regexOut').value=body;$('count').textContent=a.length;$('length').textContent=body.length}document.querySelectorAll('#terms,#matchMode,#caseMode,#anchorMode,#dedupe').forEach(x=>x.addEventListener('input',go));$('generate').onclick=go;$('copy').onclick=()=>tkCopy($('regexOut').value);go()})();</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>What this generator creates</h2><p>This tool turns multiple lines into one alternation pattern, escapes regex characters in each entered item, and optionally adds anchors or Search Console's case-sensitive prefix. It is meant for the Custom (regex) filters in the Search results Performance report.</p>
<h2>How to use the regex</h2><ol><li>Paste the queries or page URLs you want to include, one per line.</li><li>Choose whether the filter should match or exclude matches, then set case and scope options.</li><li>Copy the generated expression into the Search Console filter and review the matching rows before drawing conclusions.</li></ol>
<h2>Why RE2 compatibility matters</h2><p>Google Search Console documents RE2 as the regex syntax for its custom filter. That means many regex features used in other engines should not be assumed to work here. This generator stays intentionally simple: escaped literals, alternation, anchors and the documented <code>(?-i)</code> case-sensitive prefix. citeturn112108search0</p>
<h2>Search Console data has limits</h2><p>Query tables can omit anonymized queries and are subject to data truncation, so a regex filter is a way to filter the data Search Console exposes, not a guarantee that every matching query exists in the visible table. citeturn112108search5</p>
<?php $toolContent=ob_get_clean();$faqs=[['Which regex syntax does Search Console use?','Google documents RE2 syntax for the Custom (regex) filters in Search Console.'],['Does Search Console regex match partial text by default?','Yes. Google documents partial matching as the default unless you use anchors such as ^ or $.'],['How do I make a Search Console regex case-sensitive?','Prefix the expression with (?-i), which Google documents for case-sensitive matching.'],['Can this tool create negative lookaheads or other advanced regex features?','No. It intentionally generates simple RE2-compatible patterns instead of features that may not be supported by Search Console.']];require __DIR__.'/../includes/tool-template.php';