<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('developer','json-diff-checker');ob_start(); ?>
<h2>Compare two JSON documents</h2>
<p class="lead">Paste valid JSON on both sides. Objects are compared by key and arrays are compared by index.</p>
<div class="form-grid"><div class="field full"><label for="left">Original JSON</label><textarea id="left">{"name":"ToolboxKart","version":1,"features":["fast","local"]}</textarea></div><div class="field full"><label for="right">Updated JSON</label><textarea id="right">{"name":"ToolboxKart","version":2,"features":["fast","local","private"]}</textarea></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Compare JSON</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Added paths</span><strong id="added">—</strong></div><div class="metric"><span>Removed paths</span><strong id="removed">—</strong></div><div class="metric"><span>Changed paths</span><strong id="changed">—</strong></div><div class="metric"><span>No differences</span><strong id="same">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><div class="result-box"><strong>Diff details</strong><pre id="diff" class="code-output">—</pre></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function eq(a,b){return JSON.stringify(a)===JSON.stringify(b);}function walk(a,b,path,out){if(eq(a,b))return;if(a===undefined){out.added.push(path||'$');return;}if(b===undefined){out.removed.push(path||'$');return;}const ao=a&&typeof a==='object',bo=b&&typeof b==='object';if(!ao||!bo||Array.isArray(a)!==Array.isArray(b)){out.changed.push([path||'$',a,b]);return;}if(Array.isArray(a)){const n=Math.max(a.length,b.length);for(let i=0;i<n;i++)walk(a[i],b[i],`${path||'$'}[${i}]`,out);return;}const keys=new Set([...Object.keys(a),...Object.keys(b)]);for(const k of keys){const p=path?path+'.'+k:'$.'+k;walk(a[k],b[k],p,out);}}function go(){let a,b;try{a=JSON.parse($('left').value);}catch(e){note('Original JSON is invalid: '+e.message,true);return;}try{b=JSON.parse($('right').value);}catch(e){note('Updated JSON is invalid: '+e.message,true);return;}const out={added:[],removed:[],changed:[]};walk(a,b,'',out);$('added').textContent=out.added.length;$('removed').textContent=out.removed.length;$('changed').textContent=out.changed.length;const total=out.added.length+out.removed.length+out.changed.length;$('same').textContent=total===0?'Yes':'No';const lines=[];out.added.forEach(p=>lines.push('+ '+p));out.removed.forEach(p=>lines.push('- '+p));out.changed.forEach(([p,x,y])=>lines.push('~ '+p+'\n  from: '+JSON.stringify(x)+'\n  to:   '+JSON.stringify(y)));$('diff').textContent=lines.length?lines.join('\n'):'No differences found.';note(total===0?'The parsed JSON values are equivalent under this comparison.':'Differences are listed by JSON path. Arrays are compared by index.');} $('left').addEventListener('input',go);$('right').addEventListener('input',go);
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>The checker parses both inputs with the browser's JSON parser, then recursively compares values. Object properties are compared by key, while arrays are compared by index. Added, removed and changed paths are listed separately.</p><h2>How to use the result</h2><p>Use it for API payloads, configuration files, structured data, test fixtures or saved application state. The path-oriented output is designed to show where the parsed structures differ rather than highlighting every textual formatting change.</p><h2>Assumptions and limitations</h2><p>Object key order and whitespace do not count as differences because valid JSON is parsed first. Array order does matter: moving an item to another index can create multiple reported changes. The tool does not apply schema-aware matching or semantic array identity.</p><h2>Example</h2><p>All comparison work runs locally in the browser, so pasted JSON does not need to be uploaded to a server.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Does whitespace affect the diff?','No. Both inputs are parsed as JSON first, so formatting and insignificant whitespace are ignored.'],['Does object key order matter?','No. Object properties are compared by key.'],['How are arrays compared?','Arrays are compared by index, so reordering items can produce changed paths even when the same values are present elsewhere.'],['Does the JSON leave my browser?','No. Parsing and comparison run locally in the page.']];require __DIR__.'/../includes/tool-template.php';
