<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('solar-energy','battery-backup-runtime-calculator');
ob_start();
?>
<h2>Estimate battery backup runtime</h2><p class="lead">Estimate usable battery energy and runtime from voltage, amp-hours, depth of discharge, efficiency and load.</p><div class="notice">Do not use nominal Ah alone to guarantee runtime. For critical backup sizing, use battery/inverter manufacturer discharge curves and system design limits.</div><div class="form-grid"><div class="field"><label for="v">Battery bank nominal voltage (V)</label><input id="v" type="number" value="48" min="0.001" step="any"></div><div class="field"><label for="ah">Battery bank capacity (Ah)</label><input id="ah" type="number" value="100" min="0" step="any"></div><div class="field"><label for="dod">Usable depth of discharge (%)</label><input id="dod" type="number" value="80" min="0" max="100" step="any"></div><div class="field"><label for="eff">Inverter/system efficiency (%)</label><input id="eff" type="number" value="90" min="0.1" max="100" step="any"></div><div class="field"><label for="load">Average AC load (W)</label><input id="load" type="number" value="800" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Nominal battery energy</span><strong id="nominal">—</strong></div><div class="metric"><span>Estimated usable AC energy</span><strong id="usable">—</strong></div><div class="metric"><span>Estimated runtime</span><strong id="runtime">—</strong></div><div class="metric"><span>Approx. DC current at load</span><strong id="current">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('nominal').textContent='—';$('usable').textContent='—';$('runtime').textContent='—';$('current').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const v=num('v'),ah=num('ah'),dod=num('dod')/100,eff=num('eff')/100,l=num('load');if(!(v>0&&ah>=0&&dod>=0&&dod<=1&&eff>0&&eff<=1&&l>0))throw 0;const wh=v*ah,usable=wh*dod*eff,hrs=usable/l,amps=l/(v*eff);$('nominal').textContent=fmt(wh/1000,3)+' kWh';$('usable').textContent=fmt(usable/1000,3)+' kWh';$('runtime').textContent=fmt(hrs,2)+' h';$('current').textContent=fmt(amps,2)+' A';$('note').textContent='This is an energy-balance estimate. Real runtime changes with battery chemistry, discharge rate, temperature, inverter standby draw, aging and BMS cutoffs.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Battery Backup Runtime Calculator works</h2><p>Nominal battery energy is voltage × amp-hours, expressed in watt-hours. The calculator multiplies nominal energy by the allowed depth of discharge and system/inverter efficiency to estimate usable AC energy, then divides by average AC load to estimate runtime. It also approximates DC current needed at the entered load.</p><h2>How to use this battery backup runtime calculator</h2><p>Enter the battery bank’s effective nominal voltage and Ah capacity as configured, not a single battery value if several units form the bank. Set a usable depth-of-discharge appropriate to the battery/BMS design and an inverter/system efficiency representative of your load range. Use average load rather than only nameplate peak power.</p><h2>How to interpret the result</h2><p>Runtime is an energy estimate. A 4.8 kWh nominal battery bank is not the same as 4.8 kWh delivered to AC loads because reserve/DoD limits and conversion losses reduce usable energy. The result is useful for scenario planning and comparing load reductions, but it should not be treated as a guaranteed outage duration.</p><h2>Assumptions and limitations</h2><p>Battery capacity can fall at high discharge rates, low temperature and with aging. Lead-acid batteries are especially affected by discharge-rate behavior; lithium systems may have BMS reserve/cutoffs. Inverter standby consumption, surge loads and battery voltage variation are also omitted. Critical systems need manufacturer curves and engineered design.</p><h2>Practical example and workflow</h2><p>A 48 V, 100 Ah bank has 4.8 kWh nominal energy. At 80% usable DoD and 90% system efficiency, estimated AC energy is about 3.46 kWh. An 800 W average load therefore gives roughly 4.32 hours in the simplified model before real-world derating.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How do I convert battery Ah to Wh?','Multiply the battery-bank voltage by amp-hours: Wh = V × Ah.'],['Why multiply by depth of discharge?','Many systems intentionally reserve part of nominal capacity to protect the battery or meet BMS limits, so not all nominal energy is usable.'],['Why can actual runtime be lower?','Battery aging, temperature, discharge rate, inverter losses, standby draw and cutoff voltage can all reduce delivered energy.'],['Can I size critical backup from this result alone?','No. Use manufacturer discharge data, surge requirements, redundancy and professional design for critical loads.']];
require __DIR__.'/../includes/tool-template.php';
