<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('solar-energy','electricity-bill-savings-calculator');
ob_start();
?>
<h2>Estimate electricity bill savings</h2><p class="lead">Estimate monthly and annual bill savings from reduced grid import and credited exported energy using editable tariffs.</p><div class="notice">NREL PVWatts can estimate PV energy production; this calculator starts after you already have an estimated monthly kWh offset and applies simple import/export energy rates.</div><div class="form-grid"><div class="field"><label for="baseline">Baseline grid consumption (kWh/month)</label><input id="baseline" type="number" value="900" min="0" step="any"></div><div class="field"><label for="offset">On-site generation / efficiency offset (kWh/month)</label><input id="offset" type="number" value="500" min="0" step="any"></div><div class="field"><label for="self">Offset used to reduce imports (%)</label><input id="self" type="number" value="80" min="0" max="100" step="any"></div><div class="field"><label for="tariff">Grid energy tariff per kWh</label><input id="tariff" type="number" value="8" min="0" step="any"></div><div class="field"><label for="export">Export credit per kWh</label><input id="export" type="number" value="3" min="0" step="any"></div><div class="field"><label for="fixed">Monthly fixed charges unaffected</label><input id="fixed" type="number" value="300" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Baseline energy + fixed bill</span><strong id="before">—</strong></div><div class="metric"><span>Estimated bill after offset</span><strong id="after">—</strong></div><div class="metric"><span>Monthly savings</span><strong id="save">—</strong></div><div class="metric"><span>Annual savings</span><strong id="annual">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('before').textContent='—';$('after').textContent='—';$('save').textContent='—';$('annual').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const b=num('baseline'),o=num('offset'),s=num('self')/100,t=num('tariff'),e=num('export'),f=num('fixed');if(!(b>=0&&o>=0&&s>=0&&s<=1&&t>=0&&e>=0&&f>=0))throw 0;const selfk=Math.min(b,o*s),exp=Math.max(0,o-selfk),before=b*t+f,after=(b-selfk)*t+f-exp*e,save=before-after;$('before').textContent=fmt(before,2);$('after').textContent=fmt(after,2);$('save').textContent=fmt(save,2);$('annual').textContent=fmt(save*12,2);$('note').textContent='Tariff structures can include slabs, demand charges, taxes, time-of-use pricing and export limits. Enter rates that match your actual billing rules.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Electricity Bill Savings Calculator works</h2><p>The calculator separates energy that directly reduces grid imports from surplus energy credited as export. Self-used offset is valued at the entered retail tariff, while export is valued at the entered export credit. Fixed monthly charges are included before and after because they may remain payable even when energy imports fall.</p><h2>How to use this electricity bill savings calculator</h2><p>Enter a representative baseline monthly consumption, the expected monthly energy offset from solar or efficiency, the percentage used behind the meter, retail energy price, export-credit rate and unaffected fixed charges. Use actual tariff rules from the utility rather than assuming export electricity is worth the retail rate.</p><h2>How to interpret the result</h2><p>Monthly savings are the difference between the simplified baseline and post-offset bill. If export credit is lower than the retail tariff, increasing self-consumption can be more valuable than exporting the same kWh. The model therefore makes the self-consumption share explicit instead of using only annual generation.</p><h2>Assumptions and limitations</h2><p>Real tariffs may include tier/slab pricing, demand charges, time-of-use rates, taxes, minimum bills, net-metering periods and export caps. Solar production also varies by season; NREL PVWatts is designed to estimate energy production from PV system inputs. This calculator does not forecast generation or utility policy changes.</p><h2>Practical example and workflow</h2><p>If a site uses 900 kWh/month and generates/offsets 500 kWh, with 80% self-used, 400 kWh reduces imports and 100 kWh may be exported. At different retail and export rates, the tool shows why 500 kWh of generation does not necessarily save 500 × retail tariff.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does every solar kWh save the retail electricity rate?','No. Self-consumed energy may offset retail purchases, while exported energy may receive a different credit depending on the tariff.'],['Why include fixed charges?','Some bill components do not fall when kWh consumption falls, so excluding them can overstate the bill reduction.'],['Does this estimate solar production?','No. Use a system-production model such as NREL PVWatts or measured data, then enter the expected kWh offset here.'],['Can this model slab or time-of-use tariffs?','Not directly. Use an average effective rate only for rough planning or build a tariff-specific interval model for precise billing.']];
require __DIR__.'/../includes/tool-template.php';
