<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('solar-energy','inverter-capacity-calculator');
ob_start();
?>
<h2>Estimate inverter capacity from connected loads</h2><p class="lead">Calculate continuous load, recommended inverter headroom and surge requirement from user-entered loads.</p><div class="notice">This is load-side inverter sizing. PV array DC/AC sizing uses different design considerations; NREL PVWatts treats DC/AC ratio as a separate system input.</div><div class="form-grid"><div class="field"><label for="run">Simultaneous continuous load (W)</label><input id="run" type="number" value="2500" min="0" step="any"></div><div class="field"><label for="surge">Additional startup surge above running load (W)</label><input id="surge" type="number" value="1500" min="0" step="any"></div><div class="field"><label for="head">Continuous headroom (%)</label><input id="head" type="number" value="25" min="0" step="any"></div><div class="field"><label for="pf">Worst-case power factor for VA estimate</label><input id="pf" type="number" value="0.9" min="0.1" max="1" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Recommended continuous W rating</span><strong id="watts">—</strong></div><div class="metric"><span>Approx. continuous VA</span><strong id="va">—</strong></div><div class="metric"><span>Minimum short surge W</span><strong id="surgew">—</strong></div><div class="metric"><span>Headroom multiplier</span><strong id="ratio">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('watts').textContent='—';$('va').textContent='—';$('surgew').textContent='—';$('ratio').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const r=num('run'),s=num('surge'),h=num('head')/100,pf=num('pf');if(!(r>=0&&s>=0&&h>=0&&pf>0&&pf<=1))throw 0;const cont=r*(1+h),va=cont/pf,surge=r+s;$('watts').textContent=fmt(cont,0)+' W';$('va').textContent=fmt(va,0)+' VA';$('surgew').textContent=fmt(surge,0)+' W';$('ratio').textContent=fmt(1+h,2)+'×';$('note').textContent='Verify both continuous and short-duration surge ratings on the inverter datasheet. Motor/compressor startup and waveform requirements can dominate sizing.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Inverter Capacity Calculator works</h2><p>For backup/load-side sizing, the first requirement is simultaneous continuous real power. The calculator adds a configurable headroom percentage to that running load and divides by the entered power factor to provide a rough VA requirement. Startup surge is reported separately as running load plus additional surge watts.</p><h2>How to use this inverter capacity calculator</h2><p>List or measure loads that may run at the same time and enter their combined watts. Add surge above running watts for motors, pumps, compressors or other high-inrush equipment. Choose conservative headroom and power factor based on equipment/inverter documentation rather than treating the defaults as universal engineering standards.</p><h2>How to interpret the result</h2><p>An inverter must satisfy both continuous and surge requirements. A unit with adequate continuous watts can still trip if its surge duration/rating is insufficient. Conversely, oversizing solely for a brief inrush may not be necessary if the inverter has a documented short-duration surge capability that matches the load.</p><h2>Assumptions and limitations</h2><p>Real sizing must consider DC battery voltage/current, wiring, ambient temperature derating, inverter efficiency, waveform compatibility, neutral/grounding, code requirements and load diversity. For grid-tied PV, array-to-inverter DC/AC ratio is a separate design topic; NREL PVWatts exposes DC/AC ratio and inverter efficiency as system parameters.</p><h2>Practical example and workflow</h2><p>With 2,500 W of simultaneous running load and 25% headroom, the continuous planning target is about 3,125 W. At power factor 0.9 that corresponds to roughly 3,472 VA. If startup adds another 1,500 W, the inverter must also tolerate about 4,000 W for the required surge duration.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How much inverter headroom should I use?','Use manufacturer/system-design guidance and your actual load profile. The tool keeps headroom editable because one percentage is not universal.'],['Why are watts and VA different?','Watts measure real power; VA is apparent power. With power factor below 1, the VA requirement is higher than real watts.'],['How do I size for a refrigerator or motor?','Include documented startup/inrush surge and verify the inverter’s surge power and duration, not only its continuous rating.'],['Is this the same as solar DC/AC ratio sizing?','No. This tool sizes an inverter for loads; PV array DC/AC design is a separate grid-tied system calculation.']];
require __DIR__.'/../includes/tool-template.php';
