<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('ecommerce','ean-upc-check-digit-calculator');ob_start(); ?>
<h2>Calculate or validate barcode check digits</h2>
<p class="lead">Choose the barcode format and enter the numeric data digits or a complete barcode.</p>
<div class="form-grid"><div class="field"><label for="format">Barcode format</label><select id="format"><option value="EAN13" selected>EAN-13</option><option value="UPCA">UPC-A</option><option value="EAN8">EAN-8</option></select></div><div class="field full"><label for="digits">Digits</label><input id="digits" type="text" value="400638133393"><small>For calculation: EAN-13 uses 12 data digits, UPC-A 11, EAN-8 7. You may also enter the complete code to validate.</small></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Check / Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Calculated check digit</span><strong id="check">—</strong></div><div class="metric"><span>Complete barcode</span><strong id="complete">—</strong></div><div class="metric"><span>Validation</span><strong id="valid">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function checkDigit(data){let sum=0,rev=[...data].reverse();rev.forEach((ch,i)=>sum+=(+ch)*(i%2===0?3:1));return String((10-(sum%10))%10);}function go(){const fmt=$('format').value,s=$('digits').value.replace(/\s+/g,'');const lens={EAN13:[12,13],UPCA:[11,12],EAN8:[7,8]}[fmt];if(!/^\d+$/.test(s)||!lens.includes(s.length)){note(`Enter ${lens[0]} data digits to calculate or ${lens[1]} digits to validate ${fmt}.`,true);$('check').textContent=$('complete').textContent=$('valid').textContent='—';return;}if(s.length===lens[0]){const cd=checkDigit(s);$('check').textContent=cd;$('complete').textContent=s+cd;$('valid').textContent='Calculated';note('Check digit calculated using the standard alternating 3/1 weighting from the right.');}else{const data=s.slice(0,-1),cd=checkDigit(data),ok=cd===s.slice(-1);$('check').textContent=cd;$('complete').textContent=s;$('valid').textContent=ok?'Valid':'Invalid';note(ok?'The supplied check digit matches.':'The supplied check digit does not match the calculated value.',!ok);}}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>UPC-A, EAN-8 and EAN-13 use a modulo-10 check digit. Starting from the rightmost data digit, the algorithm applies alternating weights of 3 and 1, sums the weighted digits, and chooses the final digit that makes the total a multiple of 10.</p><h2>How to use the result</h2><p>Use calculation mode before creating a barcode from an assigned company/product number, or paste a full code to catch typing errors. A valid check digit verifies arithmetic consistency only; it does not prove that a number has been legitimately assigned.</p><h2>Assumptions and limitations</h2><p>The tool does not query GS1 or any product registry. It cannot verify ownership, allocation, product identity or barcode print quality. Leading zeros are preserved because the input is handled as text.</p><h2>Example</h2><p>The format selector avoids the ambiguity of a 12-digit value, which could otherwise be interpreted as a complete UPC-A or as the data portion of an EAN-13.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Can this verify who owns a UPC or EAN?','No. It validates only the mathematical check digit and does not query GS1 assignment records.'],['Why do I need to choose a format?','The expected data length differs by format, and 12 digits can have different meanings depending on whether you are using UPC-A or EAN-13.'],['Are leading zeros supported?','Yes. The digits are processed as text so leading zeros are not removed.'],['Does a valid check digit mean the barcode will scan?','Not necessarily. Printing, sizing, quiet zones and encoding quality also affect scanning.']];require __DIR__.'/../includes/tool-template.php';
