<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('ecommerce','landed-cost-calculator');ob_start(); ?>
<h2>Estimate true landed unit cost</h2>
<p class="lead">Combine purchase cost with shipment-level charges before evaluating selling price or margin.</p>
<div class="form-grid"><div class="field"><label for="units">Units in shipment</label><input id="units" type="number" value="500" step="1" min="1"></div><div class="field"><label for="unitCost">Product cost per unit</label><input id="unitCost" type="number" value="250" step="0.01" min="0"></div><div class="field"><label for="freight">Freight & insurance</label><input id="freight" type="number" value="20000" step="0.01" min="0"></div><div class="field"><label for="duty">Duty / import charges</label><input id="duty" type="number" value="10000" step="0.01" min="0"></div><div class="field"><label for="tax">Non-recoverable taxes</label><input id="tax" type="number" value="0" step="0.01" min="0"></div><div class="field"><label for="other">Other shipment costs</label><input id="other" type="number" value="5000" step="0.01" min="0"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Goods cost</span><strong id="goods">—</strong></div><div class="metric"><span>Shipment charges</span><strong id="charges">—</strong></div><div class="metric"><span>Total landed shipment cost</span><strong id="total">—</strong></div><div class="metric"><span>Landed cost per unit</span><strong id="perUnit">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const u=num('units'),uc=num('unitCost'),f=num('freight'),d=num('duty'),t=num('tax'),o=num('other');if(u<=0||[uc,f,d,t,o].some(v=>v<0)){note('Units must be positive and cost inputs cannot be negative.',true);return;}const g=u*uc,ch=f+d+t+o,tot=g+ch;$('goods').textContent=money(g,'');$('charges').textContent=money(ch,'');$('total').textContent=money(tot,'');$('perUnit').textContent=money(tot/u,'');note('Include only taxes or charges that are true economic costs to your business.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Goods cost = units × product cost per unit. Shipment charges are freight, duty, non-recoverable taxes and other entered costs. Total landed cost is goods cost plus shipment charges, and landed cost per unit divides that total by the number of units.</p><h2>How to use the result</h2><p>Use landed cost rather than supplier price alone when setting marketplace prices, planning reorder quantities or comparing sourcing options. It makes shipment-level costs visible at the unit level.</p><h2>Assumptions and limitations</h2><p>Actual import duty and tax treatment depends on product classification, origin, destination and business tax status. Recoverable credits should generally not be treated as permanent cost. This calculator does not determine customs classification or tax liability.</p><h2>Example</h2><p>Changing shipment size can materially change per-unit landed cost because fixed freight and handling costs are spread across more or fewer units.</p>
<?php $toolContent=ob_get_clean();$faqs=[['What costs belong in landed cost?','Typically product cost plus freight, insurance, duty, non-recoverable taxes, customs or handling charges and other costs needed to bring inventory to its usable location.'],['Should recoverable GST or VAT be included?','Usually only if it is an economic cost to you. Confirm treatment with your accounting or tax process.'],['Why enter shipment units?','Shipment-level charges are divided by units so you can estimate a comparable landed cost per item.'],['Does this calculate customs duty automatically?','No. Enter a duty amount that you have calculated or verified for the shipment.']];require __DIR__.'/../includes/tool-template.php';
