<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('ecommerce','return-rate-profit-impact-calculator');ob_start(); ?>
<h2>Model return-rate impact</h2>
<p class="lead">Enter order economics and expected return behaviour to see how much contribution may be lost.</p>
<div class="form-grid"><div class="field"><label for="orders">Orders</label><input id="orders" type="number" value="1000" step="1" min="0"></div><div class="field"><label for="price">Average order revenue</label><input id="price" type="number" value="1500" step="0.01" min="0"></div><div class="field"><label for="cost">Product / fulfilment cost per order</label><input id="cost" type="number" value="900" step="0.01" min="0"></div><div class="field"><label for="returnRate">Return rate (%)</label><input id="returnRate" type="number" value="10" step="0.01" min="0" max="100"></div><div class="field"><label for="returnCost">Extra processing cost per returned order</label><input id="returnCost" type="number" value="150" step="0.01" min="0"></div><div class="field"><label for="recovery">Value recovered from returned goods (%)</label><input id="recovery" type="number" value="80" step="0.01" min="0" max="100"><small>Approximate share of product cost recoverable through restocking/resale.</small></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Returned orders</span><strong id="returns">—</strong></div><div class="metric"><span>Retained sales revenue</span><strong id="retainedRevenue">—</strong></div><div class="metric"><span>Contribution before returns</span><strong id="baseProfit">—</strong></div><div class="metric"><span>Contribution after return impact</span><strong id="afterProfit">—</strong></div><div class="metric"><span>Estimated contribution loss</span><strong id="loss">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const o=num('orders'),p=num('price'),c=num('cost'),r=num('returnRate')/100,rc=num('returnCost'),rec=num('recovery')/100;if([o,p,c,rc].some(v=>v<0)||r<0||r>1||rec<0||rec>1){note('Check that amounts are non-negative and percentage inputs are between 0% and 100%.',true);return;}const ret=o*r,kept=o-ret,base=o*(p-c);const returnedLoss=ret*(c*(1-rec)+rc);const after=kept*(p-c)-returnedLoss;$('returns').textContent=dec(ret,0);$('retainedRevenue').textContent=money(kept*p,'');$('baseProfit').textContent=money(base,'');$('afterProfit').textContent=money(after,'');$('loss').textContent=money(base-after,'');note('Model assumes returned orders refund revenue and applies the entered recovery rate to product/fulfilment cost.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>The model separates kept orders from returned orders. Kept orders retain their normal contribution. Returned orders are assumed to refund their sale revenue, incur the entered return-processing cost, and recover only the chosen share of product/fulfilment cost through resale or restocking.</p><h2>How to use the result</h2><p>Use the result to compare products, channels or policies with different return rates. A seemingly healthy front-end margin can weaken when return shipping, inspection, damage, repackaging and unrecoverable inventory are material.</p><h2>Assumptions and limitations</h2><p>This is a planning model rather than a full accounting statement. Real returns may involve partial refunds, exchanges, non-refundable shipping, marketplace fee reversals, taxes, varying recovery values and repeat-purchase effects.</p><h2>Example</h2><p>Try the same order economics at several return rates to see how sensitive contribution is to return behaviour.</p>
<?php $toolContent=ob_get_clean();$faqs=[['What does recovery rate mean?','It is the share of the entered product/fulfilment cost you expect to recover when a returned item can be restocked, resold or otherwise recovered.'],['Does the model include exchanges?','Not separately. Treat an exchange according to the economics you want to model or use return rate as an approximation.'],['Why can return losses exceed refunded revenue?','Returns can also create processing costs and unrecoverable inventory cost.'],['Can I compare channels with this tool?','Yes. Use channel-specific return rates and order economics in separate calculations.']];require __DIR__.'/../includes/tool-template.php';
