<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('ecommerce','shipping-dimensional-weight-calculator');ob_start(); ?>
<h2>Compare actual and dimensional shipping weight</h2>
<p class="lead">Enter package dimensions, actual weight and the divisor specified by your carrier or service.</p>
<div class="form-grid"><div class="field"><label for="system">Measurement system</label><select id="system"><option value="metric" selected>Metric: cm / kg</option><option value="imperial">Imperial: in / lb</option></select></div><div class="field"><label for="length">Length</label><input id="length" type="number" value="40" step="0.01" min="0"></div><div class="field"><label for="width">Width</label><input id="width" type="number" value="30" step="0.01" min="0"></div><div class="field"><label for="height">Height</label><input id="height" type="number" value="20" step="0.01" min="0"></div><div class="field"><label for="actual">Actual weight</label><input id="actual" type="number" value="3" step="0.01" min="0"></div><div class="field"><label for="divisor">DIM divisor</label><input id="divisor" type="number" value="5000" step="0.01" min="0.0001"><small>Use the carrier/service divisor that matches your units.</small></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Package volume</span><strong id="volume">—</strong></div><div class="metric"><span>Dimensional weight</span><strong id="dim">—</strong></div><div class="metric"><span>Higher comparison weight</span><strong id="billable">—</strong></div><div class="metric"><span>Likely weight basis</span><strong id="basis">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const sys=$('system').value,l=num('length'),w=num('width'),h=num('height'),a=num('actual'),d=num('divisor');if([l,w,h,a].some(v=>v<0)||d<=0){note('Dimensions and weight cannot be negative, and divisor must be positive.',true);return;}const vol=l*w*h,dw=vol/d,b=Math.max(a,dw),unit=sys==='metric'?'kg':'lb',vu=sys==='metric'?'cm³':'in³';$('volume').textContent=dec(vol,2)+' '+vu;$('dim').textContent=dec(dw,3)+' '+unit;$('billable').textContent=dec(b,3)+' '+unit;$('basis').textContent=dw>a?'Dimensional':'Actual';note('Carriers may round dimensions/weight and may use different divisors by service.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Dimensional weight = length × width × height ÷ carrier divisor. The calculator then compares dimensional weight with actual scale weight and displays the larger value as the comparison weight.</p><h2>How to use the result</h2><p>Use the divisor and rounding rules published for the exact carrier, country and service. The tool is especially useful for bulky but light items where package volume can drive shipping charges.</p><h2>Assumptions and limitations</h2><p>Carrier billing rules can include dimension rounding, minimum billable weights, oversize surcharges, packaging rules and zone-specific pricing. This calculator does not quote freight charges; it only calculates the dimensional-weight comparison using your divisor.</p><h2>Example</h2><p>If a box measures 40 × 30 × 20 cm and the divisor is 5,000, dimensional weight is 4.8 kg. If actual weight is 3 kg, dimensional weight is higher.</p>
<?php $toolContent=ob_get_clean();$faqs=[['What DIM divisor should I use?','Use the divisor published by the carrier and service you are shipping with. It can vary by market and service level.'],['Is dimensional weight always the billed weight?','Not necessarily. It is commonly compared with actual weight, but carriers can apply additional rules and surcharges.'],['Why is the divisor editable?','There is no single universal divisor across all carriers, services and measurement systems.'],['Does this calculate shipping price?','No. It calculates dimensional weight and the higher comparison weight only.']];require __DIR__.'/../includes/tool-template.php';
