<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('telecom-networking','bandwidth-calculator');
ob_start();
?>
<h2>Calculate network bandwidth requirement</h2><p class="lead">Estimate total throughput requirement from concurrent users and per-user demand, with overhead and file-transfer context.</p><div class="notice">This calculator uses decimal networking units: 1 Gbps = 1,000 Mbps and 1 byte = 8 bits. Real throughput is lower than link rate because protocols and contention consume capacity.</div><div class="form-grid"><div class="field"><label for="users">Concurrent users / streams</label><input id="users" type="number" value="50" min="0" step="any"></div><div class="field"><label for="per">Average Mbps per user / stream</label><input id="per" type="number" value="3" min="0" step="any"></div><div class="field"><label for="over">Protocol / growth headroom (%)</label><input id="over" type="number" value="25" min="0" step="any"></div><div class="field"><label for="file">Optional file size (GB)</label><input id="file" type="number" value="5" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Raw aggregate demand</span><strong id="raw">—</strong></div><div class="metric"><span>Bandwidth with headroom</span><strong id="recommended">—</strong></div><div class="metric"><span>Equivalent Gbps</span><strong id="gbps">—</strong></div><div class="metric"><span>Entered file transfer time at recommended rate</span><strong id="transfer">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('raw').textContent='—';$('recommended').textContent='—';$('gbps').textContent='—';$('transfer').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const u=num('users'),p=num('per'),o=num('over')/100,f=num('file');if(!(u>=0&&p>=0&&o>=0&&f>=0))throw 0;const raw=u*p,bw=raw*(1+o),sec=bw>0?f*8*1000/bw:Infinity;$('raw').textContent=fmt(raw,2)+' Mbps';$('recommended').textContent=fmt(bw,2)+' Mbps';$('gbps').textContent=fmt(bw/1000,4)+' Gbps';$('transfer').textContent=Number.isFinite(sec)?fmt(sec/60,2)+' min':'Unavailable';$('note').textContent='Bandwidth is a rate, not a guarantee of application performance. Latency, packet loss, Wi-Fi airtime, traffic bursts and provider contention also matter.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Bandwidth Calculator works</h2><p>Aggregate bandwidth demand is concurrent users or streams × average Mbps per user. The calculator then adds a configurable headroom percentage for growth, bursts and protocol overhead. It uses decimal networking units, so 1 Gbps = 1,000 Mbps. File-transfer time converts gigabytes to gigabits and divides by the available Mbps rate.</p><h2>How to use this bandwidth calculator</h2><p>Enter truly concurrent demand, not total registered users. Estimate per-user bandwidth from the actual workload—voice, HD video, cloud desktop, backup or file transfer—and use a separate peak category when workloads differ materially. Add headroom based on observed peaks and service-quality requirements rather than blindly applying one benchmark.</p><h2>How to interpret the result</h2><p>The raw aggregate number is the theoretical application demand before headroom. The recommended figure is a planning capacity under the entered assumptions, not a guarantee. A 1 Gbps access link can deliver less usable application throughput after Ethernet/IP/TCP/VPN overhead, contention and provider/network conditions.</p><h2>Assumptions and limitations</h2><p>Bandwidth does not capture latency, jitter, packet loss, Wi-Fi airtime, duplex limitations or traffic shaping. Voice/video can perform poorly on a high-bandwidth link if latency or loss is high. File transfers may also be limited by server, storage or TCP behavior. Use measured utilization and QoS data for production design.</p><h2>Practical example and workflow</h2><p>Fifty concurrent streams averaging 3 Mbps create 150 Mbps raw demand. Adding 25% headroom raises the planning target to 187.5 Mbps. The file-transfer estimate then shows approximately how long a selected data size would take at that idealized sustained rate, making rate-versus-volume easier to understand.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How do I calculate bandwidth for multiple users?','Multiply concurrent users by average Mbps per user, then add appropriate headroom for bursts and growth.'],['Is 1 Gbps equal to 1,000 or 1,024 Mbps?','Networking link rates are normally expressed in decimal SI units, so 1 Gbps = 1,000 Mbps.'],['Why is real file transfer slower than the calculator?','Protocol overhead, congestion, latency, server/storage limits and Wi-Fi/network contention reduce application throughput.'],['Does more bandwidth fix latency?','No. Bandwidth and latency are different network characteristics; a high-capacity link can still have poor latency or packet loss.']];
require __DIR__.'/../includes/tool-template.php';
