<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('finance','cagr-xirr-calculator');
ob_start();
?>
<h2>Calculate CAGR and XIRR</h2><p class="lead">Use CAGR for simple start-to-end growth and XIRR when cash flows occur on irregular dates.</p>
<h3>CAGR</h3><div class="form-grid"><div class="field"><label for="start">Starting value</label><input id="start" type="number" min="0" step="any" value="100000"></div><div class="field"><label for="end">Ending value</label><input id="end" type="number" min="0" step="any" value="150000"></div><div class="field"><label for="years">Years</label><input id="years" type="number" min="0.0001" step="any" value="3"></div></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>CAGR</span><strong id="cagr">—</strong></div><div class="metric"><span>Total growth</span><strong id="growth">—</strong></div><div class="metric"><span>Growth multiple</span><strong id="multiple">—</strong></div></div></div>
<h3 style="margin-top:24px">XIRR from irregular cash flows</h3><p class="helper">Enter one ISO date and one cash flow per line: <code>YYYY-MM-DD, amount</code>. Investments/outflows should be negative; receipts/inflows positive.</p>
<div class="field full"><label for="flows">Dated cash flows</label><textarea id="flows">2023-01-01,-100000\n2023-09-15,-20000\n2024-07-01,30000\n2026-01-01,140000</textarea></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated XIRR</span><strong id="xirr">—</strong></div><div class="metric"><span>Cash-flow count</span><strong id="count">—</strong></div><div class="metric"><span>Net cash flow</span><strong id="net">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value);function npv(rate,arr){const d0=arr[0].d;return arr.reduce((s,x)=>s+x.v/Math.pow(1+rate,(x.d-d0)/86400000/365),0)}function xirr(arr){let grid=[];for(let x=-0.9999;x<=10;x+=x<1?0.02:0.2)grid.push(x);grid.push(20,50,100,250,500,1000);let a=null,b=null,fa=null;for(const r of grid){const f=npv(r,arr);if(!Number.isFinite(f))continue;if(f===0)return r;if(fa!==null&&f*fa<0){a=prev;b=r;break;}prev=r;fa=f;}if(a===null)return null;let l=a,h=b,fl=npv(l,arr);for(let i=0;i<160;i++){const m=(l+h)/2,fm=npv(m,arr);if(Math.abs(fm)<1e-8)return m;if(fl*fm<=0){h=m}else{l=m;fl=fm}}return(l+h)/2}
function go(){const s=n('start'),e=n('end'),y=n('years');if(Number.isFinite(s)&&Number.isFinite(e)&&Number.isFinite(y)&&s>0&&e>=0&&y>0){const c=Math.pow(e/s,1/y)-1;$('cagr').textContent=(c*100).toFixed(2)+'%';$('growth').textContent=((e/s-1)*100).toFixed(2)+'%';$('multiple').textContent=(e/s).toFixed(3)+'×'}else{$('cagr').textContent=$('growth').textContent=$('multiple').textContent='—'}let arr=[],bad=false;for(const line of $('flows').value.split(/\n+/)){if(!line.trim())continue;const p=line.split(',');if(p.length<2){bad=true;continue}const d=new Date(p[0].trim()+'T00:00:00Z'),v=parseFloat(p.slice(1).join(',').trim());if(!Number.isFinite(d.getTime())||!Number.isFinite(v)){bad=true;continue}arr.push({d:d.getTime(),v});}arr.sort((a,b)=>a.d-b.d);$('count').textContent=arr.length.toString();$('net').textContent=arr.reduce((s,x)=>s+x.v,0).toLocaleString(undefined,{maximumFractionDigits:2});if(arr.length<2||!arr.some(x=>x.v<0)||!arr.some(x=>x.v>0)){$('xirr').textContent='—';$('note').textContent='XIRR needs at least one negative and one positive dated cash flow.';$('note').className='helper danger';return;}const r=xirr(arr);$('xirr').textContent=r===null?'No root found':(r*100).toFixed(3)+'%';$('note').textContent=(bad?'Some malformed lines were ignored. ':'')+(r===null?'The cash-flow pattern may have no XIRR in the search range or may have multiple roots.':'XIRR is the annualized rate that makes the dated cash flows have approximately zero net present value using a 365-day year.');$('note').className='helper'+((bad||r===null)?' danger':'');}
['start','end','years','flows'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('start').value=100000;$('end').value=150000;$('years').value=3;$('flows').value='2023-01-01,-100000\n2023-09-15,-20000\n2024-07-01,30000\n2026-01-01,140000';go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>CAGR versus XIRR: which growth rate should you use?</h2><p><strong>CAGR</strong> is appropriate when you only need the constant annual growth rate connecting one starting value to one ending value over a known number of years. <strong>XIRR</strong> is more appropriate when money moves in and out on irregular dates.</p>
<h2>CAGR formula</h2><p>CAGR = (ending value ÷ starting value)<sup>1/years</sup> − 1. CAGR smooths the path into one annual rate, so it does not describe volatility between the start and end dates.</p>
<h2>How this XIRR calculator works</h2><p>The XIRR engine discounts each cash flow according to the number of days from the earliest date and searches for a rate that makes net present value approximately zero. Microsoft documents XIRR as an annualized internal rate of return for irregular cash flows using a 365-day year and requiring at least one positive and one negative cash flow. <a href="https://support.microsoft.com/en-us/excel/functions/xirr-function" target="_blank" rel="noopener">Microsoft XIRR reference</a>.</p>
<h2>Interpretation and limitations</h2><p>XIRR can be misleading when a cash-flow series has more than one mathematical solution, and it should not be treated as a forecast. CAGR and XIRR are historical/analytical measures; neither accounts for risk, taxes, fees or inflation unless those effects are included in the cash flows themselves.</p>
<h3>Input sign convention</h3><p>Enter investments, purchases and other cash outflows as negative values. Enter distributions, sale proceeds and other inflows as positive values. Use actual dates for irregular flows.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the difference between CAGR and XIRR?','CAGR uses only a starting value, ending value and elapsed years. XIRR uses the timing and amount of every dated cash flow, so it is better suited to irregular contributions and withdrawals.'],['Why does XIRR require positive and negative cash flows?','An internal rate of return is a discount rate that balances outflows and inflows. Without at least one value of each sign, there is no rate that crosses a zero net present value in the usual sense.'],['Can XIRR have more than one answer?','Yes. Certain non-conventional cash-flow patterns can produce multiple mathematical roots. This calculator reports the first sign-change root it finds and flags cases where it cannot find one.'],['Is CAGR the same as average annual return?','No. CAGR is the constant compounded rate connecting start and end values. A simple arithmetic average of yearly returns can differ materially.'],['Does this calculator provide investment advice?','No. It performs mathematical return calculations only and does not evaluate suitability, risk, tax treatment or future performance.']];
require __DIR__.'/../includes/tool-template.php';
