<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('finance','sip-investment-growth-calculator');
ob_start();
?>
<h2>Project SIP investment growth</h2><p class="lead">Model recurring monthly contributions with an editable annual return and optional yearly contribution step-up.</p>
<div class="form-grid"><div class="field"><label for="initial">Initial investment</label><input id="initial" type="number" min="0" step="any" value="10000"></div><div class="field"><label for="monthly">Monthly contribution</label><input id="monthly" type="number" min="0" step="any" value="500"></div><div class="field"><label for="rate">Assumed annual return (%)</label><input id="rate" type="number" step="any" value="8"></div><div class="field"><label for="years">Investment period (years)</label><input id="years" type="number" min="0" step="any" value="10"></div><div class="field"><label for="step">Annual contribution step-up (%)</label><input id="step" type="number" min="0" step="any" value="5"></div><div class="field"><label for="timing">Contribution timing</label><select id="timing"><option value="end">End of each month</option><option value="begin">Beginning of each month</option></select></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate growth</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Projected value</span><strong id="fv">—</strong></div><div class="metric"><span>Total contributed</span><strong id="invested">—</strong></div><div class="metric"><span>Estimated growth</span><strong id="gain">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value),fmt=v=>v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});function go(){const initial=n('initial'),base=n('monthly'),rate=n('rate'),years=n('years'),step=n('step');if(![initial,base,rate,years,step].every(Number.isFinite)||initial<0||base<0||years<0||step<0||rate<=-100){$('note').textContent='Enter non-negative contributions and duration; annual return must be greater than -100%.';$('note').className='helper danger';return;}const months=Math.round(years*12),mr=Math.pow(1+rate/100,1/12)-1;let bal=initial,invested=initial,monthly=base;for(let m=1;m<=months;m++){if(m>1&&(m-1)%12===0)monthly*=1+step/100;if($('timing').value==='begin'){bal+=monthly;invested+=monthly;bal*=1+mr}else{bal*=1+mr;bal+=monthly;invested+=monthly}}$('fv').textContent=fmt(bal);$('invested').textContent=fmt(invested);$('gain').textContent=fmt(bal-invested);$('note').textContent='Projection assumes the same effective annual return is earned smoothly each month. Actual market returns, fees, taxes and cash-flow dates vary.';$('note').className='helper';}
['initial','monthly','rate','years','step','timing'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('initial').value=10000;$('monthly').value=500;$('rate').value=8;$('years').value=10;$('step').value=5;$('timing').value='end';go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the SIP investment growth calculator works</h2><p>This calculator compounds the current balance monthly and adds the recurring contribution at either the beginning or end of each month. If you use a step-up percentage, the monthly contribution increases after each completed 12-month block.</p>
<h2>Why contribution timing matters</h2><p>A contribution made at the beginning of a month receives one additional month of modeled growth compared with an equal contribution made at month-end. Over long periods, that timing difference can become visible.</p>
<h2>What the projected value means</h2><p>The result is a scenario, not a prediction. The assumed annual return is converted to an equivalent monthly compound rate. Real investments do not normally earn the same return every month, and sequence of returns can materially change outcomes.</p>
<h2>Use step-up assumptions carefully</h2><p>An annual SIP step-up can model future increases in recurring contributions. It is useful for scenario planning, but only choose a step-up that is realistic for your own cash-flow assumptions.</p>
<h3>Important financial limitation</h3><p>This tool does not model product fees, taxes, inflation, investment risk, missed contributions or market volatility. It is a mathematical planning calculator, not investment advice or a guarantee of future returns.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is a SIP in this calculator?','SIP is used here generically for a recurring monthly investment. The tool models regular contributions and compound growth; it is not tied to any specific fund or investment product.'],['Does the calculator use a simple annual rate divided by 12?','No. It converts the annual return into an equivalent monthly compound rate using (1 + annual rate)^(1/12) - 1.'],['What does annual step-up mean?','It increases the recurring monthly contribution once after each 12-month period by the percentage you enter.'],['Why can beginning-of-month contributions produce a higher value?','They are invested one month earlier than end-of-month contributions, giving each contribution an extra compounding period.'],['Is the projected value guaranteed?','No. It is a scenario based on the return and contribution assumptions you enter. Actual investment returns and costs can differ substantially.']];
require __DIR__.'/../includes/tool-template.php';
