<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('small-business','freelance-hourly-rate-calculator-india');ob_start(); ?>
<h2>Estimate a freelance hourly rate</h2>
<p class="lead">Build the rate from annual income goals and realistic billable hours rather than dividing salary by total working hours.</p>
<div class="form-grid"><div class="field"><label for="income">Desired annual personal/business income before tax</label><input id="income" type="number" value="1200000" step="0.01" min="0"></div><div class="field"><label for="costs">Annual business overhead</label><input id="costs" type="number" value="300000" step="0.01" min="0"></div><div class="field"><label for="weeks">Working weeks per year</label><input id="weeks" type="number" value="46" step="0.01" min="0.01" max="52"></div><div class="field"><label for="hours">Working hours per week</label><input id="hours" type="number" value="40" step="0.01" min="0.01"></div><div class="field"><label for="util">Billable utilization (%)</label><input id="util" type="number" value="60" step="0.01" min="0.01" max="100"></div><div class="field"><label for="reserve">Reserve / profit buffer (%)</label><input id="reserve" type="number" value="15" step="0.01" min="0" max="99.9"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated billable hours/year</span><strong id="billable">—</strong></div><div class="metric"><span>Annual revenue requirement</span><strong id="need">—</strong></div><div class="metric"><span>Required hourly rate</span><strong id="rate">—</strong></div><div class="metric"><span>8-hour equivalent billable day</span><strong id="day">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='₹')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const i=num('income'),c=num('costs'),w=num('weeks'),h=num('hours'),u=num('util')/100,r=num('reserve')/100;if([i,c].some(v=>v<0)||w<=0||h<=0||u<=0||u>1||r<0||r>=1){note('Check income, cost, capacity, utilization and reserve inputs.',true);return;}const bh=w*h*u,base=i+c,need=base/(1-r),rate=need/bh;$('billable').textContent=dec(bh,1);$('need').textContent=money(need,'₹');$('rate').textContent=money(rate,'₹')+'/hr';$('day').textContent=money(rate*8,'₹');note('This is a business-pricing model. GST, income tax and market positioning are not calculated automatically.');}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Estimated billable hours = working weeks × weekly hours × billable utilization. Revenue requirement before reserve = desired income + annual business overhead. To leave the entered reserve percentage of revenue, required revenue = base requirement ÷ (1 − reserve). Hourly rate divides required revenue by billable hours.</p><h2>How to use the result</h2><p>Use realistic utilization rather than assuming every working hour can be invoiced. Freelancers need time for sales, administration, learning, leave, collections and project gaps.</p><h2>Assumptions and limitations</h2><p>This is a pricing-planning model, not a tax calculator. It does not automatically add GST, income tax, platform fees or bad-debt risk. Market rates, project risk and value delivered may justify pricing above or below the calculated floor.</p><h2>Example</h2><p>A lower billable-utilization assumption increases the required hourly rate because the annual revenue target is spread across fewer invoiceable hours.</p>
<?php $toolContent=ob_get_clean();$faqs=[['Why not divide my desired income by 2,080 hours?','Freelancers rarely bill every working hour. The utilization input reserves time for non-billable work and gaps.'],['What should business overhead include?','Examples include software, equipment, coworking, accounting, insurance, marketing and subcontractor or administrative costs not already in your income goal.'],['Does the rate include GST?','No. Add any applicable indirect tax separately according to your verified tax treatment.'],['What is the reserve percentage?','It is the share of revenue you want left beyond the entered income and overhead requirement for profit, contingency or reinvestment.']];require __DIR__.'/../includes/tool-template.php';
