<?php require __DIR__.'/../includes/bootstrap.php';$tool=tool_by_path('small-business','project-profitability-calculator');ob_start(); ?>
<h2>Measure project profitability</h2>
<p class="lead">Combine direct delivery costs and allocated overhead, then compare them with project revenue.</p>
<div class="form-grid"><div class="field"><label for="revenue">Project revenue</label><input id="revenue" type="number" value="500000" step="0.01" min="0"></div><div class="field"><label for="laborHours">Internal labor hours</label><input id="laborHours" type="number" value="300" step="0.01" min="0"></div><div class="field"><label for="laborRate">Internal loaded cost per hour</label><input id="laborRate" type="number" value="800" step="0.01" min="0"></div><div class="field"><label for="contractors">Contractor / vendor cost</label><input id="contractors" type="number" value="50000" step="0.01" min="0"></div><div class="field"><label for="other">Other direct project cost</label><input id="other" type="number" value="20000" step="0.01" min="0"></div><div class="field"><label for="overhead">Allocated overhead</label><input id="overhead" type="number" value="40000" step="0.01" min="0"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Internal labor cost</span><strong id="labor">—</strong></div><div class="metric"><span>Total project cost</span><strong id="cost">—</strong></div><div class="metric"><span>Project profit</span><strong id="profit">—</strong></div><div class="metric"><span>Profit margin</span><strong id="margin">—</strong></div><div class="metric"><span>Profit / cost</span><strong id="roi">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{
const $=id=>document.getElementById(id);
const num=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0;};
const money=(v,c='')=>Number.isFinite(v)?c+v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const dec=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—';
const note=(m,bad=false)=>{const el=$('note');if(el){el.textContent=m||'';el.className='helper'+(bad?' danger':'');}};
function go(){const r=num('revenue'),h=num('laborHours'),lr=num('laborRate'),c=num('contractors'),o=num('other'),oh=num('overhead');if([r,h,lr,c,o,oh].some(v=>v<0)){note('Revenue and costs cannot be negative.',true);return;}const labor=h*lr,cost=labor+c+o+oh,profit=r-cost;$('labor').textContent=money(labor,'');$('cost').textContent=money(cost,'');$('profit').textContent=money(profit,'');$('margin').textContent=r>0?pct(profit/r*100):'—';$('roi').textContent=cost>0?pct(profit/cost*100):'—';note(profit<0?'The modeled project is loss-making under the entered cost allocation.':'Use a loaded labor cost rate if you want payroll-related employer costs reflected.',profit<0);}
if($('calc')) $('calc').addEventListener('click',go);
if($('reset')) $('reset').addEventListener('click',()=>{document.querySelectorAll('.tool-panel input,.tool-panel textarea,.tool-panel select').forEach(el=>{if(el.tagName==='SELECT') el.selectedIndex=0; else el.value=el.defaultValue;});go();});
document.querySelectorAll('.tool-panel input,.tool-panel select').forEach(el=>el.addEventListener('input',go));
go();
})();
</script>
<?php $toolBody=ob_get_clean();ob_start(); ?>
<h2>How the calculation works</h2><p>Internal labor cost = labor hours × loaded internal cost per hour. Total project cost adds contractor/vendor cost, other direct cost and allocated overhead. Project profit = revenue − total cost, and margin = profit ÷ revenue.</p><h2>How to use the result</h2><p>Use project profitability to compare scopes, clients and delivery models. Time tracking quality is important because unrecorded internal hours can make service projects look more profitable than they are.</p><h2>Assumptions and limitations</h2><p>Overhead allocation is a management assumption, and revenue timing may differ from cash collection. The model does not include tax, financing cost or future support obligations unless you add them to the cost inputs.</p><h2>Example</h2><p>A project can have positive cash inflow but poor economic profit if internal labor is treated as free; using a loaded hourly cost helps expose that consumption of capacity.</p>
<?php $toolContent=ob_get_clean();$faqs=[['What is a loaded labor cost rate?','It is an internal hourly cost that may include salary plus employer costs and other labor-related burden, depending on your accounting approach.'],['Should sales commission be included?','Include it in other direct cost or overhead if you want it reflected in project economics.'],['What is the difference between margin and ROI here?','Margin divides profit by revenue; the displayed profit/cost ratio divides profit by total modeled cost.'],['Does this measure cash flow?','No. It measures economic project profitability from entered revenue and costs, not payment timing.']];require __DIR__.'/../includes/tool-template.php';
