<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','cac-payback-calculator');
ob_start();
?>
<h2>Calculate CAC payback period</h2><p class="lead">Estimate how many months of gross-margin contribution are needed to recover customer acquisition cost.</p><div class="notice">Use gross-margin contribution rather than revenue alone when the purpose is to estimate recovery of acquisition spend.</div><div class="form-grid"><div class="field"><label for="cac">Customer acquisition cost (CAC)</label><input id="cac" type="number" value="12000" min="0" step="any"></div><div class="field"><label for="mrr">Monthly revenue per customer</label><input id="mrr" type="number" value="3000" min="0" step="any"></div><div class="field"><label for="margin">Gross margin (%)</label><input id="margin" type="number" value="75" min="0" max="100" step="any"></div><div class="field"><label for="churn">Optional monthly churn assumption (%)</label><input id="churn" type="number" value="0" min="0" max="100" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Simple CAC payback</span><strong id="payback">—</strong></div><div class="metric"><span>Monthly gross-margin contribution</span><strong id="contribution">—</strong></div><div class="metric"><span>12-month contribution</span><strong id="months12">—</strong></div><div class="metric"><span>12-month contribution / CAC</span><strong id="ratio">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('payback').textContent='—';$('contribution').textContent='—';$('months12').textContent='—';$('ratio').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const cac=num('cac'),m=num('mrr'),gm=num('margin')/100,ch=num('churn')/100;if(!(cac>=0&&m>=0&&gm>=0&&gm<=1&&ch>=0&&ch<=1))throw 0;const c=m*gm;const pb=c>0?cac/c:Infinity;let sum=0,surv=1;for(let i=0;i<12;i++){sum+=c*surv;surv*=1-ch}$('payback').textContent=Number.isFinite(pb)?fmt(pb,2)+' months':'Unavailable';$('contribution').textContent=fmt(c,2);$('months12').textContent=fmt(sum,2);$('ratio').textContent=cac>0?fmt(sum/cac,2)+'×':'—';$('note').textContent='Simple payback uses CAC ÷ monthly gross-margin contribution and ignores churn timing. The 12-month contribution scenario applies the optional churn assumption.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the CAC Payback Calculator works</h2><p>CAC payback asks how long gross-margin contribution from a newly acquired customer takes to recover the acquisition cost. The simple formula is CAC ÷ monthly revenue per customer ÷ gross margin percentage. The tool also calculates a 12-month contribution scenario that reduces the surviving customer base by an optional monthly churn assumption.</p><h2>How to use this cac payback calculator</h2><p>Enter blended or channel-specific CAC, monthly customer revenue and the gross margin percentage that remains after cost of goods or service delivery. Use the same cohort definition for both CAC and revenue. If you add churn, treat the 12-month result as a simple expected-value scenario rather than a detailed cohort survival model.</p><h2>How to interpret the result</h2><p>A shorter payback period means acquisition cash is recovered faster under the entered economics. The monthly contribution result makes the denominator transparent, while the 12-month contribution-to-CAC ratio shows whether one year of expected contribution covers acquisition spend. Neither metric measures lifetime profitability by itself.</p><h2>Assumptions and limitations</h2><p>CAC definitions vary: sales salaries, marketing payroll, tools, agency fees and overhead may be included or excluded. Gross margin can also vary by product and customer. The simple payback result assumes stable monthly contribution and does not discount cash flows. Churn, expansion and contraction can materially change realized recovery.</p><h2>Practical example and workflow</h2><p>If CAC is 12,000, monthly revenue is 3,000 and gross margin is 75%, monthly contribution is 2,250 and simple payback is about 5.33 months. A growth team can compare that with a higher-CAC channel that produces larger customers instead of judging channels by CAC alone.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the CAC payback formula?','Simple CAC payback = customer acquisition cost divided by monthly gross-margin contribution per customer.'],['Why use gross margin instead of revenue?','Revenue includes amounts needed to deliver the product/service. Gross-margin contribution is closer to the cash available to recover acquisition cost.'],['Should sales salaries be included in CAC?','That depends on your company’s CAC definition. For comparisons, use a consistent fully loaded or channel-specific definition.'],['Does a short CAC payback guarantee profitability?','No. Retention, support costs, expansion, overhead and long-term cash flows still determine overall unit economics.']];
require __DIR__.'/../includes/tool-template.php';
