<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','lead-scoring-calculator');
ob_start();
?>
<h2>Build a transparent weighted lead score</h2><p class="lead">Combine explicit fit, intent, engagement and authority scores with editable weights—without a hidden black-box score.</p><div class="notice">Define how each 0–100 component is earned before using the score operationally. A transparent scorecard is useful only when reps apply the same rules.</div><div class="form-grid"><div class="field"><label for="fit">ICP / company fit score (0–100)</label><input id="fit" type="number" value="80" min="0" max="100" step="any"></div><div class="field"><label for="fitw">Fit weight (%)</label><input id="fitw" type="number" value="35" min="0" max="100" step="any"></div><div class="field"><label for="intent">Buying intent score (0–100)</label><input id="intent" type="number" value="70" min="0" max="100" step="any"></div><div class="field"><label for="intentw">Intent weight (%)</label><input id="intentw" type="number" value="30" min="0" max="100" step="any"></div><div class="field"><label for="eng">Engagement score (0–100)</label><input id="eng" type="number" value="60" min="0" max="100" step="any"></div><div class="field"><label for="engw">Engagement weight (%)</label><input id="engw" type="number" value="20" min="0" max="100" step="any"></div><div class="field"><label for="auth">Decision authority score (0–100)</label><input id="auth" type="number" value="50" min="0" max="100" step="any"></div><div class="field"><label for="authw">Authority weight (%)</label><input id="authw" type="number" value="15" min="0" max="100" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Weighted lead score</span><strong id="score">—</strong></div><div class="metric"><span>Weight total</span><strong id="weights">—</strong></div><div class="metric"><span>Largest contribution</span><strong id="top">—</strong></div><div class="metric"><span>Points below 100</span><strong id="missing">—</strong></div></div><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>Component</th><th>Score</th><th>Weight</th><th>Contribution</th></tr></thead><tbody id="scoreRows"></tbody></table></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('score').textContent='—';$('weights').textContent='—';$('top').textContent='—';$('missing').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const vals=[['Fit',num('fit'),num('fitw')],['Intent',num('intent'),num('intentw')],['Engagement',num('eng'),num('engw')],['Authority',num('auth'),num('authw')]];if(vals.some(x=>!(x[1]>=0&&x[1]<=100&&x[2]>=0&&x[2]<=100)))throw 0;const ws=vals.reduce((a,x)=>a+x[2],0);const rows=vals.map(x=>[x[0],x[1],x[2],ws>0?x[1]*x[2]/ws:0]);const total=rows.reduce((a,x)=>a+x[3],0);rows.sort((a,b)=>b[3]-a[3]);$('score').textContent=ws>0?fmt(total,1)+' / 100':'—';$('weights').textContent=fmt(ws,1)+'%';$('top').textContent=ws>0?rows[0][0]+' ('+fmt(rows[0][3],1)+')':'—';$('missing').textContent=ws>0?fmt(100-total,1):'—';$('scoreRows').innerHTML=rows.map(x=>'<tr><td>'+x[0]+'</td><td>'+fmt(x[1],1)+'</td><td>'+fmt(x[2],1)+'%</td><td>'+fmt(x[3],1)+'</td></tr>').join('');$('note').textContent=ws===100?'Weights total 100%.':'Weights are normalized automatically because they total '+fmt(ws,1)+'%, but using 100% makes the model easier to govern.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Lead Scoring Calculator works</h2><p>This tool uses a weighted-average model rather than an unexplained proprietary score. Each component is scored from 0 to 100, multiplied by its relative weight, and normalized by the total weight. The contribution table shows exactly how many points each component adds to the final score so sales and marketing can audit the model.</p><h2>How to use this lead scoring calculator</h2><p>Define a written rubric before entering scores. For example, fit could reflect industry, company size and geography; intent could reflect pricing/demo behavior; engagement could reflect meaningful responses rather than raw email opens; authority could reflect buying-role evidence. Enter weights that reflect your go-to-market priorities and keep them stable long enough to validate outcomes.</p><h2>How to interpret the result</h2><p>The score is a prioritization aid, not a prediction of purchase probability. A high lead score should mean “meets the criteria we intentionally weighted,” not “will definitely buy.” The largest-contribution output helps diagnose why a lead ranks highly and can expose a model dominated by one component.</p><h2>Assumptions and limitations</h2><p>Bad inputs create bad scores. Avoid using sensitive personal traits, protected characteristics or opaque third-party inferences. Do not let activity volume outweigh qualification quality by accident. Revisit scoring rules with actual closed-won/lost data and check whether the model unfairly excludes good-fit segments or over-rewards noisy engagement signals.</p><h2>Practical example and workflow</h2><p>With 35% fit, 30% intent, 20% engagement and 15% authority, a lead with strong fit but modest authority can still score well, but the table makes that trade-off visible. A sales leader can then decide whether an authority threshold should be a separate routing rule instead of hiding it inside the score.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How should I choose lead scoring weights?','Start from documented sales qualification criteria, then validate the weights against real outcomes. Avoid assigning weights only because they “feel right.”'],['Why does the tool normalize weights?','Normalization keeps the final score on a 0–100 scale even if your entered weights do not total exactly 100%.'],['Is the score a probability that the lead will buy?','No. It is a weighted prioritization score based on your rubric unless you separately calibrate it as a predictive model.'],['What data should not be used in lead scoring?','Avoid protected/sensitive personal attributes and opaque data that cannot be justified or governed for the business purpose.']];
require __DIR__.'/../includes/tool-template.php';
