<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','meeting-to-opportunity-conversion-calculator');
ob_start();
?>
<h2>Calculate meeting-to-opportunity conversion</h2><p class="lead">Measure how many completed sales meetings create qualified opportunities and estimate meeting volume needed for a target.</p><div class="notice">Use completed meetings rather than scheduled meetings if no-shows are tracked separately, and keep the opportunity-creation rule consistent across reps.</div><div class="form-grid"><div class="field"><label for="meet">Completed qualified meetings</label><input id="meet" type="number" value="120" min="0" step="1"></div><div class="field"><label for="opp">Opportunities created</label><input id="opp" type="number" value="36" min="0" step="1"></div><div class="field"><label for="target">Target opportunities</label><input id="target" type="number" value="50" min="0" step="1"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Meeting-to-opportunity rate</span><strong id="rate">—</strong></div><div class="metric"><span>Meetings not converted</span><strong id="notconv">—</strong></div><div class="metric"><span>Meetings needed at current rate</span><strong id="needed">—</strong></div><div class="metric"><span>Opportunities from +5 points</span><strong id="lift">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('rate').textContent='—';$('notconv').textContent='—';$('needed').textContent='—';$('lift').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const m=num('meet'),o=num('opp'),t=num('target');if(!(m>=0&&o>=0&&o<=m&&t>=0))throw 0;const r=m>0?o/m:NaN;$('rate').textContent=Number.isFinite(r)?fmt(r*100,2)+'%':'—';$('notconv').textContent=fmt(m-o,0);$('needed').textContent=r>0?fmt(Math.ceil(t/r),0):'Unavailable';$('lift').textContent=fmt(m*0.05,1);$('note').textContent='Define what counts as a completed qualified meeting and as an opportunity before comparing teams. Calendar bookings alone are usually not the same denominator.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Meeting-to-Opportunity Conversion Calculator works</h2><p>Meeting-to-opportunity conversion is opportunities created ÷ completed qualified meetings. It isolates the part of the funnel where discovery quality, qualification and next-step alignment turn conversations into pipeline. The calculator also back-solves the number of meetings needed for a target opportunity count at the current conversion rate.</p><h2>How to use this meeting-to-opportunity conversion calculator</h2><p>Enter completed meetings using a documented definition—for example, discovery meetings that actually occurred—and the opportunities created from those meetings. If your CRM allows one meeting to create multiple opportunities or an opportunity to originate without a meeting, decide how those exceptions are handled before comparing teams.</p><h2>How to interpret the result</h2><p>A low rate can indicate targeting problems, weak qualification before the meeting, discovery execution or a very strict opportunity definition. A high rate is not automatically good if reps create low-quality opportunities too early. Pair the rate with downstream win rate and pipeline quality rather than optimizing the conversion percentage in isolation.</p><h2>Assumptions and limitations</h2><p>Calendar bookings are not the same as completed meetings because no-shows and cancellations change the denominator. Timing also matters: opportunities may be created days after a meeting. Use a consistent attribution window and avoid comparing teams that use different stage-entry criteria.</p><h2>Practical example and workflow</h2><p>If 36 opportunities are created from 120 completed meetings, conversion is 30%. To create 50 opportunities at the same rate, the team needs about 167 comparable meetings. A manager can then decide whether the gap should be solved with more activity or better conversion.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What should count as a meeting?','Use a consistent definition such as completed qualified discovery meetings. Do not mix scheduled meetings and completed meetings without accounting for no-shows.'],['What should count as an opportunity?','Use the CRM stage/qualification definition your organization has agreed on and apply it consistently.'],['Is a higher meeting-to-opportunity rate always better?','No. Creating weak opportunities too easily can raise the rate while reducing downstream pipeline quality.'],['How do I calculate meetings needed for a target?','Divide the target opportunity count by the current meeting-to-opportunity conversion rate.']];
require __DIR__.'/../includes/tool-template.php';
