<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','renewal-uplift-calculator');
ob_start();
?>
<h2>Model renewal and price uplift</h2><p class="lead">Estimate renewed recurring revenue after retention, contractual price uplift and expansion.</p><div class="notice">Apply uplift only where contracts permit it. Expansion, downsell and churn should be modelled using definitions that match your recurring-revenue reporting.</div><div class="form-grid"><div class="field"><label for="base">Starting renewable ARR / contract value</label><input id="base" type="number" value="1000000" min="0" step="any"></div><div class="field"><label for="renew">Renewal / retained value (%)</label><input id="renew" type="number" value="90" min="0" max="100" step="any"></div><div class="field"><label for="uplift">Price uplift on renewed base (%)</label><input id="uplift" type="number" value="5" step="any"></div><div class="field"><label for="exp">Expansion on renewed base (%)</label><input id="exp" type="number" value="8" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Retained base</span><strong id="renewed">—</strong></div><div class="metric"><span>Price uplift value</span><strong id="upliftamt">—</strong></div><div class="metric"><span>Ending renewed + expansion value</span><strong id="ending">—</strong></div><div class="metric"><span>Net change vs starting base</span><strong id="growth">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('renewed').textContent='—';$('upliftamt').textContent='—';$('ending').textContent='—';$('growth').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const b=num('base'),rr=num('renew')/100,u=num('uplift')/100,e=num('exp')/100;if(!(b>=0&&rr>=0&&rr<=1&&Number.isFinite(u)&&Number.isFinite(e)&&u>-1&&e>-1))throw 0;const ret=b*rr,up=ret*u,end=ret*(1+u)+ret*e;$('renewed').textContent=fmt(ret,2);$('upliftamt').textContent=fmt(up,2);$('ending').textContent=fmt(end,2);$('growth').textContent=b>0?fmt((end/b-1)*100,2)+'%':'—';$('note').textContent='This separates retained base, price uplift and expansion. It is a planning model, not a substitute for contract-level renewal forecasting.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Renewal Uplift Calculator works</h2><p>This tool first applies the renewal/retention percentage to the starting renewable value, creating the retained base. It then applies the entered price uplift and expansion assumptions to that retained base. Separating those effects prevents a price increase from being accidentally applied to churned value.</p><h2>How to use this renewal uplift calculator</h2><p>Enter the ARR or contract value that is actually up for renewal, the expected retained percentage, a contractual/assumed price uplift and expansion from added seats, products or usage. Use negative expansion if you intentionally want to model downsell, but keep churn/retention and expansion definitions consistent with finance reporting.</p><h2>How to interpret the result</h2><p>The ending value shows the combined effect of retention, price and expansion. A business can have high uplift but still end below the starting base if churn is large. Conversely, strong expansion can offset some lost accounts. The net-change percentage is therefore more informative than quoting price uplift alone.</p><h2>Assumptions and limitations</h2><p>Renewal behaviour is customer-level and often lumpy. The model does not account for renewal timing, multi-year contracts, ramped pricing, currency effects, usage variability or probability by account. Price increases may also be limited by contract language or regulation. Use contract-level forecasts for committed planning.</p><h2>Practical example and workflow</h2><p>With a 1,000,000 renewable base, 90% retained value, 5% price uplift and 8% expansion, the retained base is 900,000 and the uplift applies to that amount. The resulting ending value can be compared with the original million to see whether retention plus expansion actually creates net growth.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Should price uplift be applied before or after churn?','For this model, uplift is applied to the retained/renewed base so churned value does not receive a price increase.'],['Is renewal rate based on logos or revenue?','It can be either. This calculator is value-based when the starting input is ARR/contract value; do not mix logo retention with revenue retention.'],['Can expansion offset churn?','Yes mathematically, but track the components separately so the business can see whether growth comes from retention, pricing or expansion.'],['Does this forecast individual renewals?','No. It is an aggregate scenario; account-level probability and contract terms require a detailed renewal forecast.']];
require __DIR__.'/../includes/tool-template.php';
