<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','sales-commission-calculator');
ob_start();
?>
<h2>Calculate sales commission with an accelerator</h2><p class="lead">Estimate commission using a base rate up to a threshold and an accelerator rate above it.</p><div class="notice">Use the signed compensation plan as the authority. This calculator assumes the accelerator applies only to revenue above the threshold, not retroactively to all sales.</div><div class="form-grid"><div class="field"><label for="sales">Commissionable sales / bookings</label><input id="sales" type="number" value="1200000" min="0" step="any"></div><div class="field"><label for="rate">Base commission rate (%)</label><input id="rate" type="number" value="5" min="0" step="any"></div><div class="field"><label for="threshold">Accelerator threshold</label><input id="threshold" type="number" value="1000000" min="0" step="any"></div><div class="field"><label for="accel">Rate above threshold (%)</label><input id="accel" type="number" value="8" min="0" step="any"></div><div class="field"><label for="draw">Recoverable/nonrecoverable draw to subtract</label><input id="draw" type="number" value="0" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Gross commission</span><strong id="commission">—</strong></div><div class="metric"><span>Base-tier commission</span><strong id="base">—</strong></div><div class="metric"><span>Accelerated-tier commission</span><strong id="accelerated">—</strong></div><div class="metric"><span>Commission after entered draw</span><strong id="net">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('commission').textContent='—';$('base').textContent='—';$('accelerated').textContent='—';$('net').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const s=num('sales'),r=num('rate')/100,t=num('threshold'),a=num('accel')/100,d=num('draw');if(!(s>=0&&r>=0&&t>=0&&a>=0&&d>=0))throw 0;const base=Math.min(s,t)*r,extra=Math.max(0,s-t)*a,g=base+extra;$('commission').textContent=fmt(g,2);$('base').textContent=fmt(base,2);$('accelerated').textContent=fmt(extra,2);$('net').textContent=fmt(Math.max(0,g-d),2);$('note').textContent='Commission plans can use quotas, cumulative tiers, cliffs, caps, splits, collection rules and product multipliers. This models one simple marginal accelerator.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Sales Commission Calculator works</h2><p>The model applies the base commission rate to sales up to the accelerator threshold and the higher rate only to sales above that threshold. This is a marginal tier structure. It separately reports each tier so reps and managers can see exactly how the total was formed before subtracting an entered draw.</p><h2>How to use this sales commission calculator</h2><p>Enter commissionable sales, the base rate, accelerator threshold and rate above the threshold. Confirm whether your actual plan uses bookings, recognized revenue, collected cash, gross margin or another commission base. If the plan accelerates all revenue retroactively after quota, this simple marginal model is not the correct formula.</p><h2>How to interpret the result</h2><p>The split between base-tier and accelerated-tier commission helps explain the incremental value of selling above the threshold. It also makes plan modelling easier because a manager can test different thresholds/rates without manually rebuilding a spreadsheet for every scenario.</p><h2>Assumptions and limitations</h2><p>Compensation plans frequently include quotas by period, gates, cliffs, multiple tiers, decelerators, caps, product multipliers, team overlays, splits, clawbacks and draw rules. Tax withholding is also separate. This tool does not determine contractual entitlement; it is a transparent calculator for the specific two-tier assumptions entered.</p><h2>Practical example and workflow</h2><p>With 1.2 million of commissionable sales, a 5% base rate up to 1 million and an 8% accelerator above that point, the first tier earns 50,000 and the extra 200,000 earns 16,000, for 66,000 gross commission before any entered draw.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is a marginal accelerator?','Only the sales above the threshold earn the accelerator rate; earlier sales keep the base rate.'],['What if my plan applies the higher rate to all sales after quota?','That is a retroactive tier and needs a different formula. Do not use this marginal model for that plan.'],['Should commission be calculated on revenue or bookings?','Use the compensation plan’s defined commissionable base, which may be bookings, revenue, cash collection, margin or another measure.'],['Does this include tax withholding?','No. It calculates plan commission before payroll tax/withholding unless you model deductions separately.']];
require __DIR__.'/../includes/tool-template.php';
