<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','sales-velocity-calculator');
ob_start();
?>
<h2>Calculate sales velocity</h2><p class="lead">Estimate pipeline revenue velocity from opportunities, average deal value, win rate and sales-cycle length.</p><div class="notice">Sales velocity is a comparative pipeline metric, not guaranteed revenue. Open opportunity counts and win rates can be distorted by stale pipeline or inconsistent stage definitions.</div><div class="form-grid"><div class="field"><label for="opps">Qualified opportunities</label><input id="opps" type="number" value="80" min="0" step="any"></div><div class="field"><label for="deal">Average deal value</label><input id="deal" type="number" value="50000" min="0" step="any"></div><div class="field"><label for="win">Win rate (%)</label><input id="win" type="number" value="25" min="0" max="100" step="any"></div><div class="field"><label for="cycle">Average sales cycle (days)</label><input id="cycle" type="number" value="60" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Revenue velocity per day</span><strong id="velocity">—</strong></div><div class="metric"><span>Expected won value in cohort</span><strong id="weighted">—</strong></div><div class="metric"><span>Expected wins</span><strong id="wins">—</strong></div><div class="metric"><span>30-day equivalent velocity</span><strong id="monthly">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('velocity').textContent='—';$('weighted').textContent='—';$('wins').textContent='—';$('monthly').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const o=num('opps'),d=num('deal'),w=num('win')/100,c=num('cycle');if(!(o>=0&&d>=0&&w>=0&&w<=1&&c>0))throw 0;const weighted=o*d*w,v=weighted/c;$('velocity').textContent=fmt(v,2)+'/day';$('weighted').textContent=fmt(weighted,2);$('wins').textContent=fmt(o*w,2);$('monthly').textContent=fmt(v*30,2);$('note').textContent='Salesforce expresses sales velocity as opportunities × average deal value × win rate ÷ sales-cycle length. Keep all four inputs scoped to the same pipeline definition.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Sales Velocity Calculator works</h2><p>Salesforce describes sales velocity as opportunities × average deal value × win rate ÷ length of sales cycle. The numerator is the expected won value represented by the measured opportunity cohort; dividing by cycle length converts that amount into a revenue-per-day pace for the selected pipeline assumptions.</p><h2>How to use this sales velocity calculator</h2><p>Use qualified opportunities from a consistent stage, average deal value from the same segment, win rate based on comparable closed opportunities and average sales-cycle length using a documented start/end point. Mixing enterprise cycle length with SMB opportunity values, for example, creates a number that looks precise but is not operationally meaningful.</p><h2>How to interpret the result</h2><p>Velocity can improve by increasing qualified opportunity volume, deal value or win rate, or by shortening cycle length. The formula is useful because it keeps those levers visible instead of celebrating one metric in isolation. A 30-day equivalent is shown only as a scaling convenience, not a forecast of recognized monthly revenue.</p><h2>Assumptions and limitations</h2><p>The metric assumes average values and stable relationships. Pipeline age, stage quality, seasonality, multi-year bookings, renewals and changes in segment mix can make realized revenue differ materially. Salesforce also emphasizes CRM hygiene when using win-rate metrics; stale or inconsistently closed opportunities can distort the result.</p><h2>Practical example and workflow</h2><p>With 80 opportunities, 50,000 average deal value, 25% win rate and a 60-day cycle, expected won value is 1 million and velocity is about 16,667 per day. A team can then compare whether improving win rate or shortening the cycle has a larger modeled effect.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the sales velocity formula?','Opportunities × average deal value × win rate ÷ average sales-cycle length.'],['What unit is sales velocity measured in?','It is value per unit of cycle time; this calculator uses value per day because the sales cycle is entered in days.'],['Can sales velocity be used as a revenue forecast?','It is better treated as a comparative pipeline metric. Actual revenue timing and recognition can differ from the simple formula.'],['Why does pipeline hygiene matter?','Stale opportunities, inconsistent stages and incorrect close statuses distort opportunity count, win rate and cycle length—the inputs to the formula.']];
require __DIR__.'/../includes/tool-template.php';
