<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','sdr-activity-goal-calculator');
ob_start();
?>
<h2>Backsolve SDR activity goals</h2><p class="lead">Translate a meeting target into required conversations and outbound activities using funnel conversion rates.</p><div class="notice">“Activity” can mean calls, personalized emails or another defined outreach unit. Do not sum unlike activities without a clear model of how each converts.</div><div class="form-grid"><div class="field"><label for="meet">Target completed meetings per month</label><input id="meet" type="number" value="20" min="0" step="any"></div><div class="field"><label for="convmeet">Conversation → meeting rate (%)</label><input id="convmeet" type="number" value="25" min="0.001" max="100" step="any"></div><div class="field"><label for="actconv">Activity → live conversation rate (%)</label><input id="actconv" type="number" value="8" min="0.001" max="100" step="any"></div><div class="field"><label for="days">Working days in month</label><input id="days" type="number" value="20" min="1" step="1"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Conversations needed</span><strong id="conv">—</strong></div><div class="metric"><span>Activities needed</span><strong id="acts">—</strong></div><div class="metric"><span>Activities per working day</span><strong id="perday">—</strong></div><div class="metric"><span>Meetings per working day</span><strong id="meetday">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('conv').textContent='—';$('acts').textContent='—';$('perday').textContent='—';$('meetday').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const m=num('meet'),cm=num('convmeet')/100,ac=num('actconv')/100,d=num('days');if(!(m>=0&&cm>0&&cm<=1&&ac>0&&ac<=1&&d>0))throw 0;const c=m/cm,a=c/ac;$('conv').textContent=fmt(Math.ceil(c),0);$('acts').textContent=fmt(Math.ceil(a),0);$('perday').textContent=fmt(a/d,1);$('meetday').textContent=fmt(m/d,2);$('note').textContent='Activity quality and channel mix matter. Use conversion rates from comparable SDRs/segments rather than applying one benchmark universally.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the SDR Activity Goal Calculator works</h2><p>The calculator works backward through two funnel stages. Conversations needed = target meetings ÷ conversation-to-meeting rate. Activities needed = conversations needed ÷ activity-to-conversation rate. Dividing by working days turns the monthly requirement into an average daily activity goal.</p><h2>How to use this sdr activity goal calculator</h2><p>Use conversion rates from the same segment, channel and SDR motion you are planning. A cold-call live-conversation rate should not be applied to personalized email or event follow-up. Define “completed meeting” consistently and decide whether no-shows are included in the conversion stage or tracked separately.</p><h2>How to interpret the result</h2><p>The result is a capacity scenario, not a quota recommendation. Very high required activity per day can reveal that the conversion assumptions or meeting target are unrealistic, but simply raising activity volume may reduce personalization and conversion. Use it alongside available selling time and rep workload.</p><h2>Assumptions and limitations</h2><p>Conversion rates change with list quality, geography, persona, season, brand awareness and rep skill. The model assumes rates remain stable when activity increases. It also ignores multi-touch sequences where several activities contribute to one conversation. For operational planning, measure sequence-level conversion and channel mix.</p><h2>Practical example and workflow</h2><p>To create 20 meetings with a 25% conversation-to-meeting rate, an SDR needs about 80 live conversations. At an 8% activity-to-conversation rate, that implies around 1,000 activities, or 50 per day across 20 working days. The manager can then test whether the daily load fits available time.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How do I calculate SDR activity needed?','Work backward from the target: meetings ÷ conversation-to-meeting rate ÷ activity-to-conversation rate.'],['Should calls and emails be counted as the same activity?','Only if your planning model intentionally combines them. Different channels usually have different time costs and conversion rates.'],['Why can higher activity reduce conversion?','More volume can reduce targeting and personalization quality or exhaust good lists, so conversion may not stay constant.'],['Should no-shows count as meetings?','Define the metric clearly. Many teams plan around completed meetings and track booked-to-held rate separately.']];
require __DIR__.'/../includes/tool-template.php';
