<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','territory-capacity-calculator');
ob_start();
?>
<h2>Estimate sales territory capacity</h2><p class="lead">Estimate how many qualified opportunities a territory/team can actively work from rep count, available selling time and average opportunity workload.</p><div class="notice">Use time-study data where possible. The goal is to expose workload assumptions instead of assigning a universal number of accounts or opportunities per rep.</div><div class="form-grid"><div class="field"><label for="reps">Active reps in territory</label><input id="reps" type="number" value="5" min="0" step="1"></div><div class="field"><label for="days">Selling days per month</label><input id="days" type="number" value="20" min="0" step="any"></div><div class="field"><label for="hours">Productive selling hours per day</label><input id="hours" type="number" value="5" min="0" step="any"></div><div class="field"><label for="util">Share of productive time available for opportunities (%)</label><input id="util" type="number" value="70" min="0" max="100" step="any"></div><div class="field"><label for="peropp">Average rep hours per active opportunity / month</label><input id="peropp" type="number" value="4" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Available opportunity hours</span><strong id="hourscap">—</strong></div><div class="metric"><span>Active opportunity capacity</span><strong id="capacity">—</strong></div><div class="metric"><span>Capacity per rep</span><strong id="perrep">—</strong></div><div class="metric"><span>Hours per additional opportunity</span><strong id="spare">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('hourscap').textContent='—';$('capacity').textContent='—';$('perrep').textContent='—';$('spare').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const r=num('reps'),d=num('days'),h=num('hours'),u=num('util')/100,p=num('peropp');if(!(r>=0&&d>=0&&h>=0&&u>=0&&u<=1&&p>0))throw 0;const hrs=r*d*h*u,cap=hrs/p;$('hourscap').textContent=fmt(hrs,1)+' h/month';$('capacity').textContent=fmt(cap,1)+' opps';$('perrep').textContent=r>0?fmt(cap/r,1)+' opps':'—';$('spare').textContent=fmt(p,1)+' rep-hours';$('note').textContent='This is a workload capacity model, not a market-potential model. Opportunity complexity, travel, account coverage and admin time can make actual capacity lower.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Territory Capacity Calculator works</h2><p>This calculator models territory capacity as available rep-hours ÷ average hours required per active opportunity. Available hours are reps × selling days × productive selling hours/day × the share of that time actually available for opportunity work. It is deliberately a workload model rather than an unexplained “accounts per rep” benchmark.</p><h2>How to use this territory capacity calculator</h2><p>Enter active rep count, realistic selling days, productive hours after meetings/admin/travel, the percentage allocated to active opportunities and an average monthly workload per opportunity. Use CRM/calendar time studies or representative rep interviews rather than theoretical eight-hour days when setting the assumptions.</p><h2>How to interpret the result</h2><p>The result estimates how many active opportunities the team can work at the entered service level. If open pipeline is far above capacity, response quality, follow-up cadence or forecast hygiene may deteriorate. If it is far below capacity, the constraint may be territory demand, prospecting volume or qualification rather than headcount.</p><h2>Assumptions and limitations</h2><p>Opportunity workload varies by segment, deal stage, geography and sales motion. Enterprise deals can consume far more hours than transactional deals. The tool does not estimate addressable market, account potential or required travel. It also assumes workload scales linearly, which can fail when coordination overhead rises with team size.</p><h2>Practical example and workflow</h2><p>Five reps with 20 selling days, five productive hours/day and 70% of time available for opportunity work provide 350 opportunity-hours per month. At four hours per active opportunity, modeled capacity is about 87.5 active opportunities across the territory.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Is territory capacity the same as market potential?','No. Capacity is how much workload the team can handle; market potential is how much opportunity exists in the territory.'],['How do I estimate hours per opportunity?','Use representative CRM/calendar data or time studies by segment and stage rather than a universal benchmark.'],['Should prospecting time be included?','Only if the utilization assumption and opportunity-hours definition are built to include it. Keep prospecting and active-deal work conceptually clear.'],['Can I use this to decide headcount?','It can support scenario planning, but hiring decisions should also consider pipeline demand, ramp time, territory potential and service expectations.']];
require __DIR__.'/../includes/tool-template.php';
