<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('sales-business-development','win-rate-calculator');
ob_start();
?>
<h2>Calculate sales win rate</h2><p class="lead">Calculate win rate from closed-won and closed-lost opportunities and estimate wins at a target rate.</p><div class="notice">Decide whether your organization’s headline win rate uses only closed opportunities or all created opportunities, then keep that definition consistent.</div><div class="form-grid"><div class="field"><label for="won">Closed-won opportunities</label><input id="won" type="number" value="25" min="0" step="1"></div><div class="field"><label for="lost">Closed-lost opportunities</label><input id="lost" type="number" value="75" min="0" step="1"></div><div class="field"><label for="open">Open opportunities (shown separately)</label><input id="open" type="number" value="40" min="0" step="1"></div><div class="field"><label for="target">Target win rate (%)</label><input id="target" type="number" value="30" min="0" max="100" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Win rate on closed opportunities</span><strong id="rate">—</strong></div><div class="metric"><span>Loss rate</span><strong id="loss">—</strong></div><div class="metric"><span>Wins needed at target (same closed total)</span><strong id="needed">—</strong></div><div class="metric"><span>Won as % of all incl. open</span><strong id="all">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('rate').textContent='—';$('loss').textContent='—';$('needed').textContent='—';$('all').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const w=num('won'),l=num('lost'),o=num('open'),t=num('target')/100;if(!(w>=0&&l>=0&&o>=0&&t>=0&&t<=1))throw 0;const closed=w+l,r=closed>0?w/closed:NaN,all=w/(closed+o);$('rate').textContent=Number.isFinite(r)?fmt(r*100,2)+'%':'—';$('loss').textContent=Number.isFinite(r)?fmt((1-r)*100,2)+'%':'—';$('needed').textContent=closed>0?fmt(Math.ceil(closed*t),0):'—';$('all').textContent=(closed+o)>0?fmt(all*100,2)+'%':'—';$('note').textContent='Salesforce documents closed-opportunity win rate as won ÷ closed. Open opportunities are shown separately because including them answers a different question.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Win Rate Calculator works</h2><p>Salesforce documents a common closed-opportunity win-rate formula as won opportunities ÷ total closed opportunities. This calculator uses closed won plus closed lost as the denominator and shows open opportunities separately. It also displays won as a percentage of all entered opportunities so teams can see how changing the denominator changes the story.</p><h2>How to use this win rate calculator</h2><p>Enter closed-won and closed-lost counts from the same period/cohort and stage definition. Add open pipeline only for context; it does not affect the headline closed win rate. The target field estimates how many wins would correspond to that target if the same total number of opportunities were closed.</p><h2>How to interpret the result</h2><p>A 25% win rate means one in four closed opportunities was won under the chosen definition. It does not tell you how many opportunities are still open, how much value was won, or whether wins are concentrated in small deals. Pair count win rate with value-weighted performance and stage conversion for fuller diagnosis.</p><h2>Assumptions and limitations</h2><p>Win-rate definitions differ across organizations. Some divide by all created opportunities, which includes open deals; others use only closed decisions. CRM hygiene matters because stale open deals and incorrectly closed records distort either method. Compare teams only when qualification and close-status rules are consistent.</p><h2>Practical example and workflow</h2><p>If 25 opportunities are won and 75 are lost, closed win rate is 25%. Adding 40 open opportunities does not change that closed-decision rate, although wins are only 17.9% of all 140 records. Showing both prevents teams from arguing over percentages that use different denominators.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What denominator should I use for sales win rate?','A common method uses won divided by all closed opportunities. If your organization uses all created opportunities instead, label that metric separately.'],['Should open opportunities count as losses?','Not in the closed-opportunity win-rate definition. They are unresolved and should be tracked separately until closed.'],['Can win rate be value-weighted?','Yes, but that is a different metric. This calculator uses opportunity counts rather than deal value.'],['Why does CRM hygiene affect win rate?','Incorrect or stale statuses change the denominator and can make the rate look better or worse than actual closed decisions.']];
require __DIR__.'/../includes/tool-template.php';
