<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('codeql-2-27-2-security-analysis-changes');ob_start(); ?>
<p>GitHub released CodeQL 2.27.2 on October 9, 2026. The update improves security analysis for C++, Go, Rust and JavaScript/TypeScript, changes several query behaviors, and introduces a breaking change to the Go control-flow graph library. Teams using custom CodeQL queries should review the Go changes before updating, and teams building compiled languages on macOS should check the new Xcode compatibility limits.</p>
<figure class="article-image"><img src="/assets/images/blog/codeql-2-27-2-security-analysis-changes.svg" alt="CodeQL 2.27.2 release card with C++, Go, Rust and JavaScript analysis updates"></figure>
<h2>What CodeQL 2.27.2 adds</h2>
<p>CodeQL is the static analysis engine behind GitHub code scanning. It analyzes code and data flow to find patterns that may indicate security problems. Version 2.27.2 adds language models and analysis improvements rather than introducing a new AI coding assistant.</p>
<table class="data-table"><thead><tr><th>Area</th><th>Changes described by GitHub</th><th>Who should review it</th></tr></thead><tbody><tr><td>C/C++</td><td>Parses ECMAScript-style regular expressions used by <code>std::regex</code>; adds SQL-injection sink models for the Comdb2 C API and flow summaries for Bloomberg BDE codecs and byte-stream deserializers.</td><td>Teams scanning C++ services, database code or custom data-processing libraries.</td></tr><tr><td>Go</td><td>Adds modeling for <code>github.com/coder/websocket</code>, alongside the existing <code>nhooyr.io/websocket</code> path.</td><td>Go teams using the newer WebSocket package path.</td></tr><tr><td>Rust</td><td>Adds extractor support for <code>AnyAttr</code> and <code>DocComment</code>, improves data flow around async blocks and <code>await</code>, and adds summaries for TLS libraries.</td><td>Rust teams with async code or TLS dependencies.</td></tr><tr><td>JavaScript/TypeScript</td><td>Recognizes Workflow SDK directives <code>use workflow</code> and <code>use step</code>, and improves Hapi route-handler and request-input tracking.</td><td>Teams using workflow frameworks or custom Hapi route registration.</td></tr></tbody></table>
<p>These changes can improve what CodeQL understands about a codebase, but they do not guarantee that every vulnerability will be found. Keep code review, tests and other security controls in place.</p>
<h2>Important macOS and Xcode compatibility limit</h2>
<p>GitHub notes that macOS 27 and Xcode 27 no longer ship the multi-architecture x86-64/arm64 binaries that CodeQL needs for traced analysis. As a result, CodeQL's <strong>autobuild</strong> and <strong>manual</strong> build modes for compiled languages are not supported on macOS 27 with any Xcode version, or on macOS 26 when Xcode 27 is selected.</p>
<p>For those build modes, GitHub says to use at most macOS 26 with Xcode 26. The team is working to improve support for the <strong>none</strong> build mode on macOS, but the changelog does not give a date for that work. If your CI image updates automatically, pin or review the operating-system and Xcode versions before the next CodeQL run.</p>
<h2>The Go control-flow graph change may affect custom queries</h2>
<p>The Go control-flow graph (CFG) now uses a shared CFG library. It includes additional nodes for assignments, parameters, results, range statements and deferred calls, while excluding nodes that are not reachable from the entry point. This changes node and edge structure, source locations, textual representations and basic-block boundaries.</p>
<p>GitHub lists several query API changes: <code>BasicBlocks::Cfg</code> is removed; <code>ControlFlow::EntryNode</code>, <code>ControlFlow::ExitNode</code> and <code>SwitchStmt.getExpr</code> are added; <code>IfStmt.getCond</code> is deprecated in favor of <code>IfStmt.getCondition</code>; and the return types of <code>IfStmt.getThen</code> and <code>LoopStmt.getBody</code> change to <code>Stmt</code>. If you maintain custom Go queries that depend on the old CFG shape, test and update them before treating the new results as equivalent.</p>
<h2>Other query and CLI changes</h2>
<p>The release also adjusts C# clickjacking and XSS query behavior, adds a way to flag first-party owners in the GitHub Actions unpinned-tag query, and improves CodeQL CLI error handling. Invalid <code>qlpack:</code> and <code>from:</code> values now produce clearer errors instead of a crash, and YAML data-extension integers outside the signed 32-bit range are rejected rather than silently truncated.</p>
<p>Structured output such as logs and SARIF remains unchanged for the CLI message-prefix update. Still, teams that parse plain-text stderr should check scripts that expect the previous error wording.</p>
<h2>Availability and upgrade planning</h2>
<p>GitHub says each new CodeQL version is deployed automatically to users of GitHub code scanning on github.com. A future GitHub Enterprise Server release will include CodeQL 2.27.2; customers on older GHES versions can manually upgrade the CodeQL version. Do not assume the same rollout date applies to every self-hosted installation.</p>
<ol><li>Check whether your scans use compiled-language autobuild or manual build modes on macOS.</li><li>Review Xcode and macOS image changes in CI.</li><li>Run your custom Go queries against representative repositories and inspect changed results.</li><li>Check scripts that parse CodeQL CLI stderr.</li><li>Compare the new alerts with code owners and security reviewers before changing production policy.</li></ol>
<p>For another layer of pull-request review, see our <a href="/tools-guide/github-copilot-code-review-api-guide">guide to the GitHub Copilot Code Review API</a>. The API-based review workflow and CodeQL static analysis solve different problems, so one should not replace the other.</p>
<h2>Frequently asked questions</h2>
<h3>Does CodeQL 2.27.2 automatically reach GitHub code scanning?</h3><p>GitHub says it automatically deploys new CodeQL versions to users of code scanning on github.com. GitHub Enterprise Server follows its own release schedule.</p>
<h3>Should all Go query authors update their code?</h3><p>Review custom queries that depend on CFG nodes, edges, basic blocks or the listed APIs. Queries that do not use those areas may need no change, but should still be tested.</p>
<h3>Can I use Xcode 27 for compiled-language analysis on macOS 26?</h3><p>GitHub says autobuild and manual build modes for compiled languages are not supported on macOS 26 when Xcode 27 is selected. Use macOS 26 with Xcode 26 or review the supported alternatives.</p>
<h2>Sources</h2>
<ul><li><a href="https://github.blog/changelog/2026-10-09-codeql-2-27-2-improves-c-go-rust-and-javascript-analysis/" target="_blank" rel="noopener noreferrer">GitHub Changelog: CodeQL 2.27.2 improves C++, Go, Rust and JavaScript analysis</a> (October 9, 2026).</li><li><a href="https://docs.github.com/en/code-security/code-scanning" target="_blank" rel="noopener noreferrer">GitHub Docs: Code scanning</a>.</li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php';
