<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('gemini-code-assist-sales-end-renewal-dates-options');ob_start(); ?>
<p>Google stopped selling new Gemini Code Assist Standard and Enterprise subscriptions on October 9, 2026. Existing customers can keep using their subscriptions until the end of their current contractual agreement, but license additions and renewal options have different deadlines. Google points customers toward Antigravity for future agentic coding assistance, through eligible Gemini Enterprise editions.</p>
<figure class="article-image"><img src="/assets/images/blog/gemini-code-assist-sales-end-renewal-dates-options.svg" alt="A subscription transition timeline showing October 9, January 31 and December 31 dates"></figure>
<h2>What changed on October 9?</h2>
<p>The Google Cloud documentation now says new Gemini Code Assist Standard and Enterprise subscriptions can no longer be purchased from October 9, 2026. This is a change to subscription sales, not a statement that every existing installation stopped working on that date. Google's page says current subscriptions remain supported until the end of each contractual agreement.</p>
<p>The deadlines are not identical for monthly and annual customers. Check the renewal date and contract terms for your own organization rather than assuming every plan ends at the same time.</p>
<h2>Key dates for existing customers</h2>
<table class="data-table"><thead><tr><th>Date</th><th>What Google's documentation says</th></tr></thead><tbody><tr><td>October 9, 2026</td><td>New Standard and Enterprise subscriptions are no longer available for purchase.</td></tr><tr><td>January 31, 2027</td><td>Existing customers can add licenses until this date. Annual subscriptions can auto-renew until this date; after it, annual renewals are no longer available.</td></tr><tr><td>December 31, 2027</td><td>Monthly subscriptions can continue to auto-renew until this date; after it, monthly renewals are no longer available.</td></tr></tbody></table>
<p>These are the dates on Google's current sunset page. Your contractual end date may be earlier or later, depending on the agreement. Confirm the exact account status with your Google Cloud administrator or account representative before making a migration decision.</p>
<h2>What happens if your team already uses Gemini Code Assist?</h2>
<p>Google says existing subscriptions continue to work and remain supported until the end of the contractual agreement. That gives teams time to plan, but it does not mean that every future renewal or license increase will be possible. The January 2027 license-addition deadline matters for organizations that expect to expand their developer seats.</p>
<p>Make an inventory before you change anything:</p>
<ol><li>Record the subscription type, renewal date, contract end date and number of assigned licenses.</li><li>List the IDEs, extensions, command-line tools and team workflows that rely on Gemini Code Assist.</li><li>Identify any shared prompts, project rules, custom integrations or internal documentation that need a replacement.</li><li>Test the replacement with representative code tasks, private repositories and the same review rules used today.</li><li>Confirm pricing, access controls, data handling and support terms before approving the change.</li></ol>
<h2>What is the suggested replacement?</h2>
<p>Google's sunset page says agentic coding assistance will be available through Antigravity, which is included in Gemini Enterprise editions. It recommends planning a transition to Gemini Enterprise before the current plan reaches its final renewal or contract end date.</p>
<p>Do not assume this is an automatic, one-click migration or that every Gemini Code Assist feature has an identical replacement. The page does not provide a full feature-by-feature parity table, nor does it state that existing Code Assist subscriptions automatically convert to Gemini Enterprise. Review the current Antigravity IDE and CLI documentation, test the tasks your team relies on, and ask Google to confirm any commercial or support details that are not covered in the public notice.</p>
<p>Google also links a migration guide for moving from Gemini CLI to Antigravity CLI. That guide can help with the command-line transition, but it should not be treated as proof that every part of a Standard or Enterprise subscription migrates automatically.</p>
<h2>How to plan the transition safely</h2>
<p>Start with a small pilot rather than switching the whole team at once. Choose a few common tasks such as explaining a function, writing a unit test, debugging a build and making a contained refactor. Compare the result with your current workflow and check whether repository access, code review, command execution and team policies still work as expected.</p>
<p>Keep human review in place during the pilot. Coding agents can produce incorrect patches, use tools in unexpected ways or miss project-specific requirements. Require a diff review and tests before merging, and avoid granting a replacement tool broader permissions simply to make it work like the old setup.</p>
<p>For context on Google's broader work-agent direction, see our coverage of the <a href="/ai-news/gemini-agent-at-work-2026">Gemini agent announced for enterprise work</a>. It is a separate product announcement, not a substitute for checking the specific Code Assist transition terms.</p>
<h2>What remains unclear?</h2>
<p>The sunset notice gives the key sales and renewal dates, but it does not settle every customer's commercial situation. Public documentation does not establish a universal migration deadline for every contract, a direct automatic conversion path, or exact feature parity between Code Assist and Antigravity. Pricing and access through Gemini Enterprise depend on the applicable edition and agreement. Confirm those details before changing licenses or ending a contract.</p>
<h2>Frequently asked questions</h2>
<h3>Will Gemini Code Assist stop working on October 9, 2026?</h3><p>Google says existing subscriptions remain supported until the end of the contractual agreement. October 9 is the date new Standard and Enterprise subscriptions stopped being sold.</p>
<h3>Can an existing customer add licenses after January 31, 2027?</h3><p>Google's page says new licenses can be added until January 31, 2027. After that date, no new licenses can be added under this sunset arrangement.</p>
<h3>Is Antigravity a free replacement?</h3><p>The notice says Antigravity is included in Gemini Enterprise editions. It does not say that every customer receives the same features or price as their former Code Assist plan.</p>
<h2>Sources</h2>
<ul><li><a href="https://docs.cloud.google.com/gemini/docs/codeassist/sunset" target="_blank" rel="noopener noreferrer">Google Cloud documentation: Gemini Code Assist Standard and Enterprise subscription sunset</a> (last updated October 9, 2026).</li><li><a href="https://docs.cloud.google.com/gemini/docs/release-notes" target="_blank" rel="noopener noreferrer">Google Cloud documentation: Gemini for Google Cloud release notes</a> (October 9, 2026 entry).</li><li><a href="https://antigravity.google/docs/gcli-migration" target="_blank" rel="noopener noreferrer">Antigravity: Gemini CLI migration guide</a>.</li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php';
