<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('github-copilot-updates-sandbox-ollama-haiku-5-5');ob_start(); ?>
<p>GitHub's Copilot weekly roundup was published on October 9, 2026, covering updates from the week beginning October 5. The most useful changes include local sandboxing for agent sessions, Claude Haiku 5.5 access across paid Copilot plans, discovery of supported local Ollama models in Copilot CLI, and side-by-side agent sessions in VS Code. The roundup date is October 9; some individual features have their own October 7 release notes.</p>
<figure class="article-image"><img src="/assets/images/blog/github-copilot-updates-sandbox-ollama-haiku-5-5.svg" alt="GitHub Copilot weekly update summary showing local sandboxing, local models, Claude Haiku 5.5 and agent sessions"></figure>
<h2>At a glance</h2>
<table class="data-table"><thead><tr><th>Update</th><th>Where it applies</th><th>What to know</th></tr></thead><tbody><tr><td>Local sandboxing</td><td>Copilot CLI, Copilot app and VS Code sessions using Agent Host</td><td>Generally available and included with Copilot at no extra charge, but local sandboxing is off by default.</td></tr><tr><td>Claude Haiku 5.5</td><td>Copilot Pro, Pro+, Max, Business and Enterprise</td><td>Availability is plan-specific; check your model picker and organization policies.</td></tr><tr><td>Local Ollama models</td><td>Copilot CLI</td><td>Use <code>/model</code> to discover supported models from a running local Ollama instance.</td></tr><tr><td>Agent sessions</td><td>VS Code 1.141</td><td>View sessions side by side and clean up inactive session worktrees.</td></tr><tr><td>Separate accounts</td><td>GitHub Copilot app</td><td>The account providing the Copilot license can differ from the account used to access repositories.</td></tr></tbody></table>
<h2>Local sandboxing is the main security change</h2>
<p>Local sandboxing restricts the filesystem, network and system capabilities available to commands that Copilot runs. GitHub says it is now generally available in Copilot CLI, the Copilot app and VS Code sessions using Agent Host, with no extra Copilot charge for local sandboxing.</p>
<p>There is an important setup detail: GitHub's documentation says local sandboxing is turned off by default. Until it is enabled, shell commands run with the same access as your user account. In Copilot CLI, you can enable it with <code>/sandbox enable</code>; in the Copilot app, project settings define the default for new local sessions and can be changed for an active session. The CLI and app settings are separate, so changing one does not change the other.</p>
<p>Local sandboxing is not a full virtual machine or container. GitHub describes it as lighter-weight operating-system isolation that restricts what a process can read, write or reach on the network. That can reduce risk, but teams with stricter isolation requirements should review the implementation and test the policy against their threat model. Cloud sandboxing is a separate option and is billed based on usage.</p>
<h2>Claude Haiku 5.5 is available across paid Copilot plans</h2>
<p>The October 9 roundup says Claude Haiku 5.5 is available to Copilot Pro, Pro+, Max, Business and Enterprise users. This is a model-availability update, not a claim that every account will automatically select the model. Availability can still depend on the plan, organization policy and the current model picker.</p>
<p>For teams choosing a model, test it on the tasks that matter: code explanation, focused edits, test generation and multi-file changes. Do not assume a smaller or faster model will perform equally well on every repository. Keep your normal tests and code review process regardless of which model is selected.</p>
<h2>Copilot CLI can discover supported local Ollama models</h2>
<p>GitHub says Copilot CLI can use <code>/model</code> to discover supported models from a running local Ollama instance alongside configured models and cloud models supplied by Copilot. This can make it easier to compare a local workflow with a hosted model without leaving the CLI.</p>
<p>The word <strong>supported</strong> matters: the announcement does not promise that every model available through Ollama works with Copilot CLI. You need a running local Ollama service and a compatible model. Local inference also uses your machine's CPU, GPU and memory, so performance depends on your hardware and model size. Do not treat “local” as proof that every part of a workflow stays on-device; review the configuration and any tools or services the agent can call.</p>
<h2>Account separation and VS Code session management</h2>
<p>The Copilot app now supports separate GitHub accounts for the Copilot license and the repositories being accessed. For example, a developer may use an employer-provided Copilot license while opening repositories through another account. This is useful for some multi-account setups, but it does not bypass repository permissions or an organization's access policies.</p>
<p>In VS Code 1.141, agent sessions can be arranged side by side in a grid. That helps when you want to compare separate tasks or watch more than one session. The release also adds a worktree cleanup view so you can see how much disk space inactive session worktrees use and choose which ones to remove. Review a worktree before deleting it if it contains uncommitted work you may still need.</p>
<h2>A safe rollout checklist</h2>
<ol><li>Enable local sandboxing deliberately and test the filesystem and network rules with a low-risk repository.</li><li>Confirm that credentials, private keys and production data are not unnecessarily available to an agent.</li><li>Check the eligible Copilot plan and organization settings before relying on Claude Haiku 5.5.</li><li>Use <code>/model</code> to inspect supported Ollama models, then test quality and latency on a fixed set of tasks.</li><li>Keep code review and automated tests in place, and inspect diffs before merging.</li><li>Clean up inactive worktrees only after checking for uncommitted changes.</li></ol>
<p>For a separate view of static security analysis, see our <a href="/ai-news/codeql-2-27-2-security-analysis-changes">CodeQL 2.27.2 release guide</a> and our <a href="/tools-guide/github-copilot-code-review-api-guide">Copilot Code Review API guide</a>. Those tools complement agent assistance rather than replacing it.</p>
<h2>Frequently asked questions</h2>
<h3>Is local sandboxing enabled automatically?</h3><p>No. GitHub's documentation says local sandboxing is off by default. Enable it and review the policy for the environment you use.</p>
<h3>Does local sandboxing cost extra?</h3><p>GitHub says local sandboxing is included with Copilot at no extra charge. Cloud sandboxing is separate and billed based on usage.</p>
<h3>Can Copilot CLI use any Ollama model?</h3><p>GitHub describes discovery of supported models from a running Ollama instance. It does not promise compatibility with every Ollama model.</p>
<h2>Sources</h2>
<ul><li><a href="https://github.blog/changelog/2026-10-09-github-copilot-weekly-releases-october-5/" target="_blank" rel="noopener noreferrer">GitHub Changelog: Copilot weekly releases — October 5</a> (published October 9, 2026).</li><li><a href="https://docs.github.com/en/copilot/concepts/security-governance-and-network-settings/about-cloud-and-local-sandboxes" target="_blank" rel="noopener noreferrer">GitHub Docs: About cloud and local sandboxes for GitHub Copilot</a>.</li><li><a href="https://github.blog/changelog/2026-10-07-discover-local-models-in-github-copilot-cli/" target="_blank" rel="noopener noreferrer">GitHub Changelog: Discover local models in GitHub Copilot CLI</a> (October 7, 2026).</li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php';
