<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('google-discover-dive-deeper-ai-2026') ?? ['slug'=>'google-discover-dive-deeper-ai-2026','title'=>'Google Discover “Dive Deeper”: What Publishers Should Watch','description'=>'What Google’s September 2026 Discover experiment means for publishers, referral traffic and AI-search measurement.','category'=>'AI News','date'=>'2026-09-20','read_time'=>'7 min read'];ob_start(); ?>
<p>Google is testing another AI layer inside Discover. On September 18, 2026, Google Search executive Robby Stein described a “Dive deeper” experiment that opens a short AI topic overview with links to related stories, community reactions and original reporting. Google said the test starts with videos and that it will try multiple designs. For publishers, the important question is not whether the feature is permanent. It is whether an extra AI step changes how often a Discover user reaches the original page.</p>
<figure class="article-image"><img src="/assets/images/blog/google-discover-dive-deeper-ai-2026.svg" width="1200" height="630" alt="Google Discover Dive deeper experiment showing a video card, AI overview and source links"></figure>
<h2>What Google has actually confirmed</h2><p>The public description is limited. Google says the experiment is intended to make it easier to explore a topic and discover related web content. Tapping “Dive deeper” opens a short topic overview with prominent links to related stories, community reactions and original reporting. The first test is on videos, and Google plans to experiment with multiple designs.</p><p>There is no public statement yet that gives a universal rollout date, traffic impact, model details or a publisher opt-out process. That means publishers should avoid treating the test as a confirmed permanent change.</p>
<h2>Why the extra step matters</h2><p>Discover has historically been a direct discovery channel: a user sees a card and can open the publisher content. An AI overview adds another decision point. A user may read the summary, choose one of the links, or stop without visiting the original story.</p><p>That does not automatically mean traffic will fall. Better topic exploration could also send users to more relevant stories. The impact will depend on the design, the quality of the links and how much of the answer is visible before a click.</p>
<h2>What publishers should measure</h2><table class="data-table"><thead><tr><th>Metric</th><th>Why it matters</th></tr></thead><tbody><tr><td>Discover impressions</td><td>Shows whether the content is still being surfaced</td></tr><tr><td>Discover clicks</td><td>Measures direct traffic from the feed</td></tr><tr><td>CTR by content type</td><td>Helps compare video-led and article-led discovery</td></tr><tr><td>Engaged sessions</td><td>Shows whether Discover visitors still consume the page</td></tr><tr><td>Brand and direct traffic</td><td>Helps detect users who return later without a Discover referral</td></tr></tbody></table>
<h2>Build a baseline before the test expands</h2><p>If Discover matters to your site, save a baseline now. Export recent Discover performance by page and content type. Record impressions, clicks, CTR and downstream engagement. Then compare those numbers after the experiment becomes visible in your market.</p><p>Do not compare only site-wide totals. A change that affects video-heavy stories may be hidden inside a stable overall number. Segment by template, format, topic and traffic source.</p>
<h2>Make original reporting easy to reach</h2><p>Google’s description specifically mentions original reporting among the links shown in the AI overview. That makes first-hand work even more important. If your site publishes original research, tests, data or reporting, make the core evidence clear on the page and explain what is new.</p><p>Strong headlines still matter, but do not turn them into clickbait. A Discover user who reaches an AI summary before the article needs a clear reason to continue: new evidence, useful detail, a primary source, a practical workflow or an answer the summary cannot replace.</p>
<h2>Do not optimize for an unconfirmed AI ranking formula</h2><p>The test does not reveal a new “Discover AI score.” It also does not show that adding certain headings, word counts or schema will guarantee inclusion. Keep the normal foundations in place: crawlable pages, useful titles, fast mobile rendering, original content and clear information.</p><p>This is similar to how SEOs should approach AI Overviews. Observe the new surface, measure what changes and improve the underlying page rather than chasing a speculative ranking recipe.</p>
<h2>Questions to ask your analytics team</h2><ul><li>Did Discover clicks change after the feature appeared?</li><li>Did CTR change more for video-linked stories than other content?</li><li>Are users spending less time on the original page after a Discover visit?</li><li>Do AI-overview links send a different quality of visitor than direct Discover cards?</li><li>Which original stories continue to attract users after the summary step?</li></ul>
<h2>What remains unknown</h2><p>Google has not published a detailed experiment design, country list, traffic estimate, model specification or final rollout plan. The test may change substantially before broader release. Treat third-party screenshots and observations as evidence about the test, not as a final product specification.</p>
<h2>Frequently asked questions</h2><h3>Is “Dive deeper” a full Google Discover rollout?</h3><p>No. Google described it as an experiment and said it would test multiple designs.</p><h3>Does the feature replace publisher articles?</h3><p>Not based on the current description. Google says the AI overview includes prominent links to related stories, community reactions and original reporting.</p><h3>What should publishers do today?</h3><p>Build a Discover baseline, monitor referral and engagement metrics, and keep improving original content. Avoid making large technical changes based only on an early experiment.</p>
<h2>Sources</h2><ul><li><a href="https://keywordseverywhere.com/news/google-discover/">Keyword Everywhere — Google Discover updates tracker</a></li><li><a href="https://searchengineland.com/google-discover-adds-follow-feature-and-more-social-posts-from-creators-and-publishers-462123">Search Engine Land — Google Discover publisher and creator updates</a></li><li><a href="https://blog.google/products-and-platforms/products/search/discover-updates-september-2025/">Google — Updates to Discover</a></li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php';