<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('how-to-calculate-llm-api-cost-per-task');ob_start(); ?>
<p>To estimate the cost of an AI feature, calculate the tokens used for a real task, apply the current input and output rates for the model, then add tools, retries, retrieval and other usage charges. Do not budget from the advertised price of one million tokens alone. The useful number is the cost per completed task at the quality level your users need.</p>
<figure class="article-image"><img src="/assets/images/blog/how-to-calculate-llm-api-cost-per-task.svg" alt="LLM cost estimate showing input tokens, output tokens, tool charges and total cost per successful task"></figure>
<h2>Start with the full cost formula</h2>
<p>For a text request billed by tokens, a basic estimate is:</p>
<p><strong>Token cost = (input tokens ÷ 1,000,000 × input rate) + (output tokens ÷ 1,000,000 × output rate)</strong></p>
<p>Then add any other charges that apply: cached input, cache writes, tool calls, web search, file or vector storage, image or audio processing, retries and background jobs. The provider's pricing page is the source of truth for its current rates and billing units.</p>
<p>Input and output rates are often different. Some providers also price cached tokens, long-context requests, batch processing, priority service or built-in tools separately. An agent may make several model calls for one user task, so count all of them.</p>
<h2>Work through a simple example</h2>
<p>Assume an application completes 100,000 tasks per month. Each task uses 1,200 input tokens and 300 output tokens. To keep the math simple, assume hypothetical rates of $2 per million input tokens and $8 per million output tokens. These are sample rates for the calculation, not a claim about a current provider's price.</p>
<table class="data-table"><thead><tr><th>Item</th><th>Calculation</th><th>Monthly cost</th></tr></thead><tbody><tr><td>Input</td><td>120 million tokens × $2 ÷ 1 million</td><td>$240</td></tr><tr><td>Output</td><td>30 million tokens × $8 ÷ 1 million</td><td>$240</td></tr><tr><td>Base token cost</td><td>$240 + $240</td><td>$480</td></tr></tbody></table>
<p>If 10% of tasks make one additional attempt with the same average token use, the extra token cost is about $48. That brings the estimate to $528 before tool charges, retrieval, storage or monitoring. Real retry usage can be lower or higher, so replace this assumption with measured data when you have it.</p>
<h2>Measure tokens from real requests</h2>
<p>Do not guess token counts from character length if the application can provide usage data. Log input and output tokens for representative tasks, including system instructions, conversation history, retrieved documents and tool results. A short user message can still create a large request if the system sends a long prompt or repeats context on every turn.</p>
<p>Collect enough examples to cover normal requests and heavier cases. Track median and high-percentile usage rather than relying only on the average. A small number of long documents or agent runs can account for a large share of the bill.</p>
<h2>Count every call in an agent workflow</h2>
<p>A user may see one answer, while the application makes multiple calls behind the scenes. A research agent might search, summarize a page, ask the model to compare sources, validate the result and generate a final answer. Each model call can use input and output tokens. Search, browser, code execution and other tools may also have separate charges.</p>
<p>Build a task-level record that groups all calls under one request ID. Include model name, input tokens, output tokens, cached tokens, tool count, retry count, latency and final task status. Then divide total cost by successful tasks, not just by API calls.</p>
<h2>Include cache, batch and modality costs</h2>
<ul><li><strong>Prompt caching:</strong> if the provider charges a different rate for cached input or cache writes, use the actual cached-token counts and the matching rates.</li><li><strong>Batch processing:</strong> some providers offer a lower rate for work that does not need an immediate response. Confirm the batch terms and turnaround limits.</li><li><strong>Search and tools:</strong> count fixed tool-call charges as well as any model tokens returned by a tool.</li><li><strong>Images, audio and video:</strong> these may use different billing units or token calculations. Do not estimate them as plain text.</li><li><strong>Retries and repair calls:</strong> count calls made after timeouts, malformed output or failed validation.</li><li><strong>Infrastructure:</strong> include storage, retrieval, logs, hosting and monitoring when you are estimating the cost of the whole feature.</li></ul>
<h2>Turn the estimate into a monthly budget</h2>
<p>Use this order:</p>
<ol><li>Estimate monthly completed tasks.</li><li>Measure tokens and tool use for each task type.</li><li>Apply the current rates for the exact model and billing tier.</li><li>Add retries, failed attempts and background processing.</li><li>Add non-token costs such as retrieval, storage and infrastructure.</li><li>Set a budget limit and an alert threshold before launch.</li><li>Compare the estimate with the first real invoices and update your assumptions.</li></ol>
<p>For a multi-model application, calculate each route separately. A small model may handle simple extraction while a more capable model handles difficult cases. But do not switch a task to a cheaper model until it passes the quality checks in our <a href="/tools-guide/how-to-evaluate-ai-models-before-switching">AI model evaluation guide</a>.</p>
<h2>Reduce cost without hiding quality problems</h2>
<p>Trim repeated instructions, limit output length, avoid sending irrelevant history and cache stable context when the provider supports it. Route simple tasks to a smaller model only after testing. If the model needs multiple repair calls because its output is wrong, the cheaper first response may not be cheaper overall.</p>
<p>Track cost per successful result alongside accuracy, latency and failure rate. A low token bill is not a win if users need to repeat requests or staff must fix the output manually. For a provider-specific example, see our <a href="/claude/claude-haiku-5-5-api-pricing-2026">Claude Haiku 5.5 API pricing guide</a>, and always verify the provider's live pricing before using a rate in a forecast.</p>
<h2>Common budgeting mistakes</h2>
<ul><li>Using a consumer subscription price to estimate API usage.</li><li>Applying input rates to output tokens or ignoring cached-token pricing.</li><li>Counting one model call when the task uses an agent loop.</li><li>Ignoring tool charges, failed requests and retries.</li><li>Using only average token counts and missing unusually large requests.</li><li>Assuming a published rate will remain unchanged for the whole budget period.</li></ul>
<h2>Frequently asked questions</h2><h3>What is the best cost metric for an AI feature?</h3><p>Use cost per successful task, together with quality and latency. Cost per API call alone can hide retries and multi-step workflows.</p><h3>Should I use a model's listed token price as my final budget?</h3><p>No. It is only one part of the estimate. Include real token usage, tools, retries, retrieval and other infrastructure costs.</p><h3>How often should I update my cost estimate?</h3><p>Recheck current rates before launch and after provider pricing or model changes. After launch, compare estimates with actual usage and invoices regularly.</p>
<h2>Sources</h2><ul><li><a href="https://developers.openai.com/api/docs/pricing" target="_blank" rel="noopener noreferrer">OpenAI API pricing: token, cache and tool charges</a></li><li><a href="https://claude.com/pricing" target="_blank" rel="noopener noreferrer">Anthropic / Claude pricing page</a></li><li><a href="https://ai.google.dev/gemini-api/docs/pricing" target="_blank" rel="noopener noreferrer">Google AI: Gemini API pricing</a></li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php'; ?>