<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('how-to-use-screaming-frog-json-ld-custom-extraction');ob_start(); ?>
<p>Screaming Frog Custom Extraction can help SEOs inspect structured data and other page elements at scale when a normal crawl report does not expose the exact content you need. The useful approach is to define a focused extraction target, test it on a small sample, and then use the crawl output to find missing, inconsistent or unexpected implementations.</p>
<figure class="article-image"><img src="/assets/images/blog/how-to-use-screaming-frog-json-ld-custom-extraction-2026.svg" alt="Diagram showing a Screaming Frog crawl extracting JSON-LD data for a technical SEO audit"></figure>
<h2>What Custom Extraction is useful for</h2><p>Custom Extraction is most useful when you need a specific value that is not covered by the standard crawl columns. Examples include JSON-LD blocks, specific HTML elements, visible labels, data attributes and implementation patterns.</p><p>It is better to use a narrow extraction than to collect a large amount of HTML that later needs manual cleaning. Define the exact audit question first.</p>
<h2>Why use it for JSON-LD?</h2><p>Structured data can look correct in a browser while containing missing properties, duplicate blocks or inconsistent values across templates. A crawl-level extraction lets you compare pages at scale.</p><p>For example, you can extract the raw JSON-LD script content, then sort or filter the export to see which templates produce different schema types. The extraction itself does not prove that Google's processing will be identical, so validate important findings with the rendered page and Google's documentation.</p>
<h2>How to plan an extraction</h2><table class="data-table"><thead><tr><th>Question</th><th>Useful extraction</th></tr></thead><tbody><tr><td>Which pages contain JSON-LD?</td><td>Script element content for application/ld+json</td></tr><tr><td>Which templates lack a field?</td><td>Specific JSON-LD property or HTML selector</td></tr><tr><td>Do titles contain a pattern?</td><td>Targeted text or element extraction</td></tr><tr><td>Does a template expose a data attribute?</td><td>CSS or XPath-targeted value</td></tr></tbody></table>
<h2>How to test the extraction before a full crawl</h2><p>Start with a small URL sample that covers the site's important templates. Include a normal page, a page you expect to differ, a newly published page and a page known to have the target element.</p><p>Check whether the extraction returns the value you expect and whether blank results are genuinely missing or caused by the extraction rule. This small test prevents a full crawl from generating a misleading export.</p>
<h2>How to audit JSON-LD at scale</h2><p>After the extraction is working, run the crawl and export the values. Group results by schema type, template or directory. Look for pages with no JSON-LD, unexpected schema types, repeated blocks and obvious value inconsistencies.</p><p>Do not treat identical schema as automatically good. The content still needs to match the visible page and follow the relevant structured-data guidelines.</p>
<h2>How to find missing implementations</h2><p>Suppose most product pages contain Product structured data and a group of pages returns a blank extraction. That group becomes a useful investigation queue. Inspect whether those pages use a different template or whether the markup is generated differently.</p><p>The same method works for breadcrumbs, article metadata and other repeated implementation patterns.</p>
<h2>What Custom Extraction cannot prove</h2><p>An extraction shows what your crawl can retrieve. It does not prove that a search engine will display a rich result, that a particular schema item is eligible, or that a page will rank better.</p><p>Use the output as technical evidence for your own site. For Search behavior, use the current Google documentation and appropriate validation tools as separate sources.</p>
<h2>Common Custom Extraction mistakes</h2><p>One mistake is writing a rule that matches only one template. Another is assuming that a blank extraction always means the page is missing the data. A third is exporting huge HTML fields and then trying to inspect them manually.</p><p>Keep each extraction focused on one question and document the rule so another person can reproduce the audit.</p>
<h2>How to combine extraction with crawl filters</h2><p>For large sites, use crawl filters or URL patterns to narrow the problem before exporting. For example, review only blog pages when auditing Article markup or only product directories when checking Product data.</p><p>This reduces noise and makes it easier to find template-level problems.</p>
<h2>How to document the audit</h2><p>Save the crawl date, Screaming Frog version, extraction rule, URL scope and key findings. If the rule changes later, keep the old definition so you can explain why two audits are not directly comparable.</p>
<h2>When this tool is worth using</h2><p>Custom Extraction is most valuable when a site is large enough that manual inspection does not scale, but the audit question is precise enough to express as a selector or extraction rule. It complements normal crawl data rather than replacing manual validation.</p>
<h2>Frequently asked questions</h2><h3>Can Screaming Frog extract JSON-LD?</h3><p>Yes. Custom Extraction can be used to collect targeted page content such as JSON-LD for large-scale inspection, depending on the crawl configuration.</p><h3>Does extraction prove schema is valid?</h3><p>No. It shows what the crawler extracted. Structured-data validity and Search eligibility require separate validation against the current documentation.</p><h3>Should I crawl the whole site first?</h3><p>For rule development, test on a small representative sample first. Then run the full crawl after the extraction produces the expected results.</p>
<h2>Sources</h2><ul><li><a href="https://www.screamingfrog.co.uk/seo-spider/user-guide/configuration/custom-extraction/">Screaming Frog — Custom Extraction</a></li><li><a href="https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data">Google Search Central — Introduction to structured data</a></li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php';