<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('openai-codex-faster-steering-october-2026');ob_start(); ?>
<p>OpenAI announced faster steering for Codex in the ChatGPT desktop app on October 8, 2026. It is designed to let a follow-up instruction change a running coding task sooner. You can choose whether new messages steer the current run or wait in a queue for the next run. The rollout is gradual, so not every account will see the faster behavior at the same time.</p>
<figure class="article-image"><img src="/assets/images/blog/openai-codex-faster-steering-october-2026.svg" alt="A running coding task receives a correction while a separate queued task waits"></figure>
<h2>What faster steering changes</h2>
<p>Codex is an AI coding agent that can read a project, make code changes and help review work. A long task can go off track when the agent misunderstands a requirement or when you notice a missing constraint after it has started. Faster steering is meant to reduce the delay between sending a correction and Codex responding to it.</p>
<p>This is a workflow improvement, not a new model announcement. OpenAI's release note says the desktop app can respond to changes sooner when you send a follow-up while a task is running. It does not promise that every instruction will be applied immediately or that work already completed will automatically be undone.</p>
<h2>Steer and Queue do different jobs</h2>
<p><strong>Steer</strong> adds your message to the current run so Codex can adjust its approach. <strong>Queue</strong> saves the message for the next run, after the current work finishes. Steer is useful when the active task needs a correction now. Queue is better when the next request depends on reviewing the current result first.</p>
<h2>How to change the desktop setting</h2>
<ol><li>Open the ChatGPT desktop app and start or reopen a Codex task in a project you can access.</li><li>Open <strong>Settings → General → Follow-up behavior</strong>.</li><li>Choose whether follow-ups should steer the current run or wait in a queue.</li><li>When Codex is working, send a short correction that says what should change and what must stay unchanged.</li><li>Review the resulting diff, tests and command output before accepting the change.</li></ol>
<p>OpenAI says queued messages appear above the composer, where you can edit, reorder, send or delete them.</p>
<h2>Examples of useful steering messages</h2>
<p>Try a clear instruction such as: “Stop the broad refactor. Keep the public function names and current file layout. Fix only the failing validation path, add a regression test, and show me the diff before making other changes.” This gives Codex a concrete boundary instead of a vague request to try again.</p>
<p>If the agent has already changed files or run commands, inspect the result rather than assuming a new message reverses earlier actions. Use your project's normal tests and review process before merging code.</p>
<h2>When to steer and when to queue</h2>
<table class="data-table"><thead><tr><th>Situation</th><th>Choice</th><th>Reason</th></tr></thead><tbody><tr><td>The agent is using the wrong approach</td><td>Steer</td><td>The current run needs a correction.</td></tr><tr><td>You need to add a missing requirement now</td><td>Steer</td><td>The active task should account for it.</td></tr><tr><td>You want a separate task after reviewing the diff</td><td>Queue</td><td>The next task depends on the first result.</td></tr></tbody></table>
<h2>Availability and limits</h2>
<p>OpenAI says faster steering is rolling out in the ChatGPT desktop app and availability varies. The release note does not list a separate price for this change. Codex access, usage limits and workspace controls still depend on the account and plan. Codex Cloud has separate eligibility and workspace requirements, so do not assume a desktop steering update grants cloud access.</p>
<p>OpenAI's help page also describes steering and queuing in Codex CLI, where Enter steers a running task and Tab queues a follow-up. That existing CLI behavior is separate from the faster-steering rollout announced for desktop.</p>
<p>For related developer context, see our <a href="/chatgpt/openai-devday-2026-recap-developers">OpenAI DevDay developer recap</a> and our <a href="/chatgpt/openai-dots-always-on-agents-guide">guide to OpenAI Dots</a>.</p>
<p>For a different point in the Codex workflow, see our <a href="/chatgpt/codex-composer-predictions-beta-access-controls">guide to Composer predictions</a>, which covers suggestions for the next message after a response finishes.</p>
<h2>Frequently asked questions</h2><h3>Where is the setting?</h3><p>In the ChatGPT desktop app, open Settings, then General, then Follow-up behavior.</p><h3>Does steering undo earlier changes?</h3><p>Do not assume it does. Inspect the diff and tests, then request a correction or revert if needed.</p><h3>Is faster steering available to every user?</h3><p>OpenAI says it is rolling out, and availability varies.</p>
<h2>Sources</h2><ul><li><a href="https://help.openai.com/en/articles/6825453-chatgpt-release-notes" target="_blank" rel="noopener noreferrer">OpenAI: ChatGPT release notes, October 8, 2026</a></li><li><a href="https://help.openai.com/en/articles/11369540-using-codex-with-your-chatgpt-plan" target="_blank" rel="noopener noreferrer">OpenAI: Using Codex with your ChatGPT plan</a></li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php'; ?>