<?php require __DIR__.'/../includes/bootstrap.php';$post=post_by_slug('postman-agent-mode-amazon-bedrock-architecture');ob_start(); ?>
<p>A technical post published by AWS and Postman on October 9, 2026, explains how Postman built Agent Mode for a large developer audience using Amazon Bedrock. The main lesson is not that one model solves every problem: production agents need a carefully limited tool set, task-specific context, approval before state-changing actions, and deliberate choices about model routing, data retention and prompt caching.</p>
<figure class="article-image"><img src="/assets/images/blog/postman-agent-mode-amazon-bedrock-architecture.svg" alt="Production agent architecture showing scoped tools, selected context, Amazon Bedrock inference and human approval"></figure>
<h2>What the case study covers</h2>
<p>Postman Agent Mode lets users work across API testing, documentation, discovery and implementation using natural language. The AWS Machine Learning Blog describes how Postman runs it on Amazon Bedrock rather than managing its own model-serving infrastructure. The article is a technical account from the companies, not an independent benchmark or a public reference implementation; Postman says its production implementation is proprietary.</p>
<p>That distinction matters when reading the reported scale and test results. The article says Postman serves a community of about 40 million developers and describes internal engineering observations. Those details are useful examples, but they are not a guarantee that another product will see the same results.</p>
<h2>1. Expose only the tools a task needs</h2>
<p>Postman began with many small, precise tools, such as opening a request, updating a field or reading metadata. That made individual actions easier to control, but long workflows required many sequential tool calls. The team also found that the model sometimes chose a wrong or nonexistent tool when the visible catalog became too large.</p>
<p>In Postman's testing, tool-selection errors increased once the visible tool set exceeded roughly 40 tools. Its described architecture uses a root agent to search a catalog of more than 170 tools and narrow the list to about 15 relevant tools for a request, then hands those tools to a context-isolated sub-agent. These figures describe Postman's own experience, not a universal threshold for all models or applications.</p>
<p>The practical lesson is to treat tool descriptions and tool count as part of the context budget. Give an agent the smallest set of tools that can complete the task. Use clear names and argument schemas, separate read operations from write operations, and avoid exposing dangerous actions unless they are needed.</p>
<h2>2. Use schema-aware reads instead of a tool for every question</h2>
<p>For structured data, Postman combined several narrow views into a query tool that works with known table schemas. The agent can then compose queries that aggregate requests, errors and latency rather than calling a separate tool for every metric. This reduces the number of actions the model must choose from, while shifting more responsibility to data modeling and query validation.</p>
<p>A similar pattern can work in analytics systems: expose a safe, read-only query interface with an explicit schema, permitted tables, row limits and query budgets. Validate generated queries before execution. Read access is not automatically harmless; a query can still expose sensitive records or create a large bill if permissions and cost controls are weak.</p>
<h2>3. Build context for reasoning, not for screen rendering</h2>
<p>Postman found that missing context caused more problems than missing capabilities. Its product had accumulated years of UI assumptions: users knew which tab to open or where to find a request, but an agent needed structured information about the active entity, its state and the user's goal.</p>
<p>The team built context handlers that produce the information an agent needs for a particular entity instead of serializing the entire interface data model. It also uses a knowledge base with retrieval-augmented generation (RAG), selecting feature-specific documentation when the current task needs it.</p>
<p>For builders, this means separating broad background context from focused task context. Provide only the relevant repository, request, schema, log or document. Keep long user-generated fields from filling the context window, and retrieve more detail when a task requires it. A larger context window does not remove the need to decide what the model should see.</p>
<h2>4. Use model routing and regional controls deliberately</h2>
<p>The case study says Postman can use supported Anthropic Claude models through Amazon Bedrock and select a model according to workload. A faster model may suit frequent, latency-sensitive interactions, while a larger model may be reserved for tasks that need more reasoning. The article describes model selection as a configuration decision, but actual model availability still depends on Bedrock's supported models and AWS Regions.</p>
<p>Postman also describes using Bedrock cross-Region inference profiles to route requests among allowed destination Regions. Geographic profiles restrict routing to a defined geography; global profiles can route among supported destinations worldwide for more throughput. Those are different trade-offs. A team with a residency requirement should select a profile whose documented boundary meets that requirement and ensure its IAM and service control policies permit only the intended destinations.</p>
<p>Do not assume that choosing a geographic profile means inference runs inside Postman's own AWS environment. The article says processing occurs in eligible AWS Regions for the selected profile. Confirm the current model, profile, supported Regions and contractual requirements before using sensitive data.</p>
<h2>5. Check data retention and PII controls per model</h2>
<p>The AWS post says Amazon Bedrock does not use prompts and completions to train AWS models or distribute them to third parties. It also says Postman configured zero data retention for supported Agent Mode models using the relevant retention setting. The qualification is important: retention behavior is model-dependent, so teams should check the current Bedrock data-protection documentation for every model they plan to use rather than generalizing one configuration to the whole model family.</p>
<p>Postman also uses Amazon Bedrock Guardrails to redact personally identifiable information before it reaches the underlying model; enterprise administrators can enable this in Agent Mode settings. Redaction and retention controls reduce some risks, but they do not replace access controls, least-privilege permissions, logging, incident response or careful testing of prompts and tools.</p>
<h2>6. Cache stable context to reduce repeated work</h2>
<p>Agent conversations often resend the same system instructions, core tool definitions and product knowledge. The AWS article says Postman uses two prompt-cache checkpoints: a one-hour checkpoint for stable core context and a five-minute checkpoint for more variable context. The longer-lived cache can spread its write cost over more reads, while the shorter checkpoint suits content that changes more often.</p>
<p>Supported cache time-to-live options and benefits depend on the selected model. Teams should measure cache reads, cache writes, time to first token and cost for their own traffic. Caching is not automatically cheaper for every workload, especially if the prompt prefix changes frequently or the application has few repeated requests.</p>
<h2>A practical checklist for production agents</h2>
<ol><li>Map each task to a small set of read and write tools.</li><li>Use schemas and validation for queries and tool arguments.</li><li>Build task-specific context handlers instead of passing raw UI state.</li><li>Require explicit user approval before actions that modify important state.</li><li>Choose models and inference profiles based on task quality, latency, cost and permitted processing geography.</li><li>Verify retention behavior for each model and enable PII guardrails where they fit the workflow.</li><li>Measure prompt-cache hit rates, latency, token use and failed tool selections under real traffic.</li><li>Keep a human review path for uncertain or high-impact actions.</li></ol>
<p>For a practical approval framework, see our <a href="/ai-news/ai-agent-approval-policy-template">AI agent approval policy template</a>. For API workflows, our <a href="/tools-guide/how-to-design-reliable-ai-api-retries-and-fallbacks">guide to safe retries and fallbacks</a> covers failure handling around model and tool calls.</p>
<h2>Frequently asked questions</h2>
<h3>Did AWS announce a new Amazon Bedrock model in this post?</h3><p>No. The October 9 article is a technical case study about how Postman uses Bedrock for Agent Mode. It focuses on architecture, routing, retention and caching.</p>
<h3>Is Postman's production implementation open source?</h3><p>No. The article says the production implementation is proprietary and is not available as a public sample repository.</p>
<h3>Does zero data retention apply to every Claude model?</h3><p>The article says the configuration is model-dependent. Confirm the current retention behavior for each model and inference configuration you plan to use.</p>
<h2>Sources</h2>
<ul><li><a href="https://aws.amazon.com/blogs/machine-learning/how-postman-runs-agent-mode-for-40-million-developers-on-amazon-bedrock/" target="_blank" rel="noopener noreferrer">AWS Machine Learning Blog: How Postman runs Agent Mode for 40 million developers on Amazon Bedrock</a> (October 9, 2026).</li><li><a href="https://learning.postman.com/docs/getting-started/basics/about-agent-mode/" target="_blank" rel="noopener noreferrer">Postman Docs: About Agent Mode</a>.</li></ul>
<?php $articleHtml=ob_get_clean();require __DIR__.'/../includes/blog-template.php';
