<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('logistics','delivery-sla-calculator');
ob_start();
?>
<h2>Calculate a delivery SLA deadline</h2><p class="lead">Start from dispatch time, choose the SLA clock, exclude holidays when needed, and compare an actual delivery timestamp.</p>
<div class="form-grid"><div class="field"><label for="start">Dispatch date/time</label><input id="start" type="datetime-local" value="2026-09-18T10:00"></div><div class="field"><label for="amount">SLA amount</label><input id="amount" type="number" min="0" step="any" value="2"></div><div class="field"><label for="unit">SLA unit</label><select id="unit"><option value="hours">Elapsed hours</option><option value="days">Calendar days</option><option value="business" selected>Business days</option></select></div><div class="field"><label for="actual">Actual delivery (optional)</label><input id="actual" type="datetime-local"></div></div>
<div class="field full"><label for="holidays">Excluded holidays for business-day mode (YYYY-MM-DD, comma/new line)</label><textarea id="holidays" rows="3" placeholder="2026-10-02, 2026-10-20"></textarea></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate SLA</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Promised by</span><strong id="deadline">—</strong></div><div class="metric"><span>Actual status</span><strong id="status">Not entered</strong></div><div class="metric"><span>Variance</span><strong id="variance">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);function holidaySet(){return new Set($('holidays').value.split(/[\s,]+/).map(x=>x.trim()).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)))}function key(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}function business(d,hs){return d.getDay()!==0&&d.getDay()!==6&&!hs.has(key(d))}function addBusiness(start,n,hs){const d=new Date(start);const whole=Math.floor(n),frac=n-whole;let c=0;while(c<whole){d.setDate(d.getDate()+1);if(business(d,hs))c++}if(frac>0){do{d.setDate(d.getDate()+1)}while(!business(d,hs));d.setTime(d.getTime()+frac*86400000)}return d}function go(){const s=new Date($('start').value),a=parseFloat($('amount').value),u=$('unit').value;if(!Number.isFinite(s.getTime())||!(a>=0)){$('deadline').textContent='—';$('note').textContent='Enter a valid dispatch time and non-negative SLA amount.';$('note').className='helper danger';return}let d;if(u==='hours')d=new Date(s.getTime()+a*3600000);else if(u==='days')d=new Date(s.getTime()+a*86400000);else d=addBusiness(s,a,holidaySet());$('deadline').textContent=d.toLocaleString();const av=$('actual').value;if(av){const act=new Date(av),diff=act-d;$('status').textContent=diff<=0?'Met':'Missed';const hrs=Math.abs(diff)/3600000;$('variance').textContent=hrs.toFixed(2)+' h '+(diff<=0?'early/on time':'late')}else{$('status').textContent='Not entered';$('variance').textContent='—'}$('note').textContent=u==='business'?'Business-day mode excludes Saturdays, Sundays and the holidays you entered. Cutoff times, carrier calendars and time zones still need to match the governing SLA.':'Elapsed mode uses continuous time from the entered dispatch timestamp.';$('note').className='helper'}['start','amount','unit','actual','holidays'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;go()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>Delivery SLA calculator for promised-by dates</h2><p>A delivery service-level agreement can be defined in elapsed hours, calendar days or working days. This calculator keeps those clocks separate because “48 hours” and “2 business days” can produce very different deadlines around weekends and holidays.</p>
<h2>Business-day calculation</h2><p>Business-day mode moves through the calendar one day at a time, excluding Saturday, Sunday and any YYYY-MM-DD holiday dates you supply. The original time of day is preserved. A fractional business day is treated as a fraction of 24 elapsed hours after reaching the next business day, so use whole business days unless your contract defines fractional-day handling.</p>
<h2>Cutoff times and carrier calendars matter</h2><p>Many fulfillment SLAs begin only if an order is accepted before a cutoff, and carriers can use local calendars, service zones and exceptions. Enter the actual contractual start timestamp after any cutoff rule has been applied. If warehouses and customers are in different time zones, normalize timestamps before comparing them.</p>
<h2>Use the variance for operations analysis</h2><p>When an actual delivery is entered, the calculator shows whether the shipment met the calculated deadline and the time variance. Aggregate that result across orders to build on-time-delivery or SLA-compliance KPIs rather than judging a network from one shipment.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the difference between calendar days and business days?','Calendar days count every day. Business-day mode here excludes weekends plus the holiday dates you provide.'],['Does this calculator apply carrier cutoff times automatically?','No. Cutoffs vary by carrier, service and origin. Enter the dispatch/SLA start time after applying the relevant contractual cutoff rule.'],['Can I use this across time zones?','Yes if you first convert dispatch and actual-delivery timestamps into a consistent time zone. The browser datetime-local field does not carry a time-zone identifier.'],['How is SLA variance calculated?','It is actual delivery time minus the promised deadline. A non-positive value means delivered by the calculated deadline.']];
require __DIR__.'/../includes/tool-template.php';
