<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('logistics','incoterm-cost-split-calculator');
ob_start();
?>
<h2>Estimate an Incoterm cost split</h2><p class="lead">Apply a simplified Incoterms 2020 payer preset to common cost components, then review or override each allocation before totaling seller and buyer costs.</p>
<div class="form-grid"><div class="field"><label for="term">Incoterm 2020 rule</label><select id="term"><option>EXW</option><option>FCA</option><option>FAS</option><option>FOB</option><option>CFR</option><option>CIF</option><option>CPT</option><option>CIP</option><option>DAP</option><option>DPU</option><option>DDP</option></select></div><div class="field"><label for="currency">Currency symbol</label><input id="currency" value="$" maxlength="4"></div></div>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Cost component</th><th>Amount</th><th>Payer</th></tr></thead><tbody id="rows"></tbody></table></div>
<div class="tool-actions"><button class="btn btn-primary" id="preset" type="button">Apply term preset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Seller-allocated cost</span><strong id="seller">—</strong></div><div class="metric"><span>Buyer-allocated cost</span><strong id="buyer">—</strong></div><div class="metric"><span>Unallocated / optional</span><strong id="other">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);const comps=[['origin','Origin handling / pickup',200],['export','Export clearance',75],['main','Main carriage',1200],['insurance','Cargo insurance',80],['import','Import clearance',100],['duty','Import duties / taxes',350],['dest','Destination handling',150],['unload','Unloading at named destination',100],['final','Final delivery',250]];const preset={EXW:{},FCA:{origin:'seller',export:'seller',main:'buyer'},FAS:{origin:'seller',export:'seller',main:'buyer'},FOB:{origin:'seller',export:'seller',main:'buyer'},CFR:{origin:'seller',export:'seller',main:'seller'},CIF:{origin:'seller',export:'seller',main:'seller',insurance:'seller'},CPT:{origin:'seller',export:'seller',main:'seller'},CIP:{origin:'seller',export:'seller',main:'seller',insurance:'seller'},DAP:{origin:'seller',export:'seller',main:'seller',dest:'seller',final:'seller'},DPU:{origin:'seller',export:'seller',main:'seller',dest:'seller',unload:'seller',final:'seller'},DDP:{origin:'seller',export:'seller',main:'seller',import:'seller',duty:'seller',dest:'seller',final:'seller'}};function render(){const tb=$('rows');tb.innerHTML='';comps.forEach(([id,label,v])=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${label}</td><td><input id="amt-${id}" type="number" min="0" step="any" value="${v}" style="max-width:130px"></td><td><select id="pay-${id}"><option value="seller">Seller</option><option value="buyer">Buyer</option><option value="unallocated">Unallocated / contract-specific</option></select></td>`;tb.appendChild(tr);tr.querySelector('input').addEventListener('input',calc);tr.querySelector('select').addEventListener('change',calc)});apply()}function apply(){const t=$('term').value,p=preset[t]||{};comps.forEach(([id])=>{$('pay-'+id).value=p[id]||((['import','duty','dest','unload','final'].includes(id)||t==='EXW')?'buyer':'unallocated')});if(!['CIF','CIP'].includes(t))$('pay-insurance').value='unallocated';calc()}function calc(){let s=0,b=0,u=0;comps.forEach(([id])=>{const a=parseFloat($('amt-'+id).value)||0,p=$('pay-'+id).value;if(p==='seller')s+=a;else if(p==='buyer')b+=a;else u+=a});const c=$('currency').value||'';$('seller').textContent=c+s.toLocaleString(undefined,{maximumFractionDigits:2});$('buyer').textContent=c+b.toLocaleString(undefined,{maximumFractionDigits:2});$('other').textContent=c+u.toLocaleString(undefined,{maximumFractionDigits:2});$('note').textContent='Preset is a planning aid only. Incoterms allocate obligations, costs and risk at defined delivery points; named place/port, carriage contracts, terminal charges, insurance scope and local law can change the commercial total. Review the sale contract.'}$('term').addEventListener('change',apply);$('currency').addEventListener('input',calc);$('preset').onclick=apply;render()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>Incoterms 2020 cost split calculator</h2><p>ICC Incoterms 2020 rules define seller and buyer obligations for delivery, risk, carriage-related tasks, export/import formalities and certain costs. They are not simply a “who pays freight” code. The named place or port is part of the rule and can materially change where delivery and risk transfer occur. <a href="https://iccwbo.org/business-solutions/incoterms-rules/" target="_blank" rel="noopener">ICC Incoterms rules information</a>.</p>
<h2>How to use this calculator</h2><p>Select a rule to load a simplified payer preset, enter your actual cost estimates, and then review every payer cell. The preset intentionally leaves cargo insurance unallocated except under CIF and CIP, because most other Incoterms rules do not require either party to obtain cargo insurance even though one party may choose to do so.</p>
<h2>Cost allocation is not the same as risk transfer</h2><p>Under some “C” rules the seller pays main carriage to a destination while risk transfers earlier. Do not infer risk transfer from the larger cost total. Use the exact Incoterms 2020 rule and named location in the sales contract, and separately review insurance and carrier terms.</p>
<h2>Important exclusions</h2><p>This estimator cannot encode every terminal handling charge, local customs practice, VAT/GST treatment, security filing, container demurrage or contract variation. DDP can create especially significant import-tax and registration obligations for the seller. Use the calculator for quote comparison and landed-cost planning, then validate with trade/compliance professionals.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Do Incoterms decide who owns the goods?','No. Incoterms address delivery obligations, costs and risk allocation, not title/ownership or payment terms unless the contract separately defines them.'],['Which Incoterms require seller-arranged insurance?','CIF and CIP include seller insurance obligations, with different prescribed coverage levels under Incoterms 2020. Other terms do not automatically require cargo insurance.'],['Why are some costs marked unallocated?','Because insurance, terminal fees and contract-specific carriage items cannot always be assigned accurately from the three-letter rule alone without the named place and contract details.'],['Can I use FOB for container shipments?','ICC guidance often points to FCA where goods are handed to a carrier before loading on board; choose the rule that matches the actual delivery process and obtain trade advice when needed.']];
require __DIR__.'/../includes/tool-template.php';
