<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('logistics','vehicle-utilization-calculator');
ob_start();
?>
<h2>Calculate fleet vehicle utilization</h2><p class="lead">Measure how much available fleet time is productive and what share of traveled distance is loaded.</p>
<div class="form-grid"><div class="field"><label for="vehicles">Vehicles</label><input id="vehicles" type="number" min="1" step="1" value="10"></div><div class="field"><label for="avail">Available hours per vehicle</label><input id="avail" type="number" min="0" step="any" value="10"></div><div class="field"><label for="prod">Total productive/engaged hours</label><input id="prod" type="number" min="0" step="any" value="72"></div><div class="field"><label for="distance">Total distance</label><input id="distance" type="number" min="0" step="any" value="1800"></div><div class="field"><label for="loaded">Loaded/revenue distance</label><input id="loaded" type="number" min="0" step="any" value="1350"></div></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Time utilization</span><strong id="time">—</strong></div><div class="metric"><span>Loaded-distance ratio</span><strong id="load">—</strong></div><div class="metric"><span>Productive h / vehicle</span><strong id="per">—</strong></div><div class="metric"><span>Empty distance</span><strong id="empty">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);function go(){const v=+$('vehicles').value,a=+$('avail').value,p=+$('prod').value,d=+$('distance').value,l=+$('loaded').value;if(!(v>0&&a>=0&&p>=0&&d>=0&&l>=0&&l<=d)){['time','load','per','empty'].forEach(id=>$(id).textContent='—');$('note').textContent='Loaded distance cannot exceed total distance.';$('note').className='helper danger';return}const cap=v*a;$('time').textContent=cap>0?(p/cap*100).toFixed(1)+'%':'—';$('load').textContent=d>0?(l/d*100).toFixed(1)+'%':'—';$('per').textContent=(p/v).toFixed(2)+' h';$('empty').textContent=(d-l).toLocaleString(undefined,{maximumFractionDigits:2});$('note').textContent=p>cap&&cap>0?'Productive hours exceed the entered available fleet hours; check whether availability or productive-hour scope is inconsistent.':'Track the same definitions over time—especially whether waiting, maintenance and repositioning count as available or productive.';$('note').className='helper'+(p>cap&&cap>0?' danger':'')}['vehicles','avail','prod','distance','loaded'].forEach(id=>$(id).addEventListener('input',go));go()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>Fleet vehicle utilization metrics</h2><p>Vehicle utilization can mean several things, so this calculator keeps time and distance measures separate. Time utilization compares productive vehicle-hours with fleet hours made available. Loaded-distance ratio compares loaded/revenue distance with all distance traveled.</p>
<h2>Time utilization formula</h2><p><strong>Available fleet hours = vehicles × available hours per vehicle</strong>. <strong>Time utilization = productive hours ÷ available fleet hours × 100</strong>. Define “productive” consistently—for example, driving loaded, any dispatched movement, or all billable service time.</p>
<h2>Loaded distance and empty running</h2><p><strong>Loaded-distance ratio = loaded distance ÷ total distance × 100</strong>. The complement is empty/repositioning distance. A lower empty ratio can indicate better backhaul or routing, but some empty movement is operationally unavoidable.</p>
<h2>Compare like with like</h2><p>Daily, weekly and route-level comparisons are only meaningful when availability, maintenance downtime, waiting, driver-hour limits and subcontracted vehicles are treated consistently. Use the ratios as diagnostic KPIs alongside on-time service, cost, safety and asset reliability.</p>
<h2>Segment utilization before changing fleet size</h2><p>A fleet-wide average can hide underused vehicles alongside a few overloaded assets. Break the calculation down by depot, vehicle class, route, day and time window before concluding that the fleet is too large or too small. Also distinguish planned reserve capacity from accidental idle time. Some spare capacity is valuable for maintenance, seasonal peaks and service recovery, so the objective is not necessarily 100% utilization.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What counts as productive vehicle hours?','Use the definition your operation manages consistently, such as dispatched service time or billable/loaded service time. Document the rule before benchmarking.'],['Can vehicle utilization exceed 100%?','It should not if productive and available hours use the same scope. A value above 100% usually signals inconsistent inputs or overtime beyond the stated availability.'],['What is empty running?','Distance traveled without the load/revenue condition used in your loaded-distance definition, including repositioning and some return legs.'],['Is higher utilization always better?','No. Excessive utilization can reduce maintenance windows and resilience. Consider service, safety, driver constraints and asset condition alongside utilization.']];
require __DIR__.'/../includes/tool-template.php';
