<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('photography-video','depth-of-field-calculator');
ob_start();
?>
<h2>Estimate depth of field</h2><p class="lead">Calculate hyperfocal, near-focus and far-focus limits from focal length, aperture, focus distance and circle of confusion.</p><div class="notice">This is a geometric depth-of-field estimate, not a guarantee of perceived sharpness. Diffraction, lens performance, focus accuracy and final viewing conditions also matter.</div><div class="form-grid"><div class="field"><label for="f">Focal length (mm)</label><input id="f" type="number" value="50" min="1" step="any"></div><div class="field"><label for="n">Aperture (f-number)</label><input id="n" type="number" value="2.8" min="0.5" step="any"></div><div class="field"><label for="s">Focus distance (m)</label><input id="s" type="number" value="3" min="0.01" step="any"></div><div class="field"><label for="c">Circle of confusion (mm)</label><input id="c" type="number" value="0.03" min="0.001" step="any"><small class="helper">0.030 mm is a common full-frame planning value; use a value appropriate to your format and output.</small></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Hyperfocal distance</span><strong id="hyper">—</strong></div><div class="metric"><span>Near limit</span><strong id="near">—</strong></div><div class="metric"><span>Far limit</span><strong id="far">—</strong></div><div class="metric"><span>Total depth of field</span><strong id="dof">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('hyper').textContent='—';$('near').textContent='—';$('far').textContent='—';$('dof').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const f=num('f'),N=num('n'),sm=num('s'),c=num('c');if(!(f>0&&N>0&&sm>0&&c>0))throw 0;const s=sm*1000;const H=f*f/(N*c)+f;const near=H*s/(H+(s-f));let far=Infinity;if(H>(s-f))far=H*s/(H-(s-f));$('hyper').textContent=fmt(H/1000,2)+' m';$('near').textContent=fmt(near/1000,2)+' m';$('far').textContent=Number.isFinite(far)?fmt(far/1000,2)+' m':'∞';$('dof').textContent=Number.isFinite(far)?fmt((far-near)/1000,2)+' m':'From '+fmt(near/1000,2)+' m to ∞';$('note').textContent='Depth of field is an optical planning estimate. Circle of confusion depends on format, viewing size, viewing distance and sharpness expectations.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Depth of Field Calculator works</h2><p>The calculator uses the standard thin-lens depth-of-field relationships. Hyperfocal distance is approximated as H = f²/(N×c) + f, where f is focal length, N is f-number and c is the chosen circle of confusion. The near and far limits are then calculated from hyperfocal distance and subject distance.</p><h2>How to use this depth of field calculator</h2><p>Enter the actual focal length in millimetres, the working aperture, focus distance and a circle-of-confusion value suitable for your camera format and output. The common 0.030 mm full-frame value is a planning convention, not a property of the sensor. For critical work, use a stricter value that reflects the intended print size or viewing conditions.</p><h2>How to interpret the result</h2><p>The near and far limits describe the region predicted to meet the selected acceptable-blur criterion. When the far limit reaches infinity, the focus distance is at or beyond the hyperfocal relationship for the current settings. Stopping down, using a shorter focal length or increasing focus distance generally increases depth of field, consistent with manufacturer guidance.</p><h2>Assumptions and limitations</h2><p>The model assumes a simple optical system and an agreed circle of confusion. It does not model diffraction, focus breathing, field curvature, lens aberrations, subject motion, tilt/shift movements or pixel-level sharpness. Macro distances need more advanced magnification-aware treatment, so treat very close-focus results as approximate.</p><h2>Practical example and workflow</h2><p>For a 50 mm lens at f/2.8 focused at 3 m with a 0.030 mm circle of confusion, the calculator shows a relatively narrow focus region. A landscape photographer can compare that with f/8 or a wider lens to see how the near limit and hyperfocal distance change before deciding where to focus.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What circle of confusion should I use?','Use a value appropriate to the camera format and final viewing conditions. 0.030 mm is a common full-frame planning convention, but it is not universally correct.'],['Does a higher f-number increase depth of field?','Generally yes. A smaller physical aperture, represented by a higher f-number, increases calculated depth of field, although diffraction can reduce fine detail at very small apertures.'],['Why does the far limit sometimes show infinity?','The far depth-of-field limit becomes infinite when the focus-distance relationship reaches the hyperfocal condition for the chosen focal length, aperture and circle of confusion.'],['Is this accurate for macro photography?','Not fully. At high magnification, effective aperture and magnification-aware depth-of-field relationships become important, so use a macro-specific method for critical close-up work.']];
require __DIR__.'/../includes/tool-template.php';
