<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('photography-video','exposure-stop-calculator');
ob_start();
?>
<h2>Compare exposure settings in stops</h2><p class="lead">Compare two shutter, aperture and ISO combinations and see the net exposure change.</p><div class="notice">A one-stop change is a factor of two in exposure. Aperture changes affect exposure with the square of the f-number ratio.</div><div class="form-grid"><div class="field"><label for="t1">Baseline shutter time (seconds)</label><input id="t1" type="number" value="0.008" min="0.000001" step="any"><small class="helper">Example: 1/125 s = 0.008</small></div><div class="field"><label for="n1">Baseline aperture</label><input id="n1" type="number" value="4" min="0.5" step="any"></div><div class="field"><label for="iso1">Baseline ISO</label><input id="iso1" type="number" value="100" min="1" step="any"></div><div class="field"><label for="t2">New shutter time (seconds)</label><input id="t2" type="number" value="0.004" min="0.000001" step="any"></div><div class="field"><label for="n2">New aperture</label><input id="n2" type="number" value="2.8" min="0.5" step="any"></div><div class="field"><label for="iso2">New ISO</label><input id="iso2" type="number" value="100" min="1" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Shutter change</span><strong id="shutter">—</strong></div><div class="metric"><span>Aperture change</span><strong id="aperture">—</strong></div><div class="metric"><span>ISO change</span><strong id="iso">—</strong></div><div class="metric"><span>Net exposure change</span><strong id="net">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('shutter').textContent='—';$('aperture').textContent='—';$('iso').textContent='—';$('net').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const t1=num('t1'),n1=num('n1'),i1=num('iso1'),t2=num('t2'),n2=num('n2'),i2=num('iso2');if(!(t1>0&&n1>0&&i1>0&&t2>0&&n2>0&&i2>0))throw 0;const ss=Math.log2(t2/t1),as=2*Math.log2(n1/n2),is=Math.log2(i2/i1),net=ss+as+is;const fs=v=>(v>=0?'+':'')+fmt(v,2)+' stops';$('shutter').textContent=fs(ss);$('aperture').textContent=fs(as);$('iso').textContent=fs(is);$('net').textContent=fs(net);$('note').textContent=Math.abs(net)<0.05?'The two settings are essentially exposure-equivalent by this model.':'Positive means a brighter recorded result; negative means darker, before scene or processing changes.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Exposure Stop Calculator works</h2><p>Exposure changes are conveniently expressed in stops because one stop represents a doubling or halving. For shutter time the stop change is log2(new time ÷ old time). Aperture uses two times log2(old f-number ÷ new f-number) because aperture area changes with the square of the f-number. ISO is compared as log2(new ISO ÷ old ISO).</p><h2>How to use this exposure stop calculator</h2><p>Enter the baseline exposure triangle and the new settings. Shutter time is entered in seconds, so 1/125 second is 0.008 and 1/1000 is 0.001. The calculator reports each component separately and then sums the stop changes. This makes it easy to verify whether one change was compensated by another.</p><h2>How to interpret the result</h2><p>A net result near zero means the two combinations are exposure-equivalent in the simple exposure model. A positive result is brighter and a negative result is darker. The separate component values are useful for understanding trade-offs: faster shutter reduces motion blur, wider aperture reduces depth of field, and higher ISO changes camera amplification/noise behavior.</p><h2>Assumptions and limitations</h2><p>The calculation does not know the scene luminance, flash contribution, lens transmission (T-stops), auto-ISO logic, highlight headroom or sensor response. Nominal shutter, f-number and ISO markings can also differ slightly from measured values. Treat stop arithmetic as a planning and comparison tool rather than a metrology result.</p><h2>Practical example and workflow</h2><p>Changing from 1/125 s at f/4 to 1/250 s at f/2.8 keeps ISO constant. The shutter loses about one stop while the wider aperture gains about one stop, producing a net result close to zero. That is a practical way to trade depth of field for motion control without changing nominal brightness.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How much is one stop of exposure?','One stop is a factor of two: twice as much or half as much exposure depending on direction.'],['Why is aperture calculated differently from shutter speed?','The f-number is related to aperture diameter, while light-gathering area changes with the square of diameter, so the exposure relationship uses the squared f-number ratio.'],['Does doubling ISO always equal one stop?','In standard exposure arithmetic, doubling the ISO setting is treated as one stop, although measured camera response can differ from nominal labels.'],['What does a zero net stop change mean?','It means the shutter, aperture and ISO changes compensate mathematically, so the two settings are nominally exposure-equivalent.']];
require __DIR__.'/../includes/tool-template.php';
