<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('photography-video','frame-rate-duration-converter');
ob_start();
?>
<h2>Convert frame rate and clip duration</h2><p class="lead">Calculate total frames, source duration and retimed playback duration when frame rate changes.</p><div class="notice">Use this for conforming footage or timelapse planning. It does not model frame blending, optical flow or drop-frame timecode conventions.</div><div class="form-grid"><div class="field"><label for="duration">Recorded duration (seconds)</label><input id="duration" type="number" value="10" min="0.001" step="any"></div><div class="field"><label for="src">Source frame rate (fps)</label><input id="src" type="number" value="60" min="0.001" step="any"></div><div class="field"><label for="dst">Playback / timeline frame rate (fps)</label><input id="dst" type="number" value="24" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Total frames</span><strong id="frames">—</strong></div><div class="metric"><span>Playback duration</span><strong id="play">—</strong></div><div class="metric"><span>Playback speed</span><strong id="speed">—</strong></div><div class="metric"><span>Duration multiplier</span><strong id="factor">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('frames').textContent='—';$('play').textContent='—';$('speed').textContent='—';$('factor').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const d=num('duration'),s=num('src'),p=num('dst');if(!(d>0&&s>0&&p>0))throw 0;const frames=d*s,play=frames/p,speed=p/s*100,m=play/d;$('frames').textContent=fmt(frames,0);$('play').textContent=fmt(play,3)+' s';$('speed').textContent=fmt(speed,2)+'%';$('factor').textContent=fmt(m,3)+'×';$('note').textContent='This assumes every recorded frame is conformed to the target frame rate without frame interpolation or dropping.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Frame Rate Duration Converter works</h2><p>The converter first calculates total captured frames as recorded duration × source frame rate. If those same frames are interpreted at a different playback frame rate, playback duration becomes total frames ÷ target frame rate. Playback speed relative to real time is target fps ÷ source fps.</p><h2>How to use this frame rate duration converter</h2><p>Enter the actual recorded duration and source frame rate, then choose the frame rate at which the existing frames will be played. This is especially useful for 60 fps or 120 fps slow motion conformed to 24/25/30 fps, and for image-sequence or timelapse workflows where frame count is more reliable than clip metadata.</p><h2>How to interpret the result</h2><p>A duration multiplier above 1 means the conformed clip becomes longer, while a speed below 100% indicates slow motion. If the target rate is higher than the source rate, the clip becomes shorter and plays faster when no new frames are synthesized. The total frame count stays constant in this model.</p><h2>Assumptions and limitations</h2><p>The calculation assumes simple frame-rate reinterpretation. Editing software may instead drop, duplicate, blend or synthesize frames. NTSC rates such as 23.976 and 29.97 should be entered with their actual decimal values when precise timing matters. Drop-frame timecode changes counting labels, not the underlying playback rate itself.</p><h2>Practical example and workflow</h2><p>Ten seconds captured at 60 fps contains 600 frames. Conforming those frames to 24 fps produces a 25-second clip at 40% of real-time speed. This lets an editor check the usable slow-motion duration before placing the clip into a timeline.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does changing frame rate change the number of frames?','Not when you are conforming the same captured frames. The frame count stays fixed and playback duration changes.'],['What happens when 60 fps footage is conformed to 24 fps?','The same frames play at 40% speed, so the clip duration becomes 2.5 times longer.'],['Can I enter 23.976 or 29.97 fps?','Yes. Use the actual decimal frame rate when precise timing matters.'],['Does this tool perform frame interpolation?','No. It models simple reinterpretation of existing frames and does not create, blend or discard frames.']];
require __DIR__.'/../includes/tool-template.php';
