<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('photography-video','lens-field-of-view-calculator');
ob_start();
?>
<h2>Calculate lens field of view</h2><p class="lead">Estimate horizontal, vertical and diagonal angle of view plus scene coverage at a chosen distance.</p><div class="notice">Enter physical sensor dimensions, not megapixels. Focal length must be the actual lens focal length rather than a full-frame-equivalent label.</div><div class="form-grid"><div class="field"><label for="sw">Sensor width (mm)</label><input id="sw" type="number" value="36" min="0.1" step="any"></div><div class="field"><label for="sh">Sensor height (mm)</label><input id="sh" type="number" value="24" min="0.1" step="any"></div><div class="field"><label for="f">Focal length (mm)</label><input id="f" type="number" value="50" min="0.1" step="any"></div><div class="field"><label for="dist">Subject distance (m)</label><input id="dist" type="number" value="5" min="0.01" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Horizontal angle</span><strong id="hfov">—</strong></div><div class="metric"><span>Vertical angle</span><strong id="vfov">—</strong></div><div class="metric"><span>Diagonal angle</span><strong id="diag">—</strong></div><div class="metric"><span>Scene width × height</span><strong id="scene">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('hfov').textContent='—';$('vfov').textContent='—';$('diag').textContent='—';$('scene').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const w=num('sw'),h=num('sh'),f=num('f'),d=num('dist');if(!(w>0&&h>0&&f>0&&d>0))throw 0;const deg=x=>x*180/Math.PI;const ha=2*Math.atan(w/(2*f)),va=2*Math.atan(h/(2*f)),da=2*Math.atan(Math.hypot(w,h)/(2*f));const ww=2*d*Math.tan(ha/2),hh=2*d*Math.tan(va/2);$('hfov').textContent=fmt(deg(ha),2)+'°';$('vfov').textContent=fmt(deg(va),2)+'°';$('diag').textContent=fmt(deg(da),2)+'°';$('scene').textContent=fmt(ww,2)+' m × '+fmt(hh,2)+' m';$('note').textContent='Angle of view uses a rectilinear thin-lens approximation. Actual lenses may crop, breathe or distort differently.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Lens Field-of-View Calculator works</h2><p>For a rectilinear lens, angle of view can be approximated as 2 × arctan(sensor dimension ÷ (2 × focal length)). The calculator applies that relationship independently to sensor width, sensor height and sensor diagonal. It then projects the horizontal and vertical angles to estimate scene coverage at the entered subject distance.</p><h2>How to use this lens field-of-view calculator</h2><p>Use the camera sensor’s physical width and height in millimetres and the actual focal length marked on the lens. Add a subject distance to see how much width and height fit across the frame at that distance. This is useful for lens selection, studio layout, architecture, product sets and camera-placement planning.</p><h2>How to interpret the result</h2><p>Shorter focal lengths produce wider angles of view for the same sensor. A larger sensor also sees a wider angle with the same actual focal length. The scene-width output is often more actionable than “crop factor” because it tells you approximately how much of a wall, stage or subject area fits in frame from a known position.</p><h2>Assumptions and limitations</h2><p>The formula is a thin-lens rectilinear approximation. Real lenses can have distortion, focus breathing, internal focusing and manufacturer cropping. Fisheye lenses use different projection models. At very close distances, measuring from the sensor plane and accounting for lens extension can matter, so use manufacturer data for precision setups.</p><h2>Practical example and workflow</h2><p>A full-frame sensor 36 mm wide with a 50 mm lens gives a horizontal field of view around 39.6 degrees. At 5 m, that corresponds to roughly 3.6 m of horizontal scene width, helping a photographer decide whether the camera can cover a group or set from the available distance.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What sensor size should I enter?','Enter the physical active sensor dimensions in millimetres. Do not enter megapixels or crop factor directly.'],['Should I use actual or equivalent focal length?','Use the actual focal length of the lens. The sensor dimensions already account for format differences.'],['Does this work for fisheye lenses?','No. Fisheye lenses use different projection relationships, so a rectilinear field-of-view formula is not appropriate.'],['Why can my real lens show a different field of view?','Lens distortion, focus breathing, internal focusing and camera cropping can cause differences from the ideal geometric estimate.']];
require __DIR__.'/../includes/tool-template.php';
