<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('photography-video','print-resolution-calculator');
ob_start();
?>
<h2>Calculate photo print size from pixels</h2><p class="lead">Convert image pixel dimensions into maximum print dimensions at a chosen PPI and check a custom print size.</p><div class="notice">Adobe distinguishes image resolution in PPI from printer resolution in DPI. The best PPI depends on printer, viewing distance, sharpening and the print provider’s workflow.</div><div class="form-grid"><div class="field"><label for="pxw">Image width (pixels)</label><input id="pxw" type="number" value="6000" min="1" step="1"></div><div class="field"><label for="pxh">Image height (pixels)</label><input id="pxh" type="number" value="4000" min="1" step="1"></div><div class="field"><label for="ppi">Target print resolution (PPI)</label><input id="ppi" type="number" value="300" min="1" step="any"></div><div class="field"><label for="pw">Optional desired print width (inches)</label><input id="pw" type="number" value="20" min="0.01" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Print size at target PPI</span><strong id="max">—</strong></div><div class="metric"><span>Effective PPI at desired width</span><strong id="effective">—</strong></div><div class="metric"><span>Height at desired width</span><strong id="height">—</strong></div><div class="metric"><span>Image megapixels</span><strong id="mp">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('max').textContent='—';$('effective').textContent='—';$('height').textContent='—';$('mp').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const w=num('pxw'),h=num('pxh'),ppi=num('ppi'),pw=num('pw');if(!(w>0&&h>0&&ppi>0&&pw>0))throw 0;const wi=w/ppi,hi=h/ppi,ph=pw*h/w,eff=w/pw;$('max').textContent=fmt(wi,2)+' × '+fmt(hi,2)+' in';$('effective').textContent=fmt(eff,0)+' PPI';$('height').textContent=fmt(ph,2)+' in';$('mp').textContent=fmt(w*h/1e6,2)+' MP';$('note').textContent='PPI describes image pixels per printed inch. Printer DPI is a different device specification; confirm the image-resolution requirement with your lab or print provider.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Print Resolution Calculator works</h2><p>Printed image resolution is measured in pixels per inch. With resampling turned off, print width equals pixel width ÷ PPI and print height equals pixel height ÷ PPI. This tool also works in reverse for a chosen print width by calculating the effective PPI from the existing pixel dimensions.</p><h2>How to use this print resolution calculator</h2><p>Enter the image’s native pixel width and height, then a target PPI such as 300 or the value recommended by your print lab. The maximum-size result shows the physical dimensions that use those pixels without resampling. Enter a desired width to see the matching height and effective resolution for that print size.</p><h2>How to interpret the result</h2><p>PPI is not the same as a printer’s hardware DPI. Adobe’s print guidance treats image resolution and printer resolution as related but distinct concepts. A lower PPI can still look excellent at a larger viewing distance, while a close-viewed fine-art print may benefit from more source detail and careful sharpening.</p><h2>Assumptions and limitations</h2><p>The calculator does not judge image quality, focus, noise, demosaicing, interpolation or sharpening. Cropping reduces available pixels, and borderless printing may enlarge/crop slightly. Some labs resample automatically. Always confirm a provider’s preferred pixel dimensions, color space and sharpening workflow for critical output.</p><h2>Practical example and workflow</h2><p>A 6000 × 4000 image printed at 300 PPI is 20 × 13.33 inches without resampling. If you want a 30-inch-wide print from the same file, effective resolution becomes 200 PPI. That comparison helps you decide whether the larger print is acceptable for its intended viewing distance.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Is PPI the same as printer DPI?','No. PPI describes image pixels per printed inch; DPI describes a printer/output device’s dot placement. They should not be treated as identical numbers.'],['What PPI should I use for photo printing?','Use the print provider’s recommendation and consider viewing distance. 300 PPI is a common planning value, but it is not a universal requirement.'],['Does changing PPI add detail to my image?','Not unless you resample. Without resampling, changing PPI only changes the calculated physical print size for the same pixels.'],['Why does a large print sometimes look good at lower PPI?','Large prints are often viewed from farther away, so the angular size of individual pixels is smaller. Subject detail and sharpening also influence perceived quality.']];
require __DIR__.'/../includes/tool-template.php';
