<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('photography-video','timelapse-storage-calculator');
ob_start();
?>
<h2>Plan timelapse frames and storage</h2><p class="lead">Estimate frame count, card/storage use and final clip duration from interval capture settings.</p><div class="notice">Average frame size varies with RAW/JPEG compression and scene detail. Treat the storage result as an estimate and leave card/headroom for filesystem overhead and bursts.</div><div class="form-grid"><div class="field"><label for="hours">Capture duration (hours)</label><input id="hours" type="number" value="4" min="0.001" step="any"></div><div class="field"><label for="interval">Interval between frames (seconds)</label><input id="interval" type="number" value="5" min="0.001" step="any"></div><div class="field"><label for="size">Average file size per frame (MB)</label><input id="size" type="number" value="25" min="0" step="any"></div><div class="field"><label for="fps">Final video frame rate (fps)</label><input id="fps" type="number" value="24" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Frames captured</span><strong id="frames">—</strong></div><div class="metric"><span>Estimated storage</span><strong id="storage">—</strong></div><div class="metric"><span>Final clip duration</span><strong id="clip">—</strong></div><div class="metric"><span>Real-time compression</span><strong id="ratio">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('frames').textContent='—';$('storage').textContent='—';$('clip').textContent='—';$('ratio').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const hrs=num('hours'),iv=num('interval'),sz=num('size'),fps=num('fps');if(!(hrs>0&&iv>0&&sz>=0&&fps>0))throw 0;const sec=hrs*3600,frames=Math.floor(sec/iv)+1,mb=frames*sz,clip=frames/fps,ratio=sec/clip;$('frames').textContent=fmt(frames,0);$('storage').textContent=mb>=1024?fmt(mb/1024,2)+' GB':fmt(mb,0)+' MB';$('clip').textContent=fmt(clip,2)+' s';$('ratio').textContent=fmt(ratio,1)+'×';$('note').textContent='Frame count includes the starting frame. Real cameras may create extra preview, sidecar or metadata files, so leave storage headroom.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Timelapse Storage Calculator works</h2><p>Timelapse planning starts with capture duration and interval. The tool estimates captured frames from total capture seconds ÷ interval, including the initial frame, then multiplies frame count by the average file size. Final clip duration is frame count ÷ playback fps, and the compression ratio compares real elapsed time with finished video time.</p><h2>How to use this timelapse storage calculator</h2><p>Enter the total time you expect the camera to run, the interval between exposures, an average RAW or JPEG file size and your intended output frame rate. For variable-size compressed files, use a conservative average from a test sequence. The result lets you check both memory-card capacity and whether the finished clip will be long enough.</p><h2>How to interpret the result</h2><p>Shorter intervals produce more frames, use more storage and create slower apparent motion when played at the same fps. A longer capture can create a surprisingly short final clip: thousands of seconds in real time may compress into only seconds on screen. The real-time compression metric makes that relationship explicit.</p><h2>Assumptions and limitations</h2><p>The estimate does not include duplicate backup cards, video proxies, sidecar files, camera-generated JPEG+RAW pairs or filesystem overhead. Some intervalometers count the first exposure differently. Long shutter speeds also need to fit inside the chosen interval, and battery/thermal limits may end a sequence before the planned duration.</p><h2>Practical example and workflow</h2><p>A four-hour sequence at a five-second interval produces about 2,881 frames when the starting frame is included. At 24 fps, that is roughly two minutes of finished footage. If each RAW averages 25 MB, storage is about 70 GB, so a photographer can choose card capacity before leaving the camera unattended.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How many photos are needed for a 10-second timelapse?','At 24 fps you need 240 frames; at 30 fps you need 300 frames. Capture interval then determines how much real time those frames represent.'],['Why does the calculator add one frame?','It assumes a frame is captured at time zero and then at each interval. Some camera intervalometers use different counting behavior.'],['Should I use RAW or JPEG file size?','Use the format you will actually record and a conservative average from a test shot. RAW files are usually much larger and can vary by camera/compression mode.'],['Does this include video rendering storage?','No. It estimates source-image storage only; rendered masters, proxies and backups require additional space.']];
require __DIR__.'/../includes/tool-template.php';
