<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('photography-video','video-bitrate-file-size-calculator');
ob_start();
?>
<h2>Estimate video file size from bitrate</h2><p class="lead">Convert video and audio bitrate plus duration into an approximate file size.</p><div class="notice">Use average bitrate for VBR footage. File size follows bitrate and time; resolution and codec matter only through the bitrate they produce.</div><div class="form-grid"><div class="field"><label for="video">Video bitrate (Mbps)</label><input id="video" type="number" value="20" min="0" step="any"></div><div class="field"><label for="audio">Audio bitrate (kbps)</label><input id="audio" type="number" value="192" min="0" step="any"></div><div class="field"><label for="minutes">Duration (minutes)</label><input id="minutes" type="number" value="10" min="0.001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Total bitrate</span><strong id="total">—</strong></div><div class="metric"><span>Approximate file size</span><strong id="size">—</strong></div><div class="metric"><span>Storage per minute</span><strong id="permin">—</strong></div><div class="metric"><span>Binary size (GiB)</span><strong id="gib">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('total').textContent='—';$('size').textContent='—';$('permin').textContent='—';$('gib').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const v=num('video'),a=num('audio'),m=num('minutes');if(!(v>=0&&a>=0&&m>0&&(v>0||a>0)))throw 0;const mbps=v+a/1000,bytes=mbps*1e6*(m*60)/8,gb=bytes/1e9,gib=bytes/1073741824;$('total').textContent=fmt(mbps,3)+' Mbps';$('size').textContent=fmt(gb,3)+' GB';$('permin').textContent=fmt(gb/m*1000,1)+' MB/min';$('gib').textContent=fmt(gib,3)+' GiB';$('note').textContent='This is a bitrate-based estimate. Containers, metadata, VBR peaks and codec muxing overhead can make real files slightly different.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Video Bitrate File Size Calculator works</h2><p>The core relationship is file size = bitrate × duration ÷ 8 because bitrate is normally expressed in bits per second while storage is measured in bytes. The calculator adds video bitrate in Mbps and audio bitrate converted from kbps, then reports decimal gigabytes, binary gibibytes and storage used per minute.</p><h2>How to use this video bitrate file size calculator</h2><p>Enter an average video bitrate, audio bitrate and clip duration. For constant-bitrate exports, the entered value is straightforward. For variable-bitrate encodes, use the measured or target average bitrate rather than the maximum setting. This makes the result useful for upload planning, recording-time estimates and archive capacity.</p><h2>How to interpret the result</h2><p>At the same bitrate and duration, two codecs produce roughly the same file size even if their visual quality differs. Resolution, frame rate, bit depth and codec efficiency influence how much bitrate is needed to achieve a quality target, but they do not independently enter the basic size equation once bitrate is known.</p><h2>Assumptions and limitations</h2><p>Container headers, metadata, multiple audio tracks, subtitles and muxing overhead add some data. VBR footage can also miss the target average. Camera “Mbps” labels may include or exclude audio depending on the manufacturer. For guaranteed recording duration, leave safety margin rather than filling a card to the calculated limit.</p><h2>Practical example and workflow</h2><p>A 10-minute clip at 20 Mbps video plus 192 kbps audio is about 1.5 GB before small container overhead. An editor comparing a 20 Mbps and 50 Mbps export can immediately see the storage/upload difference without guessing from resolution alone.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How do I convert Mbps to file size?','Multiply Mbps by duration in seconds, divide by 8 to convert bits to bytes, then convert bytes to the storage unit you need.'],['Why is my real file slightly larger or smaller?','Variable bitrate, container overhead, metadata and extra audio/subtitle streams can move the final size away from the simple estimate.'],['Does 4K always create a larger file than 1080p?','Not automatically. File size is driven by bitrate and duration; 4K is commonly encoded at a higher bitrate, which is why it often produces larger files.'],['What bitrate should I enter for VBR video?','Use the average or measured bitrate over the clip, not just the maximum VBR setting.']];
require __DIR__.'/../includes/tool-template.php';
