<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('fitness-sports','body-fat-estimate-calculator');
ob_start();
?>
<h2>Estimate body-fat percentage</h2><p class="lead">Use circumference measurements to generate an approximate body-fat percentage. Measurement technique strongly affects the result.</p>
<div class="form-grid"><div class="field"><label for="sex">Formula</label><select id="sex"><option value="m">Male circumference formula</option><option value="f">Female circumference formula</option></select></div><div class="field"><label for="unit">Measurement unit</label><select id="unit"><option value="in">Inches</option><option value="cm">Centimetres</option></select></div><div class="field"><label for="height">Height</label><input id="height" type="number" min="0" step="any" value="70"></div><div class="field"><label for="neck">Neck circumference</label><input id="neck" type="number" min="0" step="any" value="15"></div><div class="field"><label for="waist">Waist / abdominal circumference</label><input id="waist" type="number" min="0" step="any" value="34"></div><div class="field" id="hipWrap"><label for="hip">Hip circumference (female formula)</label><input id="hip" type="number" min="0" step="any" value="40"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Estimate body fat</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated body fat</span><strong id="bf">—</strong></div><div class="metric"><span>Circumference value</span><strong id="cv">—</strong></div><div class="metric"><span>Method</span><strong id="method">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value),inch=v=>$('unit').value==='cm'?v/2.54:v;function go(){const sex=$('sex').value,h=inch(n('height')),neck=inch(n('neck')),waist=inch(n('waist')),hip=inch(n('hip'));$('hipWrap').style.display=sex==='f'?'flex':'none';if(![h,neck,waist].every(Number.isFinite)||h<=0||neck<=0||waist<=0||(sex==='f'&&(!Number.isFinite(hip)||hip<=0))){$('note').textContent='Enter positive measurements.';$('note').className='helper danger';return;}const cv=sex==='m'?waist-neck:waist+hip-neck;if(cv<=0){$('note').textContent='The circumference combination must be greater than zero.';$('note').className='helper danger';return;}const bf=sex==='m'?86.010*Math.log10(cv)-70.041*Math.log10(h)+36.76:163.205*Math.log10(cv)-97.684*Math.log10(h)-78.387;$('bf').textContent=bf.toFixed(1)+'%';$('cv').textContent=cv.toFixed(2)+' in';$('method').textContent=sex==='m'?'Waist − neck':'Waist + hip − neck';$('note').textContent='This is an estimate from circumference equations, not a direct measurement of body composition. Tape placement, rounding and body shape can materially change the result.';$('note').className='helper';}
['sex','unit','height','neck','waist','hip'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('sex').value='m';$('unit').value='in';$('height').value=70;$('neck').value=15;$('waist').value=34;$('hip').value=40;go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How this body-fat estimate is calculated</h2><p>The tool uses circumference-based logarithmic equations of the type used in U.S. military body-composition procedures. For the male equation, the key circumference value is waist minus neck. For the female equation, it is waist plus hip minus neck. Height and circumferences are evaluated in inches.</p>
<h2>Measurement consistency matters</h2><p>Small differences in tape location or tension can change the estimate. Official military procedures specify measurement locations and rounding rules; this general-purpose calculator does not reproduce an official fitness assessment. See a current example of circumference methodology in U.S. Coast Guard body-composition guidance: <a href="https://media.defense.gov/2022/Mar/31/2002967299/-1/-1/0/CI_1020_8I.PDF" target="_blank" rel="noopener">body-composition instruction</a>.</p>
<h2>Why this is only an estimate</h2><p>Circumference equations infer body-fat percentage from external measurements. They can be useful for tracking a consistent personal method over time, but they are not equivalent to DXA, air-displacement plethysmography or other laboratory methods.</p>
<h2>Do not use the result as a diagnosis</h2><p>Body-fat percentage alone does not determine health or athletic performance. If you need a clinically meaningful body-composition assessment, use a qualified professional and an appropriate measurement method.</p>
<h2>Improve repeatability before comparing estimates</h2><p>Circumference-based body fat estimates are sensitive to tape placement and measurement technique. Measure at the same anatomical locations, with the tape level and snug but not compressing tissue, and repeat measurements under similar conditions. Use the calculator to monitor a consistent method over time rather than treating small day-to-day changes as real changes in body composition. For clinical or sport-critical decisions, use a validated assessment method and trained practitioner.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Which measurements are used for the male formula?','Height, neck circumference and waist/abdominal circumference are used; the key circumference value is waist minus neck.'],['Which measurements are used for the female formula?','Height, neck, waist and hip circumferences are used; the key circumference value is waist plus hip minus neck.'],['Can I enter centimetres?','Yes. The calculator converts centimetres to inches before applying the circumference equations.'],['Is this the same as a DXA body-fat measurement?','No. It is a circumference-based estimate and can differ from laboratory body-composition measurements.']];
require __DIR__.'/../includes/tool-template.php';
