<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('fitness-sports','heart-rate-zone-calculator');
ob_start();
?>
<h2>Estimate training heart-rate zones</h2><p class="lead">Compare age-predicted percent-of-maximum zones with the heart-rate-reserve (Karvonen-style) method.</p>
<div class="form-grid"><div class="field"><label for="age">Age</label><input id="age" type="number" min="10" max="100" step="1" value="35"></div><div class="field"><label for="rest">Resting heart rate (bpm)</label><input id="rest" type="number" min="20" max="150" step="1" value="60"></div><div class="field"><label for="method">Method</label><select id="method"><option value="max">Percent of age-predicted max (220 − age)</option><option value="hrr">Heart-rate reserve</option></select></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate zones</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Age-predicted max HR</span><strong id="max">—</strong></div><div class="metric"><span>Moderate guide (50–70%)</span><strong id="moderate">—</strong></div><div class="metric"><span>Vigorous guide (70–85%)</span><strong id="vigorous">—</strong></div></div><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>Zone</th><th>Intensity</th><th>Target bpm</th></tr></thead><tbody id="zones"></tbody></table></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value);function target(p,max,rest,method){return method==='hrr'?rest+(max-rest)*p:max*p}function go(){const age=n('age'),rest=n('rest'),method=$('method').value;if(!Number.isFinite(age)||age<10||age>100||!Number.isFinite(rest)||rest<20||rest>=220-age){$('note').textContent='Enter a plausible age and a resting heart rate below the age-predicted maximum.';$('note').className='helper danger';return;}const max=220-age;$('max').textContent=Math.round(max)+' bpm';const range=(a,b)=>Math.round(target(a,max,rest,method))+'–'+Math.round(target(b,max,rest,method))+' bpm';$('moderate').textContent=range(.5,.7);$('vigorous').textContent=range(.7,.85);const bands=[[.5,.6,'Zone 1'],[.6,.7,'Zone 2'],[.7,.8,'Zone 3'],[.8,.9,'Zone 4'],[.9,1,'Zone 5']];$('zones').innerHTML=bands.map(x=>'<tr><td>'+x[2]+'</td><td>'+Math.round(x[0]*100)+'–'+Math.round(x[1]*100)+'%</td><td>'+range(x[0],x[1])+'</td></tr>').join('');$('note').textContent='Age-predicted maximum heart rate is an average estimate. Medications, cardiovascular conditions and individual physiology can change appropriate exercise heart rates.';$('note').className='helper';}
['age','rest','method'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('age').value=35;$('rest').value=60;$('method').value='max';go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the heart-rate zone calculator works</h2><p>The percent-of-max method uses an age-predicted maximum of approximately 220 minus age. The heart-rate-reserve option first subtracts resting heart rate from that maximum and then adds resting heart rate back after applying the intensity percentage.</p>
<h2>Moderate and vigorous exercise reference ranges</h2><p>The American Heart Association describes moderate-intensity activity as roughly 50–70% of maximum heart rate and vigorous activity as roughly 70–85%, while emphasizing that age-predicted values are averages. <a href="https://www.heart.org/en/healthy-living/exercise-and-physical-activity/fitness-basics/target-heart-rates" target="_blank" rel="noopener">AHA target heart-rate guidance</a>.</p>
<h2>Why two methods give different zones</h2><p>The heart-rate-reserve method accounts for your entered resting pulse, so it usually produces different targets from a simple percentage of maximum. Neither method measures your true maximum heart rate directly.</p>
<h2>Safety limitation</h2><p>This calculator is for general exercise planning, not medical clearance. Heart conditions and some medications can alter heart-rate response. People with relevant conditions or symptoms should follow individualized clinical guidance rather than a generic zone estimate.</p>
<h2>Choose zones that match your training method</h2><p>Age-predicted maximum heart rate is a rough starting point, not an individual test. Some training plans use percentage of maximum heart rate, while others use heart-rate reserve, threshold heart rate or sport-specific testing. Medication, heat, dehydration, altitude and illness can shift heart-rate response. If precise zones matter for performance or health, use a method appropriate to the athlete and obtain medical guidance when exercise safety is uncertain.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What maximum heart-rate formula does this tool use?','It uses the common age-predicted estimate of 220 minus age. The American Heart Association notes that such figures are averages and general guides.'],['What is heart-rate reserve?','Heart-rate reserve is estimated maximum heart rate minus resting heart rate. Target values are then calculated as resting HR + a percentage of that reserve.'],['What ranges are commonly used for moderate and vigorous activity?','The AHA commonly describes about 50–70% of maximum for moderate intensity and about 70–85% for vigorous intensity.'],['Can medication affect target heart rate?','Yes. Some medications and health conditions change heart-rate response, so generic formulas may not be appropriate for everyone.']];
require __DIR__.'/../includes/tool-template.php';
