<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('fitness-sports','sports-hydration-calculator');
ob_start();
?>
<h2>Estimate exercise sweat rate</h2><p class="lead">Use a before-and-after weigh-in plus measured fluid intake to estimate sweat loss during a training session.</p>
<div class="form-grid"><div class="field"><label for="pre">Pre-exercise body mass (kg)</label><input id="pre" type="number" min="0" step="any" value="70"></div><div class="field"><label for="post">Post-exercise body mass (kg)</label><input id="post" type="number" min="0" step="any" value="69.4"></div><div class="field"><label for="drink">Fluid consumed (L)</label><input id="drink" type="number" min="0" step="any" value="0.5"></div><div class="field"><label for="urine">Urine during session (L)</label><input id="urine" type="number" min="0" step="any" value="0"></div><div class="field"><label for="mins">Exercise duration (minutes)</label><input id="mins" type="number" min="1" step="any" value="60"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Estimate sweat rate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated sweat loss</span><strong id="loss">—</strong></div><div class="metric"><span>Sweat rate</span><strong id="rate">—</strong></div><div class="metric"><span>Body-mass change</span><strong id="change">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value);function go(){const pre=n('pre'),post=n('post'),drink=n('drink'),ur=n('urine'),mins=n('mins');if(![pre,post,drink,ur,mins].every(Number.isFinite)||pre<=0||post<=0||drink<0||ur<0||mins<=0){$('note').textContent='Enter positive body masses and duration, plus non-negative fluid and urine volumes.';$('note').className='helper danger';return;}const massLoss=pre-post,sweat=massLoss+drink-ur,rate=sweat/(mins/60),pct=(post-pre)/pre*100;$('loss').textContent=sweat.toFixed(2)+' L';$('rate').textContent=rate.toFixed(2)+' L/h';$('change').textContent=pct.toFixed(2)+'%';let msg='Use repeated measurements in similar conditions to understand your personal range. Sweat rate changes with temperature, clothing, intensity, acclimatization and body size.';if(sweat<0)msg='The calculated sweat loss is negative, which usually indicates inconsistent measurements, unrecorded fluid, scale error or a timing issue. '+msg;$('note').textContent=msg;$('note').className='helper'+(sweat<0?' danger':'');}
['pre','post','drink','urine','mins'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('pre').value=70;$('post').value=69.4;$('drink').value=.5;$('urine').value=0;$('mins').value=60;go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>Sports hydration and sweat-rate formula</h2><p>A practical field estimate is: sweat loss ≈ pre-exercise body mass − post-exercise body mass + fluid consumed − urine produced. When body mass is measured in kilograms, a 1 kg change is treated approximately as 1 litre of water. Divide sweat loss by exercise hours to estimate litres per hour.</p>
<h2>Why body mass is measured before and after exercise</h2><p>The change helps account for fluid that left the body during the session. Adding recorded fluid intake prevents drinking during exercise from hiding part of the loss.</p>
<h2>Do not turn one test into a universal drinking prescription</h2><p>The American College of Sports Medicine maintains evidence-based guidance on exercise and fluid replacement, but practical hydration should be individualized. Sweat rate can change substantially across weather, pace, clothing and acclimatization. <a href="https://acsm.org/education-resources/pronouncements-scientific-communications/position-stands/" target="_blank" rel="noopener">ACSM position stands</a>.</p>
<h2>Important safety note</h2><p>This calculator estimates sweat rate; it does not diagnose dehydration or prescribe a medical fluid or electrolyte plan. Excessive fluid intake can also be unsafe. People with medical conditions or unusual symptoms should follow professional guidance.</p>
<h2>Turn sweat-rate data into a practical observation</h2><p>Repeat the sweat-rate measurement in conditions similar to the sport because heat, humidity, clothing, acclimatization and intensity can change losses substantially. Body-mass change should be measured on the same scale and with similar clothing, while drinks consumed and urine produced during the session should be recorded. The result helps describe observed fluid loss; it is not a universal prescription to replace every millilitre during exercise.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How is sweat rate calculated?','Estimated sweat loss is pre-exercise mass minus post-exercise mass, plus fluid consumed, minus urine output. Divide by exercise hours for litres per hour.'],['Why is fluid consumed added back?','Drinking during exercise reduces the observed body-mass drop, so adding the measured fluid helps estimate total sweat loss.'],['Is one sweat-rate test enough?','No. Repeating the test in different temperatures, intensities and conditions gives a more useful personal range.'],['Does the result tell me exactly how much to drink?','No. It estimates sweat rate only. An appropriate hydration plan depends on conditions, session length, electrolyte losses and individual health factors.']];
require __DIR__.'/../includes/tool-template.php';
