<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('fitness-sports','tdee-calorie-needs-calculator');
ob_start();
?>
<h2>Estimate TDEE and resting energy expenditure</h2><p class="lead">Use the Mifflin-St Jeor equation for resting energy expenditure (REE), then apply an activity factor to estimate total daily energy expenditure.</p>
<div class="form-grid"><div class="field"><label for="sex">Equation sex constant</label><select id="sex"><option value="m">Male (+5)</option><option value="f">Female (−161)</option></select></div><div class="field"><label for="age">Age (years)</label><input id="age" type="number" min="18" max="100" step="1" value="35"></div><div class="field"><label for="weight">Weight (kg)</label><input id="weight" type="number" min="0" step="any" value="70"></div><div class="field"><label for="height">Height (cm)</label><input id="height" type="number" min="0" step="any" value="175"></div><div class="field"><label for="factor">Activity factor</label><select id="factor"><option value="1.2">1.20 — low activity</option><option value="1.375">1.375 — light</option><option value="1.55" selected>1.55 — moderate</option><option value="1.725">1.725 — high</option><option value="1.9">1.90 — very high</option><option value="custom">Custom</option></select></div><div class="field"><label for="custom">Custom factor</label><input id="custom" type="number" min="0.5" step="0.001" value="1.55"></div></div>
<div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Estimate TDEE</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Estimated REE</span><strong id="ree">—</strong></div><div class="metric"><span>Estimated TDEE</span><strong id="tdee">—</strong></div><div class="metric"><span>Activity factor used</span><strong id="af">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id),n=id=>parseFloat($(id).value);function go(){const sex=$('sex').value,a=n('age'),w=n('weight'),h=n('height'),f=$('factor').value==='custom'?n('custom'):parseFloat($('factor').value);$('custom').disabled=$('factor').value!=='custom';if(![a,w,h,f].every(Number.isFinite)||a<18||w<=0||h<=0||f<=0){$('note').textContent='Enter valid adult age, height, weight and activity factor.';$('note').className='helper danger';return;}const ree=10*w+6.25*h-5*a+(sex==='m'?5:-161),t=ree*f;$('ree').textContent=Math.round(ree)+' kcal/day';$('tdee').textContent=Math.round(t)+' kcal/day';$('af').textContent=f.toFixed(3);$('note').textContent='TDEE is a model estimate. Activity factors are broad categories, and individual energy expenditure can differ substantially.';$('note').className='helper';}
['sex','age','weight','height','factor','custom'].forEach(id=>$(id).addEventListener('input',go));$('calc').onclick=go;$('reset').onclick=()=>{$('sex').value='m';$('age').value=35;$('weight').value=70;$('height').value=175;$('factor').value='1.55';$('custom').value=1.55;go();};go();})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>TDEE calculator formula</h2><p>The first step is Mifflin-St Jeor resting energy expenditure: 10 × weight (kg) + 6.25 × height (cm) − 5 × age, plus 5 for the male equation or minus 161 for the female equation. The original study derived the equation from measured resting energy expenditure in healthy adults. <a href="https://pubmed.ncbi.nlm.nih.gov/2305711/" target="_blank" rel="noopener">Mifflin et al. study</a>.</p>
<h2>From REE to TDEE</h2><p>Total daily energy expenditure is estimated by multiplying REE by an activity factor. The factor is the least precise part of a simple TDEE calculator because real daily movement, occupation and training load vary continuously.</p>
<h2>Why TDEE is not a fixed personal number</h2><p>Energy expenditure changes with activity, body composition, temperature, illness, training and other factors. Treat the result as a starting estimate rather than a measurement.</p>
<h2>Health and nutrition limitation</h2><p>This tool does not prescribe a calorie deficit, weight-loss target or medical nutrition plan. People with medical, pregnancy, eating-disorder or performance-nutrition needs should use individualized professional guidance.</p>
<h2>Treat TDEE as a starting estimate, then calibrate</h2><p>Activity multipliers compress many behaviors into one category, so estimated TDEE can differ meaningfully from real energy expenditure. If body weight is stable over several weeks under consistent intake tracking, that observed intake can help calibrate the estimate. Changes in training volume, occupation, sleep, illness and body mass can change expenditure. For medical nutrition, eating disorders, pregnancy or other health conditions, use individualized professional guidance rather than a generic calculator.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What equation does the TDEE calculator use?','It uses the Mifflin-St Jeor resting energy expenditure equation and multiplies the result by the activity factor you select.'],['Is REE the same as TDEE?','No. REE estimates energy used at rest, while TDEE attempts to include daily activity by multiplying REE by an activity factor.'],['How accurate are activity factors?','They are broad planning assumptions. Two people in the same activity category can have meaningfully different actual energy expenditure.'],['Does this calculator tell me how many calories to eat for weight loss?','No. It estimates energy expenditure only and does not prescribe a calorie target or medical nutrition plan.']];
require __DIR__.'/../includes/tool-template.php';
