<?php
require_once TBK_ROOT.'/includes/helpers.php';
$cats=tbk_categories(); $cat=$cats[$tool['category']]; $canonical=tbk_url($tool['category'].'/'.$tool['slug'].'/');
$head_callback=function()use($tool,$canonical,$cat){tbk_page_head($tool['name'],$tool['description'],$canonical,'website');tbk_jsonld(['@context'=>'https://schema.org','@type'=>'WebApplication','name'=>$tool['name'],'description'=>$tool['description'],'url'=>$canonical,'applicationCategory'=>'UtilitiesApplication','operatingSystem'=>'Any','offers'=>['@type'=>'Offer','price'=>'0','priceCurrency'=>'USD']]);tbk_jsonld(['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'Home','item'=>tbk_url()],['@type'=>'ListItem','position'=>2,'name'=>$cat['name'],'item'=>tbk_url($tool['category'].'/')],['@type'=>'ListItem','position'=>3,'name'=>$tool['name'],'item'=>$canonical]]]);};
require TBK_ROOT.'/partials/header.php';
?>
<section class="page-hero"><div class="wrap"><nav class="breadcrumbs"><a href="/">Home</a><span>›</span><a href="/<?=e($tool['category'])?>/"><?=e($cat['name'])?></a><span>›</span><span><?=e($tool['name'])?></span></nav><h1><?=e($tool['name'])?></h1><p><?=e($tool['description'])?></p><div class="tool-badges"><span class="badge">Free</span><span class="badge">No signup</span><span class="badge">Runs in your browser</span></div></div></section>
<section class="section"><div class="wrap"><div class="tool-layout"><div class="workspace"><h2>Enter your values</h2><form id="tool-form"><?php require DIR_OF_TOOL.'/form.php'; ?><div class="tool-actions"><button class="btn primary" type="submit">Calculate / Run</button><button class="btn secondary" type="button" id="tool-reset">Reset</button></div></form></div><aside class="result-panel"><h2>Result</h2><div id="tool-result"><div class="result-placeholder">Your result will appear here.</div></div></aside></div>
<div class="content-stack"><section class="content-card"><h2>How to use <?=e($tool['name'])?></h2><ol><?php foreach($tool['guide'] as $g):?><li><?=e($g)?></li><?php endforeach;?></ol></section><section class="content-card"><h2>About this tool</h2><p><?=e($tool['about'])?></p><?php if(!empty($tool['formula'])):?><h3>Method</h3><p><?=e($tool['formula'])?></p><?php endif;?><?php if(!empty($tool['warning'])):?><div class="notice"><?=e($tool['warning'])?></div><?php endif;?></section><?php if(!empty($tool['faqs'])):?><section class="content-card faq"><h2>Frequently asked questions</h2><?php foreach($tool['faqs'] as $q=>$a):?><details><summary><?=e($q)?></summary><p><?=e($a)?></p></details><?php endforeach;?></section><?php endif;?><section class="content-card"><h2>Related tools</h2><div class="related-grid"><?php $rel=array_filter(tbk_tools_by_category($tool['category']),fn($x)=>$x['slug']!==$tool['slug']);foreach(array_slice($rel,0,3) as $r):?><a class="related-link" href="/<?=e($r['category'])?>/<?=e($r['slug'])?>/"><b><?=e($r['name'])?></b><span><?=e($r['description'])?></span></a><?php endforeach;?></div></section></div></div></section>
<script src="/assets/tool-core.js"></script><script src="tool.js"></script>
<?php require TBK_ROOT.'/partials/footer.php'; ?>
