<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','calibration-curve-calculator');
ob_start();
?>
<h2>Fit a linear calibration curve</h2><p class="lead">Paste concentration,response pairs to calculate least-squares slope, intercept, R² and an unknown concentration from measured response.</p><div class="notice">NIST notes that calibration model choice matters and linear models can be inappropriate outside a validated range. This tool does not replace method validation, uncertainty analysis or weighted regression.</div><div class="form-grid"><div class="field"><label for="pairs">Calibration points (x,y; one pair per line)</label><textarea id="pairs" rows="7">0,0.02
1,1.04
2,2.01
4,4.10
6,6.05</textarea></div><div class="field"><label for="unknown">Unknown sample response (y)</label><input id="unknown" type="number" value="3.05" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Calibration equation</span><strong id="equation">—</strong></div><div class="metric"><span>R²</span><strong id="r2">—</strong></div><div class="metric"><span>Estimated unknown x</span><strong id="pred">—</strong></div><div class="metric"><span>Valid calibration points</span><strong id="npts">—</strong></div></div><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>x concentration</th><th>Observed y</th><th>Fitted y</th><th>Residual</th></tr></thead><tbody id="calRows"></tbody></table></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('equation').textContent='—';$('r2').textContent='—';$('pred').textContent='—';$('npts').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const lines=$('pairs').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const pts=[];for(const line of lines){const parts=line.split(/[;,\t ]+/).filter(Boolean).map(Number);if(parts.length>=2&&parts.slice(0,2).every(Number.isFinite))pts.push([parts[0],parts[1]])}if(pts.length<2)throw 0;const n=pts.length,sx=pts.reduce((a,p)=>a+p[0],0),sy=pts.reduce((a,p)=>a+p[1],0),sxx=pts.reduce((a,p)=>a+p[0]*p[0],0),sxy=pts.reduce((a,p)=>a+p[0]*p[1],0);const den=n*sxx-sx*sx;if(Math.abs(den)<1e-15)throw 0;const slope=(n*sxy-sx*sy)/den,inter=(sy-slope*sx)/n;const ybar=sy/n;let ssr=0,sst=0;const rows=pts.map(p=>{const fit=slope*p[0]+inter,res=p[1]-fit;ssr+=res*res;sst+=(p[1]-ybar)**2;return [p[0],p[1],fit,res]});const R2=sst>0?1-ssr/sst:1,uy=num('unknown'),ux=slope!==0?(uy-inter)/slope:NaN;$('equation').textContent='y = '+fmt(slope,6)+'x '+(inter>=0?'+ ':'− ')+fmt(Math.abs(inter),6);$('r2').textContent=fmt(R2,6);$('pred').textContent=Number.isFinite(ux)?fmt(ux,6):'Unavailable';$('npts').textContent=n;$('calRows').innerHTML=rows.map(p=>'<tr><td>'+fmt(p[0],6)+'</td><td>'+fmt(p[1],6)+'</td><td>'+fmt(p[2],6)+'</td><td>'+fmt(p[3],6)+'</td></tr>').join('');$('note').textContent='This fits an unconstrained ordinary least-squares straight line. Inspect residuals and validate the calibration range before quantifying unknowns.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Calibration Curve Calculator works</h2><p>NIST describes calibration as relating known analyte quantities to measured instrumental response through a mathematical model. This tool performs an ordinary least-squares linear fit y = slope×x + intercept from entered concentration-response pairs, calculates R², displays residuals and back-calculates an unknown x from its measured y.</p><h2>How to use this calibration curve calculator</h2><p>Paste at least two numeric x,y pairs, ideally several standards covering the validated analytical range. Review the fitted-vs-observed table rather than relying only on R². Enter the unknown response only when it falls within a range and method context where inverse prediction is appropriate. Replicates can be entered as separate points if that matches your method.</p><h2>How to interpret the result</h2><p>Slope represents response change per concentration unit, while the intercept estimates response at x=0 under an unconstrained fit. R² describes the fraction of response variation accounted for by the line, but a high R² alone does not prove unbiased calibration. Residual pattern, back-calculated standards, blanks and uncertainty are also important.</p><h2>Assumptions and limitations</h2><p>The tool fits an unweighted straight line and does not test heteroscedasticity, outliers, limit of detection/quantitation, replicate weighting, uncertainty or matrix effects. NIST guidance emphasizes choosing an appropriate calibration model; do not force a linear fit simply because the software can calculate one. Extrapolating unknowns beyond standards is especially risky.</p><h2>Practical example and workflow</h2><p>With standards spanning 0–6 concentration units and responses near a straight line, the table shows fitted response and residual for every point. If a mid-range unknown response of 3.05 back-calculates near 3 concentration units, the analyst can still verify QC acceptance and calibration-range rules before reporting the result.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What regression does this calculator use?','Unconstrained ordinary least-squares linear regression with an estimated slope and intercept.'],['Is a high R² enough to prove a good calibration?','No. Inspect residuals, standard recovery, blanks, range, weighting needs and method-specific validation criteria.'],['Can I force the line through zero?','Not in this tool. NIST notes different calibration models exist; choose a zero-intercept model only when justified by the analytical method.'],['Should I extrapolate beyond my highest standard?','Generally avoid unvalidated extrapolation. Quantify unknowns within the method’s validated calibration range or follow the laboratory procedure.']];
require __DIR__.'/../includes/tool-template.php';
