<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','cell-seeding-density-calculator');
ob_start();
?>
<h2>Calculate cell seeding density and inoculum volume</h2><p class="lead">Convert a target cells-per-area density into total cells and stock-suspension volume.</p><div class="notice">Seeding density is protocol- and cell-line-specific. Thermo Fisher provides vessel reference charts, but your validated SOP and cell-line behavior are the authority.</div><div class="form-grid"><div class="field"><label for="area">Growth surface area (cm²)</label><input id="area" type="number" value="75" min="0.0001" step="any"></div><div class="field"><label for="density">Target seeding density (cells/cm²)</label><input id="density" type="number" value="20000" min="0" step="any"></div><div class="field"><label for="stock">Cell suspension concentration (cells/mL)</label><input id="stock" type="number" value="1000000" min="0.0001" step="any"></div><div class="field"><label for="viab">Viability (%)</label><input id="viab" type="number" value="95" min="0.1" max="100" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Viable cells required</span><strong id="cells">—</strong></div><div class="metric"><span>Stock suspension volume</span><strong id="volume">—</strong></div><div class="metric"><span>Total counted cells needed</span><strong id="raw">—</strong></div><div class="metric"><span>Effective viable concentration</span><strong id="perml">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('cells').textContent='—';$('volume').textContent='—';$('raw').textContent='—';$('perml').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const a=num('area'),d=num('density'),s=num('stock'),v=num('viab')/100;if(!(a>0&&d>=0&&s>0&&v>0&&v<=1))throw 0;const viable=a*d,eff=s*v,vol=viable/eff,raw=viable/v;$('cells').textContent=fmt(viable,0)+' cells';$('volume').textContent=fmt(vol,4)+' mL';$('raw').textContent=fmt(raw,0)+' cells';$('perml').textContent=fmt(eff,0)+' viable cells/mL';$('note').textContent='Use the surface area and recommended density for your specific vessel, cell type and protocol. This is a counting/volume calculator, not a cell-culture recommendation.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Cell Seeding Density Calculator works</h2><p>For adherent culture, total viable cells required equal growth surface area × target cells per square centimetre. The calculator then adjusts stock concentration for the entered viability and divides required viable cells by viable cells per millilitre to estimate inoculum volume.</p><h2>How to use this cell seeding density calculator</h2><p>Enter the actual growth area of the flask, dish or plate, the seeding density specified by your protocol, measured cell concentration and viability. Surface areas can differ between vessel manufacturers even when names are similar, so use the vessel documentation rather than assuming a generic area.</p><h2>How to interpret the result</h2><p>The “raw counted cells needed” output shows how viability changes the number of total cells you must withdraw to deliver the desired viable-cell count. The volume result is useful for setting up a dilution or distributing a suspension across replicate vessels, but it does not determine culture-medium volume.</p><h2>Assumptions and limitations</h2><p>Cell attachment, passage number, confluence, aggregation and counting method can change effective seeding. Some protocols specify cells per well rather than cells/cm². The tool does not recommend density, media, supplements or incubation conditions; it only converts validated user-supplied protocol values into cell counts and volume.</p><h2>Practical example and workflow</h2><p>A T75-style vessel with 75 cm² growth area seeded at 20,000 viable cells/cm² requires 1.5 million viable cells. From a suspension measured at 1 million cells/mL with 95% viability, the effective viable concentration is 950,000 cells/mL and the inoculum is about 1.58 mL.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How do I calculate cells needed from seeding density?','Multiply the vessel growth area in cm² by the target viable cells per cm².'],['Why does viability change the inoculum volume?','The measured stock includes non-viable cells; adjusting by viability estimates the concentration of viable cells actually available for seeding.'],['Where do I get vessel surface area?','Use the vessel manufacturer’s specification or your laboratory SOP rather than relying on the vessel name alone.'],['Does this tool recommend a seeding density?','No. Density depends on cell type, experiment and protocol; the calculator only uses the value you provide.']];
require __DIR__.'/../includes/tool-template.php';
