<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','dilution-calculator');
ob_start();
?>
<h2>Calculate solution dilution with C1V1 = C2V2</h2><p class="lead">Find stock volume and diluent volume for a target concentration and final volume.</p><div class="notice">Sigma-Aldrich and Thermo Fisher both use C1V1=C2V2 for dilution of solutions with known concentration. Keep concentration units consistent.</div><div class="form-grid"><div class="field"><label for="c1">Stock concentration</label><input id="c1" type="number" value="100" min="0.000000001" step="any"></div><div class="field"><label for="c2">Desired concentration</label><input id="c2" type="number" value="10" min="0" step="any"></div><div class="field"><label for="v2">Desired final volume (mL)</label><input id="v2" type="number" value="50" min="0.000001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Stock volume required</span><strong id="v1">—</strong></div><div class="metric"><span>Diluent volume</span><strong id="diluent">—</strong></div><div class="metric"><span>Dilution factor</span><strong id="factor">—</strong></div><div class="metric"><span>Stock fraction of final volume</span><strong id="fraction">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('v1').textContent='—';$('diluent').textContent='—';$('factor').textContent='—';$('fraction').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const c1=num('c1'),c2=num('c2'),v2=num('v2');if(!(c1>0&&c2>=0&&v2>0&&c2<=c1))throw 0;const v1=c2*v2/c1,di=v2-v1;$('v1').textContent=fmt(v1,6)+' mL';$('diluent').textContent=fmt(di,6)+' mL';$('factor').textContent=c2>0?fmt(c1/c2,4)+'×':'Infinite';$('fraction').textContent=fmt(v1/v2*100,4)+'%';$('note').textContent='This uses C1V1 = C2V2 and assumes concentration units are the same and volumes are additive enough for the intended laboratory preparation.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Dilution Calculator works</h2><p>The standard dilution relationship is C1V1 = C2V2, where C1 is stock concentration, V1 is stock volume, C2 is desired concentration and V2 is desired final volume. Sigma-Aldrich and Thermo Fisher publish the same relationship in their laboratory dilution guidance. Solving for V1 gives the stock aliquot required.</p><h2>How to use this dilution calculator</h2><p>Enter stock and desired concentrations in the same units—for example both mM or both ng/µL—and enter final volume in millilitres. The tool calculates stock volume and the remaining volume to be made up with diluent. If you prefer µL, multiply the returned millilitres by 1,000.</p><h2>How to interpret the result</h2><p>Dilution factor is stock concentration ÷ final concentration. A 10× dilution means the final solution is one-tenth the stock concentration and one-tenth of the final volume comes from stock under this simple model. The stock-fraction output provides the same relationship as a percentage.</p><h2>Assumptions and limitations</h2><p>This equation assumes the analyte amount is conserved and concentration units are directly compatible. Highly concentrated acids/bases, solutions defined by mass fraction/density, non-additive volumes or chemical reactions may require additional information. Laboratory safety, mixing order and compatibility are outside the calculation.</p><h2>Practical example and workflow</h2><p>To make 50 mL of 10 mM solution from a 100 mM stock, V1 = 10×50/100 = 5 mL of stock and 45 mL diluent. A technician can scale the final volume while keeping the concentration ratio unchanged.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the dilution formula?','C1V1 = C2V2 for a solute conserved during dilution.'],['Do C1 and C2 need the same units?','Yes. Convert them to the same concentration unit before using the equation.'],['Can I use this for concentrated acids by weight percent?','Not directly unless you first convert the stock to a compatible concentration using density/formula-weight information.'],['Why must the desired concentration be no higher than the stock?','Simple dilution can only reduce concentration. Increasing concentration requires adding solute or removing solvent, not just diluting.']];
require __DIR__.'/../includes/tool-template.php';
