<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','molarity-calculator');
ob_start();
?>
<h2>Calculate molarity or required solute mass</h2><p class="lead">Convert between mass, formula weight, solution volume and molar concentration.</p><div class="notice">Sigma-Aldrich expresses mass = molarity × volume × formula weight. This tool applies the same relationship in either direction.</div><div class="form-grid"><div class="field"><label for="mode">Solve for</label><select id="mode"><option value="molarity" selected>Molarity from mass</option><option value="mass">Mass from target molarity</option></select></div><div class="field"><label for="mass">Solute mass (g)</label><input id="mass" type="number" value="5.844" min="0" step="any"></div><div class="field"><label for="mw">Formula / molecular weight (g/mol)</label><input id="mw" type="number" value="58.44" min="0.000001" step="any"></div><div class="field"><label for="vol">Final solution volume (mL)</label><input id="vol" type="number" value="1000" min="0.000001" step="any"></div><div class="field"><label for="target">Target molarity (mol/L)</label><input id="target" type="number" value="0.1" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Molarity</span><strong id="molarity">—</strong></div><div class="metric"><span>Required / entered mass</span><strong id="reqmass">—</strong></div><div class="metric"><span>Moles of solute</span><strong id="moles">—</strong></div><div class="metric"><span>Concentration in mM</span><strong id="mm">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('molarity').textContent='—';$('reqmass').textContent='—';$('moles').textContent='—';$('mm').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const mode=$('mode').value,m=num('mass'),mw=num('mw'),ml=num('vol'),target=num('target');if(!(m>=0&&mw>0&&ml>0&&target>=0))throw 0;const L=ml/1000;let M,grams,moles;if(mode==='molarity'){grams=m;moles=grams/mw;M=moles/L}else{M=target;moles=M*L;grams=moles*mw}$('molarity').textContent=fmt(M,8)+' mol/L';$('reqmass').textContent=fmt(grams,8)+' g';$('moles').textContent=fmt(moles,8)+' mol';$('mm').textContent=fmt(M*1000,5)+' mM';$('note').textContent='Use final solution volume, not just solvent volume. Formula weight must match the exact chemical form, hydration state and salt used.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Molarity Calculator works</h2><p>Molarity is moles of solute per litre of final solution. Moles equal mass ÷ formula weight, so M = mass/(formula weight × litres). Rearranging gives mass = molarity × litres × formula weight, the same relationship shown in Sigma-Aldrich laboratory calculation guidance.</p><h2>How to use this molarity calculator</h2><p>Choose whether to solve for molarity or required mass. Enter the exact formula weight for the reagent form you are using, including hydrate or salt form where relevant, and the final prepared solution volume. When making a solution, dissolve the reagent and bring the solution to final volume rather than simply adding that volume of solvent.</p><h2>How to interpret the result</h2><p>The tool reports molarity in mol/L and mM plus moles of solute, which makes unit checks easier. If the formula weight is wrong, every concentration result will be wrong by the same proportional factor, so verify the bottle label, certificate of analysis or validated reagent specification.</p><h2>Assumptions and limitations</h2><p>Molarity is temperature-dependent through solution volume and does not directly describe activity, normality, osmolality or mass fraction. Purity and assay may require a correction not included here. Concentrated commercial acids/bases often need density and weight-percent calculations rather than a simple solid-mass formula.</p><h2>Practical example and workflow</h2><p>For 5.844 g NaCl (formula weight about 58.44 g/mol) brought to 1 litre final volume, the calculation gives 0.1 mol/L or 100 mM. Reversing the mode shows the same 5.844 g mass required for a 0.1 M, 1 L solution.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the molarity formula?','Molarity = moles of solute divided by litres of final solution.'],['How do I calculate mass for a molar solution?','Mass in grams = target molarity × final volume in litres × formula weight in g/mol.'],['Should volume mean solvent volume or final solution volume?','Use final solution volume after the solute is dissolved and the solution is brought to volume.'],['Do hydrates change molecular weight?','Yes. Use the formula weight of the exact hydrated/salt form actually weighed.']];
require __DIR__.'/../includes/tool-template.php';
