<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','molecular-weight-calculator');
ob_start();
?>
<h2>Calculate molecular weight from a chemical formula</h2><p class="lead">Parse a chemical formula with element symbols, parentheses and hydrate dots to estimate average molar mass.</p><div class="notice">The parser supports element symbols, integer subscripts, parentheses and dot/hydrate coefficients such as CuSO4.5H2O. It does not interpret charges or isotope notation.</div><div class="form-grid"><div class="field"><label for="formula">Chemical formula</label><input id="formula" type="text" value="CuSO4.5H2O" placeholder="e.g. C6H12O6 or CuSO4.5H2O"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Molecular / formula weight</span><strong id="mwout">—</strong></div><div class="metric"><span>Total atoms in formula</span><strong id="atoms">—</strong></div><div class="metric"><span>Distinct elements</span><strong id="elements">—</strong></div><div class="metric"><span>Parsed formula</span><strong id="normalized">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('mwout').textContent='—';$('atoms').textContent='—';$('elements').textContent='—';$('normalized').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const weights={H:1.008,He:4.002602,Li:6.94,Be:9.0121831,B:10.81,C:12.011,N:14.007,O:15.999,F:18.998403163,Ne:20.1797,Na:22.98976928,Mg:24.305,Al:26.9815385,Si:28.085,P:30.973761998,S:32.06,Cl:35.45,Ar:39.948,K:39.0983,Ca:40.078,Sc:44.955908,Ti:47.867,V:50.9415,Cr:51.9961,Mn:54.938044,Fe:55.845,Co:58.933194,Ni:58.6934,Cu:63.546,Zn:65.38,Ga:69.723,Ge:72.630,As:74.921595,Se:78.971,Br:79.904,Kr:83.798,Rb:85.4678,Sr:87.62,Y:88.90584,Zr:91.224,Nb:92.90637,Mo:95.95,Ru:101.07,Rh:102.9055,Pd:106.42,Ag:107.8682,Cd:112.414,In:114.818,Sn:118.710,Sb:121.760,Te:127.60,I:126.90447,Xe:131.293,Cs:132.90545196,Ba:137.327,La:138.90547,Ce:140.116,Pr:140.90766,Nd:144.242,Sm:150.36,Eu:151.964,Gd:157.25,Tb:158.92535,Dy:162.500,Ho:164.93033,Er:167.259,Tm:168.93422,Yb:173.045,Lu:174.9668,Hf:178.49,Ta:180.94788,W:183.84,Re:186.207,Os:190.23,Ir:192.217,Pt:195.084,Au:196.966569,Hg:200.592,Tl:204.38,Pb:207.2,Bi:208.98040,Th:232.0377,U:238.02891};function parseSimple(str){let i=0;function group(){const counts={};while(i<str.length&&str[i]!==')'){if(str[i]==='('){i++;const sub=group();if(str[i]!==')')throw 0;i++;let ds='';while(/\d/.test(str[i]||'')){ds+=str[i++]}const mult=ds?+ds:1;for(const [e,c] of Object.entries(sub))counts[e]=(counts[e]||0)+c*mult}else{const m=str.slice(i).match(/^([A-Z][a-z]?)/);if(!m||!weights[m[1]])throw 0;const e=m[1];i+=e.length;let ds='';while(/\d/.test(str[i]||'')){ds+=str[i++]}counts[e]=(counts[e]||0)+(ds?+ds:1)}}return counts}const c=group();if(i!==str.length)throw 0;return c}const raw=$('formula').value.trim().replace(/·/g,'.');if(!raw)throw 0;const total={};for(const part0 of raw.split('.')){if(!part0)continue;let part=part0,mult=1;const m=part.match(/^(\d+)(.*)$/);if(m){mult=+m[1];part=m[2]}const c=parseSimple(part);for(const [e,n] of Object.entries(c))total[e]=(total[e]||0)+n*mult}let mw=0,atoms=0;for(const [e,n] of Object.entries(total)){mw+=weights[e]*n;atoms+=n}$('mwout').textContent=fmt(mw,6)+' g/mol';$('atoms').textContent=fmt(atoms,0);$('elements').textContent=Object.keys(total).length;$('normalized').textContent=raw;$('note').textContent='Uses standard average atomic weights for common naturally occurring elements. Isotopically labeled compounds need isotope-specific masses.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Molecular Weight Calculator works</h2><p>Molecular/formula weight is the sum of each element’s average atomic weight multiplied by the number of atoms in the chemical formula. The parser reads normal element symbols and integer subscripts, supports grouped parentheses, and treats a dot-separated leading coefficient as a hydrate/solvate multiplier.</p><h2>How to use this molecular weight calculator</h2><p>Type a formula such as C6H12O6, Ca(OH)2 or CuSO4.5H2O. Capitalization matters because element symbols are case-sensitive. The tool reports grams per mole using average atomic weights stored in the page, along with the atom and distinct-element counts as quick checks on parsing.</p><h2>How to interpret the result</h2><p>For compounds that exist as salts or hydrates, the exact form matters. An anhydrous reagent and a pentahydrate have different formula weights, which affects molarity and mass calculations. Use the formula printed on the reagent label or certificate rather than assuming the common form.</p><h2>Assumptions and limitations</h2><p>Average atomic weights are not exact isotope masses. The tool does not parse isotope labels such as 13C or deuterium notation, formal charges, polymers with variable n, or non-stoichiometric materials. For high-precision mass spectrometry, use monoisotopic/exact-mass data and isotope-specific software.</p><h2>Practical example and workflow</h2><p>CuSO4.5H2O is parsed as one copper, one sulfur, nine oxygens and ten hydrogens after adding five waters of hydration. The resulting formula weight is substantially higher than anhydrous CuSO4, demonstrating why hydrate notation cannot be ignored when preparing molar solutions.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does the calculator support parentheses?','Yes, standard grouped formulas such as Ca(OH)2 are supported.'],['Can I calculate hydrates?','Yes. Dot notation with a leading coefficient, such as CuSO4.5H2O or CuSO4·5H2O, is supported.'],['Is this monoisotopic exact mass?','No. It uses average atomic weights, which are appropriate for many solution-preparation calculations but not exact-mass spectrometry.'],['Why does capitalization matter?','Chemical element symbols are case-sensitive: Co is cobalt, while CO would be carbon plus oxygen.']];
require __DIR__.'/../includes/tool-template.php';
