<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','pcr-master-mix-calculator');
ob_start();
?>
<h2>Calculate PCR master mix volumes</h2><p class="lead">Scale common PCR components across reactions with an overage allowance and concentration-based primer calculation.</p><div class="notice">Thermo Fisher examples scale non-template PCR components for multiple reactions and use C1V1=C2V2 for primer/probe concentration. This tool does not prescribe assay chemistry.</div><div class="form-grid"><div class="field"><label for="rxn">Number of reactions</label><input id="rxn" type="number" value="24" min="1" step="1"></div><div class="field"><label for="over">Extra volume / overage (%)</label><input id="over" type="number" value="10" min="0" step="any"></div><div class="field"><label for="total">Final reaction volume (µL)</label><input id="total" type="number" value="20" min="0.001" step="any"></div><div class="field"><label for="mm">2× master mix per reaction (µL)</label><input id="mm" type="number" value="10" min="0" step="any"></div><div class="field"><label for="stock">Primer stock concentration (µM)</label><input id="stock" type="number" value="10" min="0.000001" step="any"></div><div class="field"><label for="finalp">Final concentration of each primer (µM)</label><input id="finalp" type="number" value="0.5" min="0" step="any"></div><div class="field"><label for="template">Template per reaction (µL; excluded from master mix)</label><input id="template" type="number" value="2" min="0" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Effective batch reactions</span><strong id="batch">—</strong></div><div class="metric"><span>Each primer / reaction</span><strong id="primer">—</strong></div><div class="metric"><span>Water / reaction</span><strong id="water">—</strong></div><div class="metric"><span>Master-mix cocktail volume</span><strong id="master">—</strong></div></div><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>Component</th><th>Per reaction</th><th>Batch volume</th></tr></thead><tbody id="mixRows"></tbody></table></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('batch').textContent='—';$('primer').textContent='—';$('water').textContent='—';$('master').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const n=Math.floor(num('rxn')),ov=num('over')/100,t=num('total'),mm=num('mm'),stock=num('stock'),fp=num('finalp'),templ=num('template');if(!(n>=1&&ov>=0&&t>0&&mm>=0&&stock>0&&fp>=0&&templ>=0))throw 0;const p=fp*t/stock,water=t-mm-2*p-templ;if(water<0)throw 0;const mult=n*(1+ov),cocktail=(mm+2*p+water)*mult;$('batch').textContent=fmt(mult,2)+' reaction-equivalents';$('primer').textContent=fmt(p,4)+' µL';$('water').textContent=fmt(water,4)+' µL';$('master').textContent=fmt(cocktail,3)+' µL';$('mixRows').innerHTML=[['2× master mix',mm,mm*mult],['Forward primer',p,p*mult],['Reverse primer',p,p*mult],['Water',water,water*mult],['Template (add separately)',templ,templ*n]].map(x=>'<tr><td>'+x[0]+'</td><td>'+fmt(x[1],4)+' µL</td><td>'+fmt(x[2],3)+' µL</td></tr>').join('');$('note').textContent='Primer volume uses C1V1=C2V2. Template is excluded from the shared cocktail to support sample-specific addition; follow your validated assay protocol.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the PCR Master Mix Calculator works</h2><p>The calculator derives each primer volume from stock concentration × volume = final concentration × final reaction volume. It then subtracts 2× master mix, both primer volumes and template from total reaction volume to calculate water. The shared cocktail is scaled by reaction count plus the entered overage; template is shown separately.</p><h2>How to use this pcr master mix calculator</h2><p>Enter your validated assay volumes and concentrations rather than treating the defaults as a protocol. Thermo Fisher PCR guidance shows the same C1V1=C2V2 approach for primer/probe calculation and often scales non-template components as a master mix to reduce pipetting variability. Choose an overage suitable for your plate size and pipetting losses.</p><h2>How to interpret the result</h2><p>The batch-reaction equivalent makes overage transparent. For 24 reactions with 10% overage, common cocktail components are prepared for 26.4 reaction equivalents. Template volume is not multiplied by overage in the shared cocktail because each sample/standard is typically added to its own reaction.</p><h2>Assumptions and limitations</h2><p>PCR formulations differ by polymerase mix, primer concentration, probes, MgCl2, additives and sample volume. Some kits have minimum/maximum template fractions. This calculator includes only two primers, 2× master mix, water and template; adapt your laboratory worksheet when additional components are required and always follow validated kit/SOP instructions.</p><h2>Practical example and workflow</h2><p>For a 20 µL reaction using 10 µL of 2× mix, 10 µM primers at 0.5 µM final, and 2 µL template, each primer contributes 1 µL and water is 6 µL. A 24-reaction run with 10% overage scales the shared 18 µL cocktail to 26.4 reaction equivalents.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['How is primer volume calculated?','Using C1V1=C2V2: primer stock concentration × primer volume = desired final concentration × final reaction volume.'],['Why is template excluded from the master mix?','Samples/standards usually differ by well, so template is commonly added separately while shared components are combined.'],['How much PCR overage should I use?','Use your laboratory SOP and pipetting workflow. The tool keeps the percentage editable rather than assuming one universal value.'],['Can this calculate probe volume or extra additives?','Not directly. Add those components to a laboratory-specific worksheet and reduce water accordingly.']];
require __DIR__.'/../includes/tool-template.php';
