<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','rcf-rpm-converter');
ob_start();
?>
<h2>Convert RCF and RPM</h2><p class="lead">Convert centrifuge speed between RPM and relative centrifugal force using rotor radius.</p><div class="notice">Protocols should preferably specify RCF because the same RPM produces different force in rotors with different radii.</div><div class="form-grid"><div class="field"><label for="mode">Convert</label><select id="mode"><option value="rpm2rcf" selected>RPM → RCF (×g)</option><option value="rcf2rpm">RCF (×g) → RPM</option></select></div><div class="field"><label for="value">RPM or RCF value</label><input id="value" type="number" value="5000" min="0" step="any"></div><div class="field"><label for="radius">Rotor radius (cm)</label><input id="radius" type="number" value="10" min="0.0001" step="any"></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>RPM</span><strong id="rpm">—</strong></div><div class="metric"><span>RCF (×g)</span><strong id="rcf">—</strong></div><div class="metric"><span>Radius used</span><strong id="radiusout">—</strong></div><div class="metric"><span>Rotor-tip speed</span><strong id="tip">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('rpm').textContent='—';$('rcf').textContent='—';$('radiusout').textContent='—';$('tip').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const mode=$('mode').value,v=num('value'),r=num('radius');if(!(v>=0&&r>0))throw 0;let rpm,rcf;if(mode==='rpm2rcf'){rpm=v;rcf=1.118e-5*r*rpm*rpm}else{rcf=v;rpm=Math.sqrt(rcf/(1.118e-5*r))}const speed=2*Math.PI*(r/100)*rpm/60;$('rpm').textContent=fmt(rpm,2)+' rpm';$('rcf').textContent=fmt(rcf,2)+' ×g';$('radiusout').textContent=fmt(r,3)+' cm';$('tip').textContent=fmt(speed,2)+' m/s';$('note').textContent='Thermo Fisher states RCF = 1.118×10⁻⁵ × radius(cm) × RPM². Use the rotor radius definition required by your centrifuge protocol.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the RCF ↔ RPM Converter works</h2><p>Thermo Fisher gives the conversion RCF = 1.118 × 10⁻⁵ × radius(cm) × RPM². Rearranging allows RPM to be calculated from RCF when rotor radius is known. Because force scales with the square of RPM and linearly with radius, the same RPM does not mean the same g-force in different rotors.</p><h2>How to use this rcf ↔ rpm converter</h2><p>Choose the conversion direction, enter RPM or RCF and enter rotor radius in centimetres. Use the radius definition appropriate to your protocol and centrifuge—often distance from the axis of rotation to the sample position of interest. Check the rotor manual when maximum, average or minimum radius matters.</p><h2>How to interpret the result</h2><p>RCF is generally more transferable between centrifuges because it describes force relative to gravity rather than motor speed alone. The optional rotor-tip speed is shown only as geometric context; it is not a substitute for RCF and should not be used to exceed a rotor’s mechanical rating.</p><h2>Assumptions and limitations</h2><p>Rotor geometry, sample position and manufacturer limits still matter. Never calculate an RPM that exceeds the certified rotor/centrifuge maximum. Some protocols depend on k-factor, sedimentation path or time in addition to RCF. This calculator does not assess rotor compatibility, balancing or centrifuge safety.</p><h2>Practical example and workflow</h2><p>At 5,000 RPM and a 10 cm radius, RCF is about 2,795×g. If the same 5,000 RPM is used in a 5 cm rotor, force is roughly half, showing why copying RPM between different rotor geometries can change a protocol materially.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the RCF to RPM formula?','RCF = 1.118×10⁻⁵ × radius in cm × RPM². Solve the equation for RPM to convert the other direction.'],['Why does rotor radius matter?','Centrifugal acceleration increases with distance from the axis, so the same RPM produces different RCF at different radii.'],['Should protocols report RPM or RCF?','RCF is often more transferable between rotors because it directly accounts for radius.'],['Can I use the calculated RPM above my rotor rating?','No. Always stay within manufacturer-certified rotor and centrifuge speed limits.']];
require __DIR__.'/../includes/tool-template.php';
