<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','reagent-scaling-calculator');
ob_start();
?>
<h2>Scale a laboratory reagent recipe</h2><p class="lead">Scale up or down a multi-component recipe by final batch volume while preserving component ratios.</p><div class="notice">This is ratio scaling. Do not add unlike units together conceptually; the sum display is most meaningful when the listed amounts share the same volume unit.</div><div class="form-grid"><div class="field"><label for="orig">Original recipe final volume</label><input id="orig" type="number" value="100" min="0.000001" step="any"></div><div class="field"><label for="target">Target final volume</label><input id="target" type="number" value="250" min="0.000001" step="any"></div><div class="field"><label for="names">Reagents (one per line)</label><textarea id="names" rows="5">Buffer A
Salt
Additive</textarea></div><div class="field"><label for="amounts">Original amounts, same order</label><textarea id="amounts" rows="5">80
5
2</textarea></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Scale factor</span><strong id="factor">—</strong></div><div class="metric"><span>Sum of listed original amounts</span><strong id="sum">—</strong></div><div class="metric"><span>Sum of scaled listed amounts</span><strong id="scaledsum">—</strong></div><div class="metric"><span>Unlisted make-up volume</span><strong id="unlisted">—</strong></div></div><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>Reagent</th><th>Original amount</th><th>Scaled amount</th></tr></thead><tbody id="reagentRows"></tbody></table></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('factor').textContent='—';$('sum').textContent='—';$('scaledsum').textContent='—';$('unlisted').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const o=num('orig'),t=num('target');if(!(o>0&&t>0))throw 0;const names=$('names').value.split(/\n+/).map(x=>x.trim()).filter(Boolean),amts=$('amounts').value.split(/\n+/).map(x=>Number(x.trim()));if(names.length===0||amts.length<names.length||amts.slice(0,names.length).some(x=>!Number.isFinite(x)||x<0))throw 0;const f=t/o,sum=amts.slice(0,names.length).reduce((a,b)=>a+b,0);$('factor').textContent=fmt(f,6)+'×';$('sum').textContent=fmt(sum,6);$('scaledsum').textContent=fmt(sum*f,6);$('unlisted').textContent=fmt((o-sum)*f,6);$('reagentRows').innerHTML=names.map((n,i)=>'<tr><td>'+n.replace(/[<>&]/g,'')+'</td><td>'+fmt(amts[i],6)+'</td><td>'+fmt(amts[i]*f,6)+'</td></tr>').join('');$('note').textContent=sum>o?'Listed component amounts exceed the original final volume. Check units and whether solid masses are mixed with liquid volumes.':'All listed amounts are multiplied by target volume ÷ original volume. Keep units for each row unchanged.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Reagent Scaling Calculator works</h2><p>Recipe scaling uses a single factor: target final volume ÷ original final volume. Every component amount is multiplied by that factor, preserving the recipe proportions. This is useful for buffers, media and reagent mixtures whose validated formulation is already known.</p><h2>How to use this reagent scaling calculator</h2><p>Enter the original and target final volumes, then list reagent names and original amounts in matching line order. Keep each reagent’s unit exactly as used in the source recipe—for example grams stay grams and millilitres stay millilitres. The calculator scales numbers but does not convert between unlike units.</p><h2>How to interpret the result</h2><p>The unlisted make-up volume is target minus the scaled sum only when all listed amounts are compatible volume units. It can be useful for recipes that list several liquid additions and then say “bring to final volume,” but it should be ignored when rows mix masses, volumes and concentrations.</p><h2>Assumptions and limitations</h2><p>Some laboratory formulations do not scale perfectly because pH adjustment, solubility, heat transfer or reaction chemistry changes with batch size. Stock solutions may also be prepared by concentration rather than direct proportional mass. Follow the validated SOP and use this tool only for the proportional part of the recipe.</p><h2>Practical example and workflow</h2><p>A 100 mL validated recipe scaled to 250 mL has a factor of 2.5. An 80 mL component becomes 200 mL, a 5-unit component becomes 12.5 units and so on. The transparent row table is easier to audit than manually multiplying each line in a notebook.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the reagent scaling formula?','Scaled amount = original component amount × target final volume ÷ original final volume.'],['Can I mix grams and millilitres in the list?','You can scale each number proportionally, but do not interpret the sum/unlisted-volume outputs when rows use different unit types.'],['Does proportional scaling always work?','Not for every formulation. pH adjustment, solubility and process conditions can make large scale changes non-linear.'],['Should I round scaled reagent amounts?','Round only to a precision your balance/pipette and validated method support, and consider whether rounding alters critical concentrations.']];
require __DIR__.'/../includes/tool-template.php';
