<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('science-labs','scientific-unit-converter');
ob_start();
?>
<h2>Convert common scientific units</h2><p class="lead">Convert length, mass, volume, temperature and molar-concentration units with explicit dimensional categories.</p><div class="notice">Units are grouped by physical dimension so incompatible quantities cannot be converted. Temperature is handled separately because Celsius/Fahrenheit/Kelvin are not simple scale-only conversions.</div><div class="form-grid"><div class="field"><label for="cat">Measurement category</label><select id="cat"><option value="length">Length</option><option value="mass">Mass</option><option value="volume" selected>Volume</option><option value="temperature">Temperature</option><option value="molar">Molar concentration</option></select></div><div class="field"><label for="val">Value</label><input id="val" type="number" value="1" step="any"></div><div class="field"><label for="from">From unit</label><select id="from"><option value="mL" selected>mL</option><option value="L">L</option><option value="uL">µL</option><option value="nL">nL</option></select></div><div class="field"><label for="to">To unit</label><select id="to"><option value="mL">mL</option><option value="L">L</option><option value="uL" selected>µL</option><option value="nL">nL</option></select></div></div><div class="tool-actions"><button class="btn btn-primary" id="calc" type="button">Calculate</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div><div class="result-box"><div class="result-grid"><div class="metric"><span>Converted value</span><strong id="out">—</strong></div><div class="metric"><span>Conversion factor</span><strong id="factor">—</strong></div><div class="metric"><span>Category</span><strong id="category">—</strong></div><div class="metric"><span>Reverse factor</span><strong id="reverse">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div><script>
(()=>{
const $=id=>document.getElementById(id); const num=id=>Number($(id).value); const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const defaults={}; document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>defaults[el.id]=el.value);
function clear(){$('out').textContent='—';$('factor').textContent='—';$('category').textContent='—';$('reverse').textContent='—'; const n=$('note'); if(n){n.textContent='';n.className='helper';}}
function calculate(){try{const sets={length:{m:1,cm:1e-2,mm:1e-3,um:1e-6,nm:1e-9},mass:{kg:1,g:1e-3,mg:1e-6,ug:1e-9,ng:1e-12},volume:{L:1,mL:1e-3,uL:1e-6,nL:1e-9},molar:{M:1,mM:1e-3,uM:1e-6,nM:1e-9}};const labels={length:[['m','m'],['cm','cm'],['mm','mm'],['um','µm'],['nm','nm']],mass:[['kg','kg'],['g','g'],['mg','mg'],['ug','µg'],['ng','ng']],volume:[['L','L'],['mL','mL'],['uL','µL'],['nL','nL']],temperature:[['C','°C'],['F','°F'],['K','K']],molar:[['M','M'],['mM','mM'],['uM','µM'],['nM','nM']]};function options(sel,arr,keep){sel.innerHTML=arr.map(x=>'<option value="'+x[0]+'">'+x[1]+'</option>').join('');if(arr.some(x=>x[0]===keep))sel.value=keep}if(!$('cat').dataset.ready){$('cat').dataset.ready='1';$('cat').addEventListener('change',()=>{const arr=labels[$('cat').value];options($('from'),arr,arr[0][0]);options($('to'),arr,arr[Math.min(1,arr.length-1)][0]);calculate()})}const c=$('cat').value,v=num('val'),f=$('from').value,t=$('to').value;if(!Number.isFinite(v))throw 0;let res,fac;if(c==='temperature'){const toC=(x,u)=>u==='C'?x:u==='F'?(x-32)*5/9:x-273.15;const fromC=(x,u)=>u==='C'?x:u==='F'?x*9/5+32:x+273.15;res=fromC(toC(v,f),t);fac=NaN}else{if(!sets[c][f]||!sets[c][t])throw 0;fac=sets[c][f]/sets[c][t];res=v*fac}$('out').textContent=fmt(res,10)+' '+t.replace('u','µ');$('factor').textContent=Number.isFinite(fac)?fmt(fac,10)+'×':'Affine';$('category').textContent=c;$('reverse').textContent=Number.isFinite(fac)&&fac!==0?fmt(1/fac,10)+'×':'Affine';$('note').textContent='Temperature uses an offset conversion; other categories use multiplicative SI-prefix factors. This tool does not convert between dimensions.';}catch(e){clear(); const n=$('note'); if(n){n.textContent='Please check the inputs and try again.';n.className='helper danger';}}}
const c=$('calc'); if(c)c.addEventListener('click',calculate); const r=$('reset'); if(r)r.addEventListener('click',()=>{Object.entries(defaults).forEach(([id,v])=>{if($(id))$(id).value=v});calculate();});
document.querySelectorAll('.tool-panel input,.tool-panel select,.tool-panel textarea').forEach(el=>el.addEventListener('input',calculate));
calculate();
})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>How the Scientific Unit Converter works</h2><p>The converter groups units by physical dimension. Length, mass, volume and molar concentration use scale factors tied to SI prefixes; temperature uses the appropriate offset and scale relationships for Celsius, Fahrenheit and Kelvin. Preventing cross-dimension conversion reduces common mistakes such as treating milligrams and millilitres as interchangeable.</p><h2>How to use this scientific unit converter</h2><p>Choose a category first, then select source and destination units. For laboratory prefixes, µ means 10⁻⁶, milli means 10⁻³ and nano means 10⁻⁹ relative to the base unit shown. Enter the numeric value without adding unit text inside the input field.</p><h2>How to interpret the result</h2><p>The conversion-factor output makes multiplicative conversions auditable. Temperature displays “affine” because a single factor cannot describe conversion when an offset is involved. For example, 0 °C is 32 °F, not zero times a scale factor.</p><h2>Assumptions and limitations</h2><p>Unit conversion does not provide missing physical properties. Converting mass to volume requires density; converting mass concentration to molarity requires molecular weight; converting activity units requires assay-specific definitions. The tool intentionally refuses those category changes instead of inventing assumptions.</p><h2>Practical example and workflow</h2><p>One millilitre converts to 1,000 microlitres because 10⁻³ L ÷ 10⁻⁶ L = 1,000. Similarly, 2 mM converts to 2,000 µM. Those prefix conversions are exact relationships, while measured laboratory values may still have instrument uncertainty and significant-figure limits.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Can I convert mg to mL?','Not without density or another relationship between mass and volume. They are different physical dimensions.'],['How many microlitres are in one millilitre?','1 mL = 1,000 µL.'],['Why is temperature not shown with one conversion factor?','Celsius and Fahrenheit include offsets as well as scaling, so the conversion is affine rather than a simple multiplication.'],['Can this convert mass concentration to molarity?','Not directly; you also need molecular/formula weight and a concentration equation.']];
require __DIR__.'/../includes/tool-template.php';
