<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('graphic-design','design-token-converter');
ob_start();
?>
<h2>Convert design tokens between JSON and CSS variables</h2><p class="lead">Paste nested JSON tokens or CSS custom properties. Conversion happens locally in your browser.</p>
<div class="form-grid"><div class="field"><label for="mode">Conversion</label><select id="mode"><option value="json">JSON tokens → CSS variables</option><option value="css">CSS variables → flat JSON</option></select></div><div class="field"><label for="prefix">CSS variable prefix</label><input id="prefix" value="ds"></div></div>
<div class="field full"><label for="input">Input</label><textarea id="input" rows="11">{"color":{"primary":"#2563eb","surface":"#ffffff"},"space":{"sm":"8px","md":"16px"},"radius":{"md":"8px"}}</textarea></div>
<div class="tool-actions"><button class="btn btn-primary" id="convert" type="button">Convert</button><button class="btn btn-secondary" id="copy" type="button">Copy output</button><button class="btn btn-secondary" id="reset" type="button">Reset</button></div>
<div class="field full"><label for="output">Output</label><textarea id="output" rows="11" readonly></textarea></div><div id="status" class="helper"></div>
<script>
(()=>{const $=id=>document.getElementById(id);function flat(o,p='',out={}){Object.entries(o).forEach(([k,v])=>{const key=p?p+'-'+k:k;if(v&&typeof v==='object'&&!Array.isArray(v))flat(v,key,out);else out[key]=v});return out}function convert(){try{if($('mode').value==='json'){const obj=JSON.parse($('input').value),f=flat(obj),pre=$('prefix').value.trim().replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'');const lines=Object.entries(f).map(([k,v])=>'  --'+(pre?pre+'-':'')+k.replace(/[^a-zA-Z0-9_-]+/g,'-')+': '+String(v)+';');$('output').value=':root {\n'+lines.join('\n')+'\n}';$('status').textContent=lines.length+' token'+(lines.length===1?'':'s')+' converted.'}else{const out={};const re=/--([\w-]+)\s*:\s*([^;{}]+)\s*;/g;let m;while((m=re.exec($('input').value)))out[m[1]]=m[2].trim();$('output').value=JSON.stringify(out,null,2);$('status').textContent=Object.keys(out).length+' CSS custom propert'+(Object.keys(out).length===1?'y':'ies')+' converted to flat JSON.'}$('status').className='helper'}catch(e){$('output').value='';$('status').textContent='Could not convert the input: '+e.message;$('status').className='helper danger'}}$('convert').onclick=convert;$('copy').onclick=async()=>{if(!$('output').value)return;try{await navigator.clipboard.writeText($('output').value);$('status').textContent='Output copied.'}catch(e){$('output').select();document.execCommand('copy');$('status').textContent='Output selected/copied where supported.'}};$('mode').onchange=()=>{if($('mode').value==='css'){$('input').value=':root {\n  --ds-color-primary: #2563eb;\n  --ds-space-md: 16px;\n}' }else{$('input').value='{"color":{"primary":"#2563eb","surface":"#ffffff"},"space":{"sm":"8px","md":"16px"}}'}convert()};$('reset').onclick=()=>{$('mode').value='json';$('prefix').value='ds';$('input').value='{"color":{"primary":"#2563eb","surface":"#ffffff"},"space":{"sm":"8px","md":"16px"},"radius":{"md":"8px"}}';convert()};convert()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>Design token converter for JSON and CSS custom properties</h2><p>Design tokens give reusable names to visual decisions such as colors, spacing, typography and radii. This converter flattens nested JSON keys into CSS-friendly names so a token like <code>color.primary</code> can become <code>--ds-color-primary</code>.</p>
<h2>JSON to CSS conversion rules</h2><p>Nested object paths are joined with hyphens and primitive values are written as custom-property values. Arrays and complex token schemas are left as string values rather than interpreted as a specific design-system standard. The optional prefix helps avoid collisions with third-party variables.</p>
<h2>CSS to JSON is intentionally flat</h2><p>CSS variable names do not preserve where each hyphen originally represented a hierarchy boundary, so reverse conversion produces a flat JSON object instead of guessing a nested structure. That makes the transformation predictable and avoids silently changing token meaning.</p>
<h2>Where this tool fits</h2><p>Use it when prototyping a design system, moving variables between design/dev handoffs, auditing a theme, or preparing a simple token bundle. Production token pipelines may also include aliases, references, modes, descriptions, type metadata and transformations; review those semantics before replacing a dedicated build tool.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['Does this converter support the Design Tokens Community Group format?','It can convert simple nested JSON values, but it does not interpret every DTCG metadata field, alias or mode. Review structured token systems before using the output as a production replacement.'],['Why is CSS converted back to flat JSON?','A CSS variable such as --space-card-large does not reveal which hyphens represented object nesting, so a flat representation avoids inventing hierarchy.'],['Is my token data uploaded?','No. The conversion logic runs in the browser and does not intentionally send the pasted token content to a server.'],['Can token values include calc(), color functions or CSS variables?','Yes when converting from CSS; values are preserved as text. JSON-to-CSS also writes primitive values as supplied.']];
require __DIR__.'/../includes/tool-template.php';
