<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('graphic-design','touch-target-size-checker');
ob_start();
?>
<h2>Check touch target size and spacing</h2><p class="lead">Compare a target's CSS pixel dimensions with the WCAG 2.2 24 × 24 CSS px minimum or a simplified same-size spacing condition.</p>
<div class="form-grid"><div class="field"><label for="w">Target width (CSS px)</label><input id="w" type="number" min="0" step="any" value="44"></div><div class="field"><label for="h">Target height (CSS px)</label><input id="h" type="number" min="0" step="any" value="44"></div><div class="field"><label for="gapX">Horizontal gap to same-size neighbor (px)</label><input id="gapX" type="number" min="0" step="any" value="8"></div><div class="field"><label for="gapY">Vertical gap to same-size neighbor (px)</label><input id="gapY" type="number" min="0" step="any" value="8"></div></div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Direct 24 × 24 test</span><strong id="direct">—</strong></div><div class="metric"><span>Horizontal center spacing</span><strong id="hx">—</strong></div><div class="metric"><span>Vertical center spacing</span><strong id="vy">—</strong></div><div class="metric"><span>Simplified result</span><strong id="result">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);function go(){const w=parseFloat($('w').value),h=parseFloat($('h').value),gx=parseFloat($('gapX').value),gy=parseFloat($('gapY').value);if(!(w>0&&h>0&&gx>=0&&gy>=0)){$('direct').textContent=$('hx').textContent=$('vy').textContent=$('result').textContent='—';$('note').textContent='Enter positive target dimensions and non-negative gaps.';$('note').className='helper danger';return}const direct=w>=24&&h>=24,hx=w+gx,vy=h+gy,space=hx>=24&&vy>=24;$('direct').textContent=direct?'Pass':'Needs exception/spacing review';$('hx').textContent=hx.toFixed(1)+' px';$('vy').textContent=vy.toFixed(1)+' px';$('result').textContent=direct||space?'Potential pass':'Likely too small/close';$('note').textContent=direct?'The target itself is at least 24 × 24 CSS px.':'WCAG 2.2 also permits certain spacing and specific exceptions. This simplified center-spacing check assumes same-sized neighboring targets and cannot prove conformance.';$('note').className='helper'+(direct||space?'':' danger')}['w','h','gapX','gapY'].forEach(id=>$(id).addEventListener('input',go));go()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>WCAG 2.2 touch target size checker</h2><p>WCAG 2.2 Success Criterion 2.5.8 Target Size (Minimum) requires pointer targets to be at least <strong>24 by 24 CSS pixels</strong>, or to satisfy a spacing condition, subject to listed exceptions. The official wording and exceptions matter for conformance. <a href="https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html" target="_blank" rel="noopener">W3C Target Size (Minimum) guidance</a>.</p>
<h2>What this checker does</h2><p>The direct test is simple: both width and height must be at least 24 CSS px. For smaller controls, this tool also shows center-to-center spacing using a simplified assumption that adjacent targets have the same dimensions and the entered edge gap. Real interfaces can have irregular shapes, diagonal neighbors, inline links and overlapping exclusion circles, so spacing needs visual/manual verification.</p>
<h2>Why larger targets may still be desirable</h2><p>Passing a minimum success criterion is not the same as creating an easy-to-use interface. Touch accuracy varies with device, motor ability, context and motion. Teams commonly choose larger controls for primary actions even when 24px would satisfy the minimum criterion.</p>
<h2>Use CSS pixels, not physical screen pixels</h2><p>WCAG expresses the requirement in CSS pixels. Inspect the rendered CSS box rather than multiplying by device pixel ratio. Also verify focus visibility, accessible names, keyboard operation and spacing as separate accessibility concerns.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What is the WCAG 2.2 minimum target size?','Success Criterion 2.5.8 uses 24 by 24 CSS pixels, with a spacing alternative and specific exceptions. Consult the W3C criterion for the complete rule.'],['Does a 24 × 24 button automatically make my page accessible?','No. Target size is only one requirement. Keyboard access, focus, contrast, labeling, semantics and other criteria still apply.'],['Why does the tool call the spacing result simplified?','The actual WCAG spacing condition uses non-overlapping 24px-diameter circles and can involve differently sized or positioned targets. This calculator assumes same-sized orthogonal neighbors.'],['Should I enter device pixels?','No. Enter the rendered target size in CSS pixels.']];
require __DIR__.'/../includes/tool-template.php';
