<?php
require __DIR__.'/../includes/bootstrap.php';
$tool=tool_by_path('graphic-design','wcag-contrast-checker');
ob_start();
?>
<h2>Check WCAG color contrast</h2><p class="lead">Enter foreground and background hex colors to calculate the relative-luminance contrast ratio and text thresholds.</p>
<div class="form-grid"><div class="field"><label for="fg">Foreground</label><input id="fg" type="text" value="#1f2937" maxlength="7"></div><div class="field"><label for="bg">Background</label><input id="bg" type="text" value="#ffffff" maxlength="7"></div></div>
<div id="preview" style="padding:22px;border-radius:10px;margin:14px 0;border:1px solid #ddd;font-size:20px">Contrast preview: readable text matters.</div>
<div class="result-box"><div class="result-grid"><div class="metric"><span>Contrast ratio</span><strong id="ratio">—</strong></div><div class="metric"><span>AA normal text</span><strong id="aa">—</strong></div><div class="metric"><span>AA large text</span><strong id="aal">—</strong></div><div class="metric"><span>AAA normal text</span><strong id="aaa">—</strong></div><div class="metric"><span>AAA large text</span><strong id="aaal">—</strong></div></div><div id="note" class="helper" style="margin-top:12px"></div></div>
<script>
(()=>{const $=id=>document.getElementById(id);function rgb(hex){hex=hex.trim();if(/^#[0-9a-f]{3}$/i.test(hex))hex='#'+[hex[1],hex[2],hex[3]].map(x=>x+x).join('');if(!/^#[0-9a-f]{6}$/i.test(hex))return null;return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255)}function lum(c){return c.map(v=>v<=0.04045?v/12.92:Math.pow((v+0.055)/1.055,2.4)).reduce((s,v,i)=>s+v*[0.2126,0.7152,0.0722][i],0)}function go(){const f=rgb($('fg').value),b=rgb($('bg').value);if(!f||!b){$('ratio').textContent=$('aa').textContent=$('aal').textContent=$('aaa').textContent=$('aaal').textContent='—';$('note').textContent='Use 3- or 6-digit hex colors such as #fff or #1f2937.';$('note').className='helper danger';return}const l1=lum(f),l2=lum(b),r=(Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05);$('ratio').textContent=r.toFixed(2)+':1';$('aa').textContent=r>=4.5?'Pass':'Fail';$('aal').textContent=r>=3?'Pass':'Fail';$('aaa').textContent=r>=7?'Pass':'Fail';$('aaal').textContent=r>=4.5?'Pass':'Fail';$('preview').style.color=$('fg').value;$('preview').style.backgroundColor=$('bg').value;$('note').textContent='Threshold checks use the unrounded ratio. Large text has a specific WCAG size/weight definition; UI components and non-text graphics use other criteria.';$('note').className='helper'}['fg','bg'].forEach(id=>$(id).addEventListener('input',go));go()})();
</script>
<?php
$toolBody=ob_get_clean();
ob_start();
?>
<h2>WCAG contrast ratio calculator</h2><p>WCAG 2.2 uses relative luminance to compare a text color with its background. For Success Criterion 1.4.3, normal text needs at least <strong>4.5:1</strong> contrast and large-scale text needs at least <strong>3:1</strong>. Enhanced (AAA) text contrast uses 7:1 for normal text and 4.5:1 for large text. <a href="https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html" target="_blank" rel="noopener">W3C Contrast (Minimum) guidance</a>.</p>
<h2>How contrast is calculated</h2><p>Each sRGB channel is linearized, weighted into relative luminance, and the lighter and darker luminances are used in <strong>(L1 + 0.05) ÷ (L2 + 0.05)</strong>. WCAG notes that threshold values should not be rounded upward for pass/fail decisions, so this tool compares the full precision value even though it displays two decimals.</p>
<h2>What counts as large text?</h2><p>Large-scale text is not simply anything that looks like a heading. WCAG defines it by rendered size and, for lower sizes, font weight. Check the current W3C definition for the exact CSS/point equivalents and do not apply the 3:1 threshold to ordinary body text.</p>
<h2>Contrast is only one accessibility check</h2><p>This calculator does not assess gradients, background images, transparency, hover/focus states, non-text contrast, font rendering or whether color is the only means of conveying information. Test the final rendered component and all interaction states.</p>
<?php
$toolContent=ob_get_clean();
$faqs=[['What contrast ratio does WCAG AA require?','For text under WCAG 2.2 SC 1.4.3, normal text requires at least 4.5:1 and large-scale text at least 3:1, subject to the criterion exceptions.'],['Why should contrast ratios not be rounded for compliance?','W3C explicitly notes that computed values should not be rounded to meet a threshold. The checker compares the raw value and only rounds the display.'],['Does this checker test button boundaries and icons?','No. Non-text UI components and graphical objects are evaluated under separate non-text contrast requirements.'],['Can I use 8-digit hex or transparency?','This version accepts solid 3- or 6-digit hex colors. Composite transparent colors against their actual background first.']];
require __DIR__.'/../includes/tool-template.php';
